### ISSUE TITLE
EXCEL CONTACTOS: Incorporar nuevos campos para revisión nuevas asignaciones de contactos a nuevas zonas

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#10]
![image](https://cloud.githubusercontent.com/assets/22589031/19693533/33429c7a-9adc-11e6-9820-78b088b7ac7c.png)
Para facilitar la revisión y reasignación de docentes a zonas/provincias, es necesario incorporar los campos de la columna CAMPOS A AÑADIR. 
Unicamente es necesario que aparezcan en el EXCEL.
Sería interesante también añadir el filtro PROMOTOR a los filtros disponibles.
@CristianBinpar

**Comment by minigoBinpar** [comment]
![image](https://cloud.githubusercontent.com/assets/20515815/20761062/0bb39a1c-b722-11e6-896f-9d4376cbcb4c.png)

Listo. Subo versión

**Comment by MACEMP** [comment]
Sigue sin aparecer en el excel los nuevos campos ¿está subida la nueva versión?
@minigoBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 

No, con PPD en progreso quedó pendiente. Hoy tengo intención de trabajar las issues de este proyecto y subir lo antes posible
