### ISSUE TITLE
Cambiar mensajes de completar fases

### ISSUE THREAD

**Issue by minigoBinpar** [BinPar/PRM#102]
Lllamnar angeles

**Comment by minigoBinpar** [comment]
Algo que anime al usuario, o que informe:
![image](https://cloud.githubusercontent.com/assets/20515815/26676565/7ef5b060-46c8-11e7-8aff-8147da437a06.png)

para fase 2, 3 y 4

**Comment by MACEMP** [comment]
Vamos a pasarte unos textos para que aparezcan al final de cada fase.
Serán tipo recordatorio de lo que le falta por hacer.
A Luis le ha gustado la idea.
Sigo en la jornada :-(
@minigoBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 
Ángeles, tienes las frases?

**Comment by MACEMP** [comment]
Todavía no me las ha pasado Luis.
Hoy lo veré y las paso.
@minigoBinpar

**Comment by MACEMP** [comment]
Estos son los textos que me ha facilitado Luis :

De Fase 1 a Fase 2: 

-	Recuerda realizar el seguimiento en la fecha que has concertado.

De Fase 2 a Fase 3:

-	Cierra la oferta económica y las condiciones de pago conforme a la política establecida

De Fase 3 a Fase 4

-	Prepara y envía el formulario para recoger la aceptación del pedido.

De Fase 4 a Fase 5

-	Envía toda la información para dar la venta como lograda ¡Enhorabuena!!


Fase 1: Primer contacto con el alumno y trasmisión de la información de curso concreto (Probabilidad 10%)
Fase 2: Contacto de Seguimiento realizado y concreción del programa (Probabilidad 30%)
Fase 3: Concreción de condiciones económicas y financiación (Probabilidad 60%)
Fase 4: Gestión de Hoja de pedido (Probabilidad 80%)
Fase 5: Tramitación del pedido (Probabilidad 100%) – Pedido enviado a Administración
@minigoBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 

Listo Ángeles. El mensaje de Fase4 a 5 no necesita mensaje porque lo que hace es mandarte al CRM para que la cierres.

Si lo ves necesario, podemos ingeniarnos algo para que se muestre

**Comment by MACEMP** [comment]
![image](https://user-images.githubusercontent.com/22589031/26865896-0d6d777a-4b5f-11e7-9101-c81e8377adfb.png)
No me aparece el mensaje ¿has subido versión?
@minigoBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 

Aún no. Te aviso :)

**Comment by MACEMP** [comment]
Sigo en reunión :-(
@minigoBinpar
