### ISSUE TITLE
Creación contacto post asignación a un user de Código Postal

### ISSUE THREAD

**Issue by minigoBinpar** [BinPar/PRM#107]
@MACEMP 

Ángeles, tenemos una duda de un hipotético caso que pudiera surgir:

Si estoy dando de alta un contacto con CP asignado a otro user, ¿qué ocurriría?. 

Hemos pensado 2 opciones:
1) Mensaje no puedes trabajar esta zona (no se guarda).
2) Se guarda y mostramos mensaje "contacto ha ido para user responsable de CP"

**Comment by MACEMP** [comment]
El VD (usuario vendedor venta directa) podrá crear contactos y oportunidades de clientes de otras zonas, p.e. contactos de los congresos.
En este caso:
-  el VD creará el contacto aunque no sea de su zona
- enviará un mail al ADMINISTRADOR del PRM informando del alta de un usuario en una "no zona" del VD 
-  el VD podrá crear y gestionar las oportunidades de este contacto de su "no zona"
- el ADMINISTRADOR podrá reasignar un contacto a otro VD
@CristianBinpar @minigoBinpar

**Comment by minigoBinpar** [comment]
- Al crear un contacto con CP que no pertenece al usuario que lo crea, se envía un email de aviso al administradorVD.

- Cuando un adminsitradorVD asigna CP´s con reasignación de contactos debe aparecer un modal con lista de usuarios y sus contactos en conflicto. El adminstradorVD selecciona los que finalmente se reasignarán y cuales no.

- Tiene que haber juego de emails con toda la info posible sobre los cambios realizados con destino a adminVD

**Comment by franciscorrr** [comment]
Cambios aplicados en PRO
