### ISSUE TITLE
PRM ACCESO EBOOK LATARJET: se ha producido una situación de excepción

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#108]
Noemí está intentando dar acceso al ebook de Latarjet (Colección o tomos sueltos)
![image](https://cloud.githubusercontent.com/assets/22589031/26691467/7bfab97a-46fd-11e7-9aa2-0ef2c69286ee.png)
 y obtiene este mensaje
![image](https://cloud.githubusercontent.com/assets/22589031/26690672/743e4060-46fa-11e7-92ef-635b1a286a8d.png)

El contacto al que quiere conceder el acceso a la colección Latarjet  es: 
jmartinez@ucam.edu
https://prm.medicapanamericana.com/Contacts/ShowContact@4d230eb6-18b2-4522-87c7-264e1a9509ba 
@CristianBinpar @minigoBinpar

**Comment by franciscorrr** [comment]
@MACEMP He estado repasando el código y no encuentro la razón para que se produzca el error, posiblemente se debiera a una discordancia entre los materiales de Panamericana y los que teníamos en la base de datos de PRM.

Como hace 2 días actualizamos la BBDD de PRM con los materiales, ¿podríais por favor volver a intentar dar acceso a este contacto al Ebook?. Si os sigue saliendo este error entonces probaremos otras opciones.

Gracias

**Comment by MACEMP** [comment]
Siento no poder realizar la prueba que solicitas. Al profesor ya se le facilitó el acceso desde el gestor de la web.
![image](https://user-images.githubusercontent.com/22589031/28710067-f6437120-7382-11e7-9968-29534362fd1f.png)
Si vuelve a ocurrir abriremos un nuevo caso.
@franciscorrr

**Comment by franciscorrr** [comment]
@MACEMP Como parece que la subida de materiales puede haber solucionado la incidencia, vamos a cerrarla. Si en algún momento vemos que se vuelve a reproducir la reabriremos.
