### ISSUE TITLE
ZONA NORDESTE REASIGNADA A OTROS PROMOTORES PERO NO APARECEN LOS CONTACTOS

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#11]
He asignado a NOEMÍ MARTÍN y ALEX NIETO la zona Nordeste, además de las zonas que ya tienen asignadas.
Noemí no consigue visualizar los contactos de la zona nordeste y sigue visualizando unicamente los de la zona centro.
El usuario Angel Perez, promotor de la zona nordeste hasta ayer, ya lo eliminé ayer como usuario del PRM
![image](https://cloud.githubusercontent.com/assets/22589031/19805493/29b4288c-9d15-11e6-891e-bef3852a9c49.png)
@CristianBinpar

**Comment by MACEMP** [comment]
Tanto Noemí Martín como Alex Nieto (con acceso autorizado en la zona Nordeste) siguen sin poder acceder a los contactos de la zona Nordeste.
Estoy enviando yo MAC los accesos a ebooks, pero lo deseable es que sean ellos los que puedan gestionar las acciones con los docentes de la zona Nordeste. En las comunicaciones a docentes aparecerá mi mail como contacto y no el suyo.
@minigoBinpar @CristianBinpar

**Comment by minigoBinpar** [comment]
Solucionada a falta de confirmación por parte de los interesados

**Comment by MACEMP** [comment]
Confirmado funciona correctamente
@minigoBinpar @CristianBinpar
