### ISSUE TITLE
CRM BETA: NO SE PUEDE UTILIZAR DNI NO VÁLIDO

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#110]
En beta no permite utilizar un DNI no válido
![image](https://cloud.githubusercontent.com/assets/22589031/26694323/49876e66-4707-11e7-8d61-e7991de376b3.png)

La funcionalidad de detectar si el DNI es correcto funciona perfectamente.

Para hacer los test hay que indicar siempre un DNI correcto.  
Prefiero utilizar datos no reales.
@CristianBinpar @minigoBinpar

**Comment by Al3xBinpar** [comment]
@MACEMP con cualquier cosa que tenga que ver con el CRM, por favor etiquétame y/o asigname a mi. Gracias.

**Comment by MACEMP** [comment]
Por supuesto. A partir de ahora lo haré
@Al3xBinpar
