### ISSUE TITLE
CRM BETA: NO ENVÍA CORREO DE CONFIRMACIÓN DE VENTA REALIZADA CORRECTAMENTE

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#111]
![image](https://cloud.githubusercontent.com/assets/22589031/26694496/e7cca082-4707-11e7-8fe9-80577b8aa877.png)
A pesar del mensaje en pantalla, no he recibido ningún mail notificando la venta.
El comprador (es decir mi usuario de prueba) tampoco ha recibido ningún mail ¿Cuándo se le notifica?
¿Cuándo Atención al cliente le factura?
@CristianBinpar @minigoBinpar

**Comment by Al3xBinpar** [comment]
Yo recibí los correos de confirmación de venta:
![image](https://cloud.githubusercontent.com/assets/25204866/26716467/bf537672-4779-11e7-9a9a-4493cf967d96.png)
Puedes verificarlo en tu bandeja de entrada?

El email de prueba (fulanitodetal@binpar.com) no existe como usuario de correo, pero si usases un correo que si existiera sí que recibiría una copia del correo.

Con respecto a: "¿Cuándo Atención al cliente le factura?" a qué te refieres?

**Comment by MACEMP** [comment]
1. Me refiero al correo que envía a macastro y lblecua.
En el mensaje ¡VENTA REALIZADA! indica que esos 2 destinatarios acaban de recibir un mensaje, pero no es así.
2. ¿Cuando atención al cliente le factura? Me refiero a ¿cuándo se notifica al cliente que ha adquirido el curso que su pedido ya ha sido tramitado? Al ver el correo que recibiste  veo que el cliente está incluido entre los destinatarios por lo tanto la duda ya está resuelta.
@Al3xBinpar

**Comment by MACEMP** [comment]
![image](https://user-images.githubusercontent.com/22589031/27227168-a9bdeba6-52a2-11e7-99ee-224cd8b0be80.png)
Sigo sin recibir en mi buzón macastro@medicapanamericana.es la confirmación de la venta, a pesar de que el mensaje indica que lo ha enviado.
@Al3xBinpar @minigoBinpar @CristianBinpar

**Comment by CristianBinpar** [comment]
Vamos a hacer una prueba con Marcos I en copia

**Comment by MACEMP** [comment]
Gracias.
ya me diréis si va bien.
@CristianBinpar @minigoBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 
El email parece enviarse correctamente y nos llega a todos (estás incluso en copia).

¿Puedes verlo ya?

![image](https://user-images.githubusercontent.com/20515815/27474987-dc648464-5803-11e7-905f-8d6d14840535.png)

**Comment by MACEMP** [comment]
No, no lo he recibido.
Este es mi buzón de entrada desde las 10:48

![image](https://user-images.githubusercontent.com/22589031/27475289-e49f9dca-5804-11e7-871e-5a997c5e1ea6.png)
@minigoBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 

El sistema envía el correo y gmail lo tramita correctamente. Creemos que esto ya toca la parte de seguridad y firewall de cada uno. 

A Luis Blecua le llega? Quizás tengamos que hablar con Jose por si tiene algo bloqueado

**Comment by MACEMP** [comment]
Confirmo que Luis tampoco ha recibido el mail.
Ninguno de los dos lo tenemos en la carpeta de NO DESEADOS - SPAM
@minigoBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 

Creo entonces que debe ser un tema de bloqueo

**Comment by MACEMP** [comment]
¿Habláis vosotros con Jose Rico?
@CristianBinpar @minigoBinpar

**Comment by MACEMP** [comment]
![image](https://user-images.githubusercontent.com/22589031/27482315-3c24cd92-5821-11e7-88c9-9b2fc8912599.png)
He creado un nuevo pedido. 
En pantalla aparece la confirmación de envío de mail a LBLECUA-MACASTRO-MINIGO .
Yo sigo sin recibirlo.
@minigoBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 

Ángeles, lo mejor es que hables con Jose Rico sobre este tema. De alguna forma tiene bloqueado el acceso de estos emails (el email si que se envía).

Te reenvío el correo para que tengas información.

**Comment by MACEMP** [comment]
Gracias.
Hablo con Jose Rico. Te mantengo informado
@minigoBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 
Perfecto. Cualquier cosa ya sabes

**Comment by minigoBinpar** [comment]
@MACEMP @Al3xBinpar 
Ángeles nos va a facilitar una dirección de correo @medicapanamericana que permita el envío de correos. 
También es necesario modificar el cuerpo del mensaje para incluir el email del VD que ha realizado la venta justo detrás de su nombre:
![image](https://user-images.githubusercontent.com/20515815/27529451-d6eafa9c-5a54-11e7-8e58-f1fd1a9562af.png)

**Comment by MACEMP** [comment]
He solicitado a Jose Rico la dirección de mail y contraseña 
crmventadirecta@medicapanamericana.com
Posiblemente se ponga en contacto con vosotros para aclarar alguna duda.
Ya le he comentado que esta dirección solo se utiliza a nivel de código y no se aloja en ninguna BBDD
@minigoBinpar @Al3xBinpar

**Comment by Al3xBinpar** [comment]
@minigoBinpar @MACEMP Jose Rico está informado de este tema. Cuando pueda ponerse en contacto conmigo, que lo haga y dejamos esto cerrado.

Por nuestra parte, de momento no podemos hacer nada más con esta issue. Dependemos de José Rico.

**Comment by Al3xBinpar** [comment]
Relacionada con #174

**Comment by MACEMP** [comment]
Hola José 
Esta issue queda pendiente hasta que hables con Alex de Binpar 
Saludos
Ángeles 

Enviado con Sophos Secure Email

El 27/6/17 18:06, 27/6/17 18:06 escribió:

>@minigoBinpar @MACEMP Jose Rico está informado de este tema. Cuando pueda ponerse en contacto conmigo, que lo haga y dejamos esto cerrado.
>
>Por nuestra parte, de momento no podemos hacer nada más con esta issue. Dependemos de José Rico.
>
>—
>You are receiving this because you were mentioned.
>Reply to this email directly, view it on GitHub, or mute the thread.￼
>
>{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/BinPar/PRM","title":"BinPar/PRM","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/BinPar/PRM"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Al3xBinpar in #111: @minigoBinpar @MACEMP Jose Rico está informado de este tema. Cuando pueda ponerse en contacto conmigo, que lo haga y dejamos esto cerrado.\r\n\r\nPor nuestra parte, de momento no podemos hacer nada más con esta issue. Dependemos de José Rico."}],"action":{"name":"View Issue","url":"https://github.com/BinPar/PRM/issues/111#issuecomment-311405937"}}}

Este correo electrónico y cualquier documento anexo que pudiera contener está dirigido exclusivamente a la persona o entidad que figura como destinatario. La información que contiene es confidencial y privada. En el caso de haber recibido esta comunicación por error le rogamos proceda a borrarlo de su sistema, ya que la copia, divulgación, distribución o cualquier uso indebido está legalmente prohibido.

This electronic mail and any attachments it may content is exclusively intended to the person or entity that figures as addressee. The information contained in it is confidential and private. Should you have received this message by mistake you are hereby urged to delete it from your system. Any copying, dissemination, distribution or use of this message or its attachments is prohibited by law.

**Comment by MACEMP** [comment]
Tanto Luis como yo hemos recibido la confirmación de pedido cuando el destinatario es Cristian@binpar.com
Quedamos a la espera de la conversación con Jose Rico
@Al3xBinpar @minigoBinpar
