### ISSUE TITLE
DATOS QUE NO SE VUELCAN DEL PRM AL CRM

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#112]
No vuelca del PRM al CRM:
![image](https://cloud.githubusercontent.com/assets/22589031/26695001/984e2e8e-4709-11e7-8144-6c1f5f6cd49f.png)
![image](https://cloud.githubusercontent.com/assets/22589031/26695034/abcc7600-4709-11e7-9248-7bf4bf4f6ac8.png)
@CristianBinpar @minigoBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 

Le damos una vuelta

**Comment by MACEMP** [comment]
OK!
@minigoBinpar

**Comment by MACEMP** [comment]
Marco en naranja los campos que debieran de tomar directamente del PRM
En verde el campo UNIVERSIDAD que debiera de tener el mismo desplegable que el PRM, para evitar un campo con texto libre.
Sugerencia: el país por defecto en ESPAÑA debiera ser ESPAÑA y no tener que seleccionar España de cada vez.

![image](https://user-images.githubusercontent.com/22589031/27632062-db8dafac-5bfa-11e7-8769-78d04d96023e.png)
@minigoBinpar @Al3xBinpar

**Comment by franciscorrr** [comment]
Cambios aplicados, pendiente de despliegue de CRM y PRM

@MACEMP una cuestión. He estado viendo que explícitamente en el código se está indicando que en caso de que estemos en el branch de España, el campo de universidad no sea un selector y pase a ser un campo de texto normal. ¿Se haría esto por alguna razón que desconozco?. Tal vez se hiciera para poder añadir manualmente universidades que no existiesen. 

Si esto no es así indícamelo en esta incidencia y la volvemos a reabrir para el tema este de las universidades.

**Comment by franciscorrr** [comment]
Debido a la incidencia #143 es posible que en algunos casos no se asigne automáticamente la provincia en los casos que no correspondan los nombres de la provincia en ambos sistemas (PRM - CRM)

**Comment by MACEMP** [comment]
Es extraño haber solicitado que en España, el campo universidad fuese texto libre, ya que intentamos homogeneizar al máximo los datos que se introducen. Si 9 vendedores van a introducir nombres de universidades, vamos a encontrarnos con 9 denominaciones distintas para la misma universidad.
Lo adecuado sería que el nombre de la universidad viniese ya del PRM, y en caso de no ser posible que el desplegable fuese el mismo.
También sería conveniente que, el Administrador pudiese añadir una nueva universidad al desplegable, en lugar de tener que hacerlo vosotros (p.e. acabo de solicitar que se añada una provincia al PRM de Colombia. Lo ideal sería que el Administrador o Superadministrador tuviese autorización para hacerlo).
@franciscorrr @minigoBinpar

**Comment by franciscorrr** [comment]
Ya hemos cambiado para que la universidad venga ya puesta desde el PRM
![image](https://user-images.githubusercontent.com/30254281/28813681-9fa4823a-769a-11e7-9780-828fa750b53b.png)
En cuanto a lo de añadir/modificar universidades no creo que haya problema, desde el PRM se pueden añadir nuevas (desde la misma pantalla donde se edita o crea el contacto) y como luego se envían al CRM, simplemente saldrán.
