### ISSUE TITLE
CORREGIR ERRATA "CONICIONES" DEBE DECIR CONDICIONES 

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#113]
![image](https://cloud.githubusercontent.com/assets/22589031/26695523/79caa580-470b-11e7-931f-8319bf01e6d5.png)
@CristianBinpar @minigoBinpar

**Comment by Al3xBinpar** [comment]
Hecho!

**Comment by MACEMP** [comment]
Gracias!
@Al3xBinpar
