### ISSUE TITLE
LOS PRECIOS EN PRM Y CRM NO COINCIDEN

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#115]
PRECIO EN CRM

http://betacrm.medicapanamericana.test/Login/VentaDirectaLogin?email=DEcW3XW9pwAs8NWqb9Gq9F3LaecL%2fJigY25%2bbMejpS4NMGdeOO5l83hLH15oC3yQZemb%2fNQH3tiD5FUj%2fGtoTSqrgh8Qsq88ftCwmKghAW2Ztf7nKWT5vA%3d%3d&isbn=0A36ahGXO7v0KtHUULFJfgijOOveKIC%2bs2gVeTQtWyDbq4WBZmRUFyiZ3LVYuHaK3KVXfIbvziGp1JhYuOYyS0zty75mFm06&remember=true&redirect=&leadEmail=j17g8hs7T9PoT7vVqanlgfiRIapqkIsFaKSnfMWm%2fgv7gExDCvNZifwbn%2fqPhjn8EZTRrvCkgmbSnXIr3H3Pcx6hBVApE3HVoYFQ732Z5xQ%3d&leadPhone=2xpK2aavZymOellvW%2bhVhaNvxMKXYlNedrM2PCigyw6L3bnyRkkML3kh7Gyguzv3f7vY%2bXR8xeMW5wbAuvVOoe3XsleVTSdZ&entityID=zKeCWEl2aEnNWnhNp71iSGHEUsYEGPch9wsZ3bYVhdlRNfY%2fsUbDznIiRv92%2fgpSgp7MRmsfBLT4nToU%2bL5Qb2Y2sjBbO2W30MtPp16eEOFTcq9ObekAsbVpIk8VAXMO&timelineEntityID=LgM%2bBTjNKjRXim%2f83ZuE8dhBJ0qzM62C2nELk03u0%2fYJwv0Ysa40R%2fL63%2b4eBlKRC2bcHHINxkUXjEu93P%2b7mgt3RgeLv9WKobbOHQRPQhN%2bay%2fEIj7h5WRTK47Bd3MA 
![image](https://cloud.githubusercontent.com/assets/22589031/26695766/58589e74-470c-11e7-9651-43d59b09403c.png)

PRECIO EN PRM
![image](https://cloud.githubusercontent.com/assets/22589031/26695823/9553e5fe-470c-11e7-88ad-15d56c1a533b.png)
http://betaprm.medicapanamericana.test/Login/AutenticateVentaDirecta?login=DEcW3XW9pwAs8NWqb9Gq9F3LaecL%2fJigY25%2bbMejpS4NMGdeOO5l83hLH15oC3yQZemb%2fNQH3tiD5FUj%2fGtoTSqrgh8Qsq88ftCwmKghAW2Ztf7nKWT5vA%3d%3d&pass=&remind=true&entityID=zKeCWEl2aEnNWnhNp71iSGHEUsYEGPch9wsZ3bYVhdlRNfY%2fsUbDznIiRv92%2fgpSgp7MRmsfBLT4nToU%2bL5Qb2Y2sjBbO2W30MtPp16eEOFTcq9ObekAsbVpIk8VAXMO&timelineEntityID=DEcW3XW9pwAs8NWqb9Gq9F3LaecL%2fJigY25%2bbMejpS4NMGdeOO5l83hLH15oC3yQZemb%2fNQH3tiD5FUj%2fGtoTSqrgh8Qsq88ftCwmKghAW2Ztf7nKWT5vA%3d%3d

@CristianBinpar @minigoBinpar

**Comment by Al3xBinpar** [comment]
Esto es porque en el CRM tenemos una sección de edición de productos, de tal manera que se realizó una importación inicial desde la WEB, pero luego se pueden modificar los precios de manera exclusiva para el CRM. @MACEMP @minigoBinpar @CristianBinpar
