### ISSUE TITLE
LAS DENOMINACIONES DE PRODUCTO NO SON LAS MISMAS EN PRM QUE EN CRM

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#116]
En PRM los productos aparecen DENOMINACIÓN SAP - EAN
En CRM los producto aparecen EAN - TÍTULO
Sería conveniente utilizar la misma denominación. Propongo la del PRM

DENOMINACIÓN EN PRM
![image](https://cloud.githubusercontent.com/assets/22589031/26695924/f31fe9ee-470c-11e7-985a-0736d91aa9d0.png)

DENOMINACION EN CRM
![image](https://cloud.githubusercontent.com/assets/22589031/26695948/0d3e5374-470d-11e7-8798-4c0ed7903813.png)
@CristianBinpar @minigoBinpar

**Comment by Al3xBinpar** [comment]
Hecho!

**Comment by minigoBinpar** [comment]
@MACEMP 

Me dicen que en todo caso primaría la denominación de CRM.

Si quieres, podemos plantear un cambio en las denominaciones de PRM para homologar todo.

**Comment by MACEMP** [comment]
Parece que hoy discrepamos.
La denominación SAP tiene la gran ventaja del tamaño y toda la información que aporta en 40 caracteres (practicamente un tweet)
Si se mantiene la denominación CRM y se pasa al PRM se convertirá en una columna con 100-150 caracteres, No nos interesa, sobre todo cuando se analiza la información en columnas. 
¿Podrían mantenerse las dos, como hacemos en el PPD?
@minigoBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 

Difícil que prime la denominación de PRM por la forma de trabajo de la gente de CRM (generaría confusión la denominación SAP).

Por otro lado, mantener las dos denominaciones es replicar información de forma innecesario.

**Comment by MACEMP** [comment]
De acuerdo,  **pero la denominación en PRM universitario ha de ser la de SAP,** no la denominación larga.

Por cierto, no sé cómo se verá en el histórico de oportunidades un título como éste:
_Programa Oficial de Actualización Profesional en Radiología de la SERAM (año 1)
Experto en técnica e instrumentación, urgencias en radiología, y neurorradiología_

@minigoBinpar

**Comment by CristianBinpar** [comment]
Debido a que habría varios colaterales al cambiar la denominación en CRM, por el momento, para esta fase dejaremos las denominaciones como siguen:

PRM: SAP - EAN
CRM: EAN - TITULO

El punto de unión entre ambos será siempre el EAN.

Aunque es un tema para analizar en el futuro, principalmente, en la creación de la futura web con BBDD común que se iniciará en agosto.

**Comment by MACEMP** [comment]
De acuerdo
@CristianBinpar @minigoBinpar
