### ISSUE TITLE
PETICIÓN DESDE COLOMBIA: INCLUSIÓN NUEVA PROVINCIA

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#119]
Desde Colombia, el promotor Gilberto Silva Luengas - COLOMBIA
solicita que se incorpore al PRM la provincia CUENCA

Mensaje original
_Respetada Ángeles, Buenos días,

Agradezco por favor la inclusión de la provincia CUENCA a mi PRM,_

@CristianBinpar @minigoBinpar

**Comment by MACEMP** [comment]
He recibido un mail desde Colombia preguntando por la resolución de este issue.
Gilberto no puede trabajar con los contactos de esta zona.

Muchas gracias.
@minigoBinpar

**Comment by MACEMP** [comment]
¿Está ya subida la provincia?
gracias
@minigoBinpar

**Comment by franciscorrr** [comment]
@MACEMP  Se ha añadido la provincia de Cuenca a Colombia en BETA y PRO

**Comment by MACEMP** [comment]
Gracias!
@franciscorrr
