### ISSUE TITLE
VD: Error llamada ajax

### ISSUE THREAD

**Issue by Al3xBinpar** [BinPar/PRM#122]
![image](https://user-images.githubusercontent.com/25204866/27025146-b180eea2-4f59-11e7-9130-53a111049d8e.png)

**Comment by minigoBinpar** [comment]
@Al3xBinpar 
El error viene dado porque las llamadas ajax a las funciones nacen del path. En el caso del retorno de crm, el login inicial de la url de retorno:

http://betaprm.medicapanamericana.test/Login/AutenticateVentaDirecta?login=%2fq1HVhWiA2fXlCkUw1FDyygM38gr6Lb5VlsEYyH8tLCijW%2fJ9oH7aq1hAH4%2bPodb4icngqOnTn8Wsvm02QZhFdro5cz2BAE2GJ9QLh9tRrDId%2fL1gLqYq%2bQzpB%2bQXVuU&pass=&remind=true&entityID=78XRFXIeQGuIit7amS0vJrdO1JdCohwPrdK6XLlPDZG5Tr6xaAUVXkO9kU0uKtASPbzdOaS%2b7EAF7zMxnLsu0m01DtAp4kOzTJvJ8t1B7%2fBwzB3WdhHJsDqNzcUPlm6B&timelineEntityID=j0y%2fUIERpk3i63y%2brrHhNVbIUuRR50%2fqD6JcqmVBUhkOxDqU8IfMKWmCsqFdC78FY2mYl15vvnVYRapnJJ%2bwGwclNf%2bsJCtM1fzoZCQF0MAFRGCQ38gQ7nm9h4rDpWC8
