### ISSUE TITLE
ADOPCIONES VALORIZADAS: CONTACTOS CON ADOPCIÓN NO APARECEN EN EL INFORME

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#124]
https://prm.medicapanamericana.com/Contacts/ShowContact@54dd8444-79b8-4c23-8ef3-a9a5d691f62e 
https://prm.medicapanamericana.com/Contacts/ShowContact@9fb92fc9-10bd-418b-aa9d-f76c722d2bc4 

![image](https://user-images.githubusercontent.com/22589031/27041363-159efa52-4f94-11e7-94d6-d56d5796660f.png)

Hemos localizado estos dos contactos con adopción confirmada para 2017-2018 que no aparecen en el INFORME ADOPCIONES VALORIZADAS o en el INFORME ADOPCIONES.

Esto se une a las 11 adopciones de NOEMÍ que aparecen en su informe y no aparecen en el que obtengo con el usuario administrador.

Parece que hay algún problema con los informes de adopciones.

@CristianBinpar @minigoBinpar

**Comment by franciscorrr** [comment]
La búsqueda por contacto (al igual que material y promotor) se está realizando por el nombre, no se puede buscar por email como estamos viendo en las capturas. 

Si buscamos por nombre nos aparece dentro de adopciones valorizadas. 

Hemos cambiado el mensaje "Buscador por contacto, material o promotor" por "Buscador por nombre de contacto, material o promotor" para que quede un poco más claro.

**Comment by franciscorrr** [comment]
En la incidencia #180 incluimos la búsqueda por email. En la #95 cambiamos el mecanismo de filtrado que evitaba que salieran algunos informes de adopciones valorizados que sí debían de salir. En cuanto esté disponible en los entornos os lo comunicaremos.

**Comment by franciscorrr** [comment]
Ya está funcionando en PRO
![image](https://user-images.githubusercontent.com/30254281/28609026-36d9df54-71e3-11e7-8eed-aa3a4cb4483a.png)

![image](https://user-images.githubusercontent.com/30254281/28609048-4ee097a0-71e3-11e7-9fcf-3d5595256df3.png)

**Comment by MACEMP** [comment]
Gracias
@franciscorrr
