### ISSUE TITLE
CAMPO EAN EN INFORMES EXCEL : FORMATO NÚMERO

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#125]
![image](https://user-images.githubusercontent.com/22589031/27070585-f1b43bda-5019-11e7-87e6-a9f44eaa9313.png)
Cuando se descarga un informe el campo EAN aparece con un signo "´" antes del número.
Esto hace que el tratamiento posterior de los datos implique la modificación del formato de todos los datos de la columna.
¿Podría descargarse al Excel con el formato Número?
@CristianBinpar @minigoBinpar

**Comment by CristianBinpar** [comment]
Hola @MACEMP ,

en realidad nosotros lo que construimos en un CSV, que luego excel te permite editar.

Y por tanto, no tenemos la opción de indicar formato al campo.

Es la mejor solución para que no lo imprima como un exponente en el excel.

**Comment by MACEMP** [comment]
Gracias. 
Ciertamente, el formato de campo se puede editar en Excel, pero si ya viene del origen con el formato número me evito 2 pasos en la transformación de datos.
Issue cerrado.
@CristianBinpar
