### ISSUE TITLE
Informe VD incluir filtro CLIENTE

### ISSUE THREAD

**Issue by minigoBinpar** [BinPar/PRM#127]
Incluir el filtro por cliente (entity).
@MACEMP también interesa este filtro en la agenda?

**Comment by MACEMP** [comment]
No entiendo qué es "agenda" . Sorry
@minigoBinpar

**Comment by MACEMP** [comment]
SI. 
Interesa el filtro en la agenda.
@minigoBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 

Entiendo que es para AdminVD y VD

**Comment by MACEMP** [comment]
Si, es para AdminVD y VD
@minigoBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 
Listo
![image](https://user-images.githubusercontent.com/20515815/27536660-756132b6-5a70-11e7-83cc-f3f36d42f00b.png)
