### ISSUE TITLE
PRM VD: COLUMNA UNIVERSIDAD/LIBRERÍA EN PANTALLA CONTACTOS

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#128]
![image](https://user-images.githubusercontent.com/22589031/27183483-fe46989a-51de-11e7-8611-8599f4807178.png)
En lugar de UNIVERSIDAD/LIBRERÍA debiera indicar HOSPITAL / CENTRO y/o SERVICIO
@CristianBinpar @minigoBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 
Listo. Los adminVD y los VD tienen la columna personalizada con respecto al resto de usuarios

**Comment by MACEMP** [comment]
Estoy deseando que subas versión para hacer los test ;-)
@minigoBinpar
