### ISSUE TITLE
PRM VD: LA BARRA DE DESPLAZAMIENTO ES EXCESIVAMENTE ESTRECHA

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#129]
![image](https://user-images.githubusercontent.com/22589031/27183621-8b4c10c6-51df-11e7-8631-9481e4c80da3.png)

En la pantalla PRM CONTACTOS, la barra de desplazamiento horizontal inferior es excesivamente estrecha lo que dificulta el desplazamiento en horizontal por la página.
Este desplazamiento es necesario para acceder a la lupa que permite llegar al CONTACTO.

2 soluciones:
- hacer más ancha la barra de desplazamiento
- poner una lupa al inicio del contacto y al final del contacto (este icono ya está)

Lo mismo aplica para el PRM UNIVERSITARIO

@CristianBinpar @minigoBinpar

**Comment by CristianBinpar** [comment]
solucionado con la adición de la lupa al inicio de los listados.

**Comment by MACEMP** [comment]
¡Magnífico!
Imagino que aplica a los 2 PRM.
@CristianBinpar

**Comment by CristianBinpar** [comment]
si

**Comment by MACEMP** [comment]
Perfecto! Gracias
@CristianBinpar
