### ISSUE TITLE
ERROR EN DESCARGA EXCEL ADOPCIONES NOEMÍ MARTIN

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#13]
Noemí ha detectado un error en la descarga de ADOPCIONES. Copio su correo.
Hola Ángeles,

Pasa algo curioso. He ido a Informes Adopciones. Y en PRM me dice que tengo 868 adopciones (entre todos los años)

Pero cuando le doy a que me lo exporte a Excel, me salen sólo 862 filas.

He mirado x encima, y uno de los que me falta en el Excel y sí sale en PRM es la adopción del Pierce de Alfredo de Bustos Rodríguez del curso 2016/17. Sí sale su adopción del curso 2015/16 pero no la del curso siguiente.

En azul se ve la que sí sale y la de debajo de ella, no sale en el Excel. ¿Por qué esta no sale y tampoco otros 5 que aún no sé cuales son y que sí salen en PRM?

 

![image](https://cloud.githubusercontent.com/assets/22589031/20066042/90bd929a-a510-11e6-9d61-da7b26398378.png)
@CristianBinpar

**Comment by minigoBinpar** [comment]
Hay algún condicionante en el excel que filtra y nos baja el número de adopciones (no sé seguro si es la falta de asignatura, titulación, subtítulo o algún otro campo..) Cuando suba versión se actualiza y yo sigo investigando

**Comment by MACEMP** [comment]
El problema persiste.
Adjunto un archivo con las adopciones que aparecen en pantalla y no en el excel.
@minigoBinpar @CristianBinpar 
[ADOPCIONES QUE NO SALEN EN EXCEL.docx](https://github.com/BinPar/PRM/files/619487/ADOPCIONES.QUE.NO.SALEN.EN.EXCEL.docx)

**Comment by minigoBinpar** [comment]
Hola Ángeles,

A esto le faltaba subir versión. Actualizo y todo debería ir bien
