### ISSUE TITLE
PRM VD: VALORAR POSIBLIDAD CREAR SECCION ADMINISTRACION PERFIL ADMINISTRADOR

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#130]
En esta sección el Administrador podría administrar:
- usuarios

@CristianBinpar @minigoBinpar

**Comment by MACEMP** [comment]
No se pueden verificar todas las funcionalidades del adminsitrador si no existen varios usuarios creando contactos.
Actualmente solo hay un usuario VD activo

@CristianBinpar @minigoBinpar

**Comment by minigoBinpar** [comment]
@MACEMP Ciertamente.

Tenemos ya más usuarios creados:
https://user-images.githubusercontent.com/20515815/27212764-873a819c-5262-11e7-92bd-08894233ca12.png

Voy a crear una sección de administración

**Comment by MACEMP** [comment]
Me parece perfecto que crees la sección administración de usuarios ;-)
@minigoBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 
Listo
![image](https://user-images.githubusercontent.com/20515815/27321213-a4355dc8-5599-11e7-8392-02b85294cf91.png)

![image](https://user-images.githubusercontent.com/20515815/27321233-b42dda48-5599-11e7-82d9-15b93571081a.png)

Subo en breves

**Comment by MACEMP** [comment]
![image](https://user-images.githubusercontent.com/22589031/27321290-efcd450c-5599-11e7-8f2d-3eae1c054b6a.png)
@minigoBinpar
