### ISSUE TITLE
PRM VD: EL TECLADO NUMERICO NO FUNCIONA AL INTRODUCIR EL NUMERO DE TELEFONO

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#131]
![image](https://user-images.githubusercontent.com/22589031/27184598-ee746bdc-51e2-11e7-8720-509ef5dba126.png)
Al introducir el número de teléfono con el teclado numérico, éste NO FUNCIONA.
Se puede introducir únicamente con los números del teclado normal.
@CristianBinpar @minigoBinpar

**Comment by minigoBinpar** [comment]
Totalmente intencionado como medida de seguridad ya que tenemos que ser más exigentes con los datos que se introducen en PRM ahora que guardan relación con una venta directa en el CRM

 Hay que usar estos:
http://www.secretosinformaticos.com/wp-content/uploads/2011/10/cambiarPesta%C3%B1asWin.png

**Comment by MACEMP** [comment]
¡Entendido!
@minigoBinpar
