### ISSUE TITLE
PRM VD: EL BOTON "GUARDAR CONTACTO" NO FUNCIONA

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#132]
![image](https://user-images.githubusercontent.com/22589031/27184818-9c454a2e-51e3-11e7-93ba-8bb33d5ded18.png)

Como no funciona el botón GUARDAR no puedo crear contactos con el usuario ADMINISTRADOR
@CristianBinpar @minigoBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 

Cierro por #133

Si quieres comentar este tema no dudes en llamar!
