### ISSUE TITLE
PRM VD: TIPO CONTACTO

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#133]
![image](https://user-images.githubusercontent.com/22589031/27184957-0cc7ba8e-51e4-11e7-8649-1d80ee073703.png)
Los tipos de contacto tendría que ser iguales a los que aparecen en el CRM.
Actualmente aparecen los de PROMOCIÓN UNIVERSITARIA
@CristianBinpar @minigoBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 
Vamos a impedir acceso a creación de user a los AdminVD (no tiene mucho sentido por lo que comentaba antes de Administradores haciendo ventas)
