### ISSUE TITLE
PRM VD: EL ADMINISTRADOR NO PUEDE CREAR NUEVAS OPORTUNIDADES

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#134]
![image](https://user-images.githubusercontent.com/22589031/27188139-88ddb00c-51ed-11e7-8aed-70d234d4a56b.png)
El botón + OPORTUNIDAD está desactivado.
¿Cómo puede el Administrador generar una nueva oportunidad?  La persona que realice la función de administrador ¿tendrá que tener dos usuarios en el PRM VD uno como un usuario VENDEDOR y otro como usuario ADMINISTRADOR?
@CristianBinpar @minigoBinpar

**Comment by minigoBinpar** [comment]
Bloqueamos la opción de crear oportunidades porque entendimos que es un perfil para administrar, no para vender. 

Además estás empleando la vista de un vendedor, por lo que tus acciones como administrador se reportarían sobre las de un tercero, lo cual puede ser un poco confuso.

No obstante, si se te ocurre alguna otra cosa no dudes en decirnos

**Comment by MACEMP** [comment]
De acuerdo, el Administrador no tendrá posibilidad de generar una nueva oportunidad o crear un nuevo contacto

Pasará la información al VD correspondiente para que sea el Vendedor quién genere el contacto y la oportunidad.
@minigoBinpar
