### ISSUE TITLE
PRM VD:  PANTALLA INICIO - BOTONES COMPARAR - REPRESENTACIÓN EUROS

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#135]
![image](https://user-images.githubusercontent.com/22589031/27188364-371abd7c-51ee-11e7-9460-128957543c74.png)
1. Los botones COMPARAR no están alineados
2. Los botones COMPARAR no responden
3. Las cantidades en euros debieran de llevar "." para separar los miles y "," para separar los decimales
@CristianBinpar @minigoBinpar

**Comment by Al3xBinpar** [comment]
Hecho!
