### ISSUE TITLE
PRM VD: LOS BOTONES EXPORTAR A EXCEL NO FUNCIONAN

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#136]
Los botones EXPORTAR a Excel no funcionan ni en la sección CONTACTOS ni en INFORMES
@CristianBinpar @minigoBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 
Deberían responder correctamente. Pero un poco de testing tampoco estaría de más

**Comment by MACEMP** [comment]
No funcionan ni con el usuario ADMINSTRADOR ni con el usuario VD
@minigoBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 
Prueba ahora

**Comment by MACEMP** [comment]
EXCEL CONTACTOS USUARIO ADMINISTRADOR
![image](https://user-images.githubusercontent.com/22589031/27376847-9fd7aea4-5673-11e7-9d78-4e51f5015885.png)
![image](https://user-images.githubusercontent.com/22589031/27377434-3e8fe556-5675-11e7-9700-1d8d5537f742.png)
En el Excel hay campos que no tienen el encabezado
En el Excel hay que sustituir Universidad/Librería por Hospital/Centro/Servicio
En el Excel hay que añadir el País
En Pantalla no aparece Localidad ni Código postal
En Pantalla no aparece Especialidad
En Pantalla no aparece una de las columnas sin nombre del Excel

Pendiente de revisar el Excel INFORME VENTA DIRECTA
@minigoBinpar

**Comment by minigoBinpar** [comment]
Excel DOCENTES:
- Elimino los campos sin encabezado (información no reflejada por pantalla).
- Sustituyo Universidad por Hospital  y añado país al Excel.
- Añado Localidad, CP y Especialidad por pantalla:
![image](https://user-images.githubusercontent.com/20515815/27421443-bb15f344-572a-11e7-892a-2cb8708b6d99.png)

Excel INFORME:
- Añado Especialidad e Importe al EXCEL
