### ISSUE TITLE
PRM VD: CAMPO PROVINCIA NO QUEDA GRABADO EL DATO

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#137]
Cuando se modifica el campo PROVINCIA queda en blanco como si no se hubiese introducido la provincia, sin embargo al volver a entrar en el contacto ¡¡¡APARECE!!!

Introduzco el dato PROVINCIA
![image](https://user-images.githubusercontent.com/22589031/27188790-9a60c696-51ef-11e7-85aa-6ea5c577d112.png)
DATO PROVINCIA NO APARECE
![image](https://user-images.githubusercontent.com/22589031/27188817-ac415cd6-51ef-11e7-88d6-e0927bc2b068.png)
SALGO Y ENTRO AL CONTACTO - DATO PROVINCIA APARECE
![image](https://user-images.githubusercontent.com/22589031/27188837-bf3096a4-51ef-11e7-82e1-1714b47daf6d.png)

Cuando se introduce un dato en un campo desde un desplegable o con texto libre, debiera de aparecer al momento y no tener que refrescar la página.
El usuario percibe que no ha quedado grabado el dato.

@CristianBinpar @minigoBinpar

**Comment by minigoBinpar** [comment]
@MACEMP ciertamente, el efecto es cuanto menos, confuso.

Ya lo he solucionado y subo versión a beta en breves
