### ISSUE TITLE
PRM VD: SUSTITUIR ADOPCIONES POR OPORTUNIDADES

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#138]
![image](https://user-images.githubusercontent.com/22589031/27188977-34015130-51f0-11e7-9017-d5d6ea100206.png)
@CristianBinpar @minigoBinpar

**Comment by minigoBinpar** [comment]
Próxima subida
![image](https://user-images.githubusercontent.com/20515815/27212863-5cc40cd4-5263-11e7-8bf5-238e29c1cdc7.png)
