### ISSUE TITLE
PRM VD: INFORME VENTA DIRECTA

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#139]
En el Informe en pantalla aparece únicamente el último estado de la oportunidad
¿Habrá otro informe Excel con el histórico?
Sería conveniente que hubiese los 2 informes, a semejanza del PRM UNIVERSITARIO.
@CristianBinpar @minigoBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 

He montado un botón en el informe actual que permite obtener el histórico de VD:
![image](https://user-images.githubusercontent.com/20515815/27445958-0ae48402-577c-11e7-8a15-a5fcb9cf08b4.png)

Al hacer click, cambia y nos muestra todo:
![image](https://user-images.githubusercontent.com/20515815/27445973-1abd0818-577c-11e7-92e4-9ff7ee199a8e.png)


Plus: modifico también el excel

**Comment by MACEMP** [comment]
Magnífica solución.

Usuario ADMINISTRADOR
El excel no descarga los campos ESPECIALIDAD ni IMPORTE

![image](https://user-images.githubusercontent.com/22589031/27483111-5cbb727e-5824-11e7-9cb9-6dde5395a1e7.png)

El número de Oportunidades en curso que aparecen en el INFORME no coincide con el que aparece en la PANTALLA INICIO

![image](https://user-images.githubusercontent.com/22589031/27483093-4ee80bf8-5824-11e7-9295-3384642de1dc.png)

![image](https://user-images.githubusercontent.com/22589031/27483207-be51c2b8-5824-11e7-8f7a-8543eaa2e656.png)


El usuario VD no tiene habilitado el botón para ver el histórico . Habría que habilitarlo también en el VD no solo en el Administrador.

@CristianBinpar @minigoBinpar

**Comment by MACEMP** [comment]
El informe en Excel  del VD macastroVD sale sin datos
![image](https://user-images.githubusercontent.com/22589031/27483378-676e84e4-5825-11e7-9c95-9b1931a1dd52.png)
@minigoBinpar

**Comment by minigoBinpar** [comment]
1. Completamos los campos de especialidad e importe:
[Desktop.zip](https://github.com/BinPar/PRM/files/1101239/Desktop.zip)

2. No es que no coincidan los números, sino que el filtro falla. Ya está solucionado.

3. Los usuarios VD ya tienen habilitada la funcionalidad para ver el histórico:
![image](https://user-images.githubusercontent.com/20515815/27528112-28719eee-5a4f-11e7-9540-d5437307d25d.png)

4. Corregido el informe de los VD:
[Desktop.zip](https://github.com/BinPar/PRM/files/1101276/Desktop.zip)

**Comment by MACEMP** [comment]
Perfecto!
@minigoBinpar
