### ISSUE TITLE
PRM VD: GRÁFICO CIRCULAR

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#140]
¿Cómo se lee este gráfico? ¿se podría añadir el importe y el % de cada estado?
![image](https://user-images.githubusercontent.com/22589031/27189243-14e49a0e-51f1-11e7-908d-942aaddb93a8.png)

Algo similar a esto:
![image](https://user-images.githubusercontent.com/22589031/27189434-a2209f6c-51f1-11e7-820e-822ff93f3b35.png)

@CristianBinpar @minigoBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 

El pluggin que empleamos para crear esos chart no soporta esta petición. Tiene un sistema de hover en el cual podemos añadir algo más de info si así lo consideras necesario.

**Comment by MACEMP** [comment]
¿qué información se podría añadir al hover?
@minigoBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 

Me atrevería a decir que casi toda la información que veas que será de utilidad, podríamos incluirla sin muchos problemas.

**Comment by MACEMP** [comment]
Modificación de las leyendas ESTADO OPORTUNIDAD:
Fase 1= **1.Primer contacto**
Fase 2= **2. Seguimiento realizado**
Fase 3= **3. Concreción condiciones**
Fase 4= **4. Gestión H.Pedido** 
Fase 5= **5. Pedido enviado**
**Oportunidad Perdida**
La información que ha de aportar cada porción del chart (similar a la que aparece en el gráfico de más arriba).
- Porcentaje del total
- Número de oportunidades
- Importe de cada porción

@minigoBinpar

**Comment by Al3xBinpar** [comment]
Buenos días @MACEMP, he estado realizando varias pruebas con el gráfico y no admite valores de cadena. Únicamente valores numéricos.

Te vale que hagamos este desglose en un listado que aparezca al lado o debajo del gráfico?

Un saludo
@minigoBinpar

**Comment by MACEMP** [comment]
Buenos días @Al3xBinpar , no habría problema siempre que el usuario interprete facilmente el gráfico y la información aportada.
@Al3xBinpar @minigoBinpar

**Comment by MACEMP** [comment]
![image](https://user-images.githubusercontent.com/22589031/27482688-b3b2b74c-5822-11e7-9ae9-6e2e7d1f437f.png)

Entiendo que el porcentaje no puede aparecer ¿verdad?
@Al3xBinpar

**Comment by MACEMP** [comment]
Ha quedado muy ilustrativo.
Sugerencia: ¿Podría ser el círculo de menor tamaño?
Con el tamaño actual no permite ver en una sola pantalla los datos totales y la comparativa de barras.
Por otra parte ¿Cómo se leen los datos de las barras?
KPI PROMOTOR vs KPI TOTAL
Habría que cambiar PROMOTOR por VD o VENDEDOR.

Muchas gracias.

![image](https://user-images.githubusercontent.com/22589031/27482836-4571b552-5823-11e7-937d-0836e58aca76.png)
@minigoBinpar @Al3xBinpar
