### ISSUE TITLE
PRM VD: NO PUEDO SEGUIR CON LOS TEST - NO DISPONGO DE USUARIO VENDEDOR

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#141]
No están operativos los usuarios anteriormente creados, por lo que no puedo seguir testando :-(
@CristianBinpar @minigoBinpar

**Comment by minigoBinpar** [comment]
@MACEMP aquí están los creados para el testing:

![image](https://user-images.githubusercontent.com/20515815/27212764-873a819c-5262-11e7-92bd-08894233ca12.png)


alexandreventadirecta@binpar.com    12341234
minigoventadirecta@binpar.com    12341234
mcastroventadirecta@binpar.com    12341234
cristianventadirecta@binpar.com    12341234

**Comment by MACEMP** [comment]
¡Gracias!
@minigoBinpar
