### ISSUE TITLE
PRM VD: UN VENDEDOR PUEDE MODIFICAR LOS DATOS DE UN CONTACTO DE OTRO VENDEDOR

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#142]
![image](https://user-images.githubusercontent.com/22589031/27226069-7a5b2536-529d-11e7-87f3-63c1b43b4c39.png)
El VD alexandreventadirecta creó un contacto con mail entity2@binpar.com y generó una oportunidad en fase1 Nombre ENTITY2 ENTITY2
El VD mcastroventadirecta modificó el mail entity2@binpar.com y siguió trabajando con la oportunidad creada por alexandreventadirecta  Nombre ENTITY DOS BI

El contacto entity2@binpar.com ha desaparecido de los contactos de alexandreventadirecta y aparece como contacto de mcastroventadirecta.

En resumen: se pueden "robar" los contactos.
El sistema emite avisos, pero no informa de a qué VD pertenece el contacto que se va a sobreescribir.

![image](https://user-images.githubusercontent.com/22589031/27226281-7facf9b4-529e-11e7-9c3a-b4527b8070b3.png)

Sería conveniente que el aviso indicase que ese contacto ya está creado por  VENDEDOR XXXXX para que no siguiese adelante con la carga de datos. Si se tratase de un contacto suyo, le estaría advirtiendo de que ya está creado por el mismo.
@CristianBinpar @minigoBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 
Cuando un VD intenta "robar" un contacto a otro VD mediante el email se muestra el siguiente mensaje:
![image](https://user-images.githubusercontent.com/20515815/27292429-b70bfcee-5513-11e7-9e2a-d8e5f7191ffa.png)

(He optado por no dar más información de nadie en caso de que surja algún conflicto de seguridad o de protección de datos).

**Comment by MACEMP** [comment]
¡Qué cauto! ;-)
@minigoBinpar
