### ISSUE TITLE
PRM VD: EL DESGLEGABLE DE MATERIAL ES MUY MUY MUY PEQUEÑO

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#144]
![image](https://user-images.githubusercontent.com/22589031/27231518-235d99f6-52b3-11e7-8aa8-b42a2e7415aa.png)
El desplegable de MATERIAL es tan pequeño que no permite leer la denominación del material.
Sería conveniente que se pudiesen leer 3-4 líneas de materiales.
@CristianBinpar @minigoBinpar

**Comment by MACEMP** [comment]
El desplegable sigue siendo muy muy muy muy muy muy muy pequeño. No se ven los materiales
@minigoBinpar

**Comment by Al3xBinpar** [comment]
Qué navegador usas @MACEMP ?

**Comment by MACEMP** [comment]
Chrome
@minigoBinpar @Al3xBinpar

**Comment by Al3xBinpar** [comment]
@MACEMP es raro, en chrome así lo vemos nosotros: 
![image](https://user-images.githubusercontent.com/25204866/27627347-c6b23cd8-5beb-11e7-9d95-05cf77a8795f.png)

**Comment by MACEMP** [comment]
![image](https://user-images.githubusercontent.com/22589031/27627436-0d1ac262-5bec-11e7-9835-c4c1590584b1.png)
Esto es lo que yo veo ¡Qué raro!
@Al3xBinpar @minigoBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 
En producción lo mismo
![image](https://user-images.githubusercontent.com/20515815/27627792-58689d56-5bed-11e7-8084-9801e9bd25b8.png)

**Comment by MACEMP** [comment]
Es un misterio. Noemí y Alex lo ven perfectamente.
Voy a probar el clásico CTRL+ SHFT + R

¡¡EUREKA!!  Funcionó
@minigoBinpar @Al3xBinpar
