### ISSUE TITLE
PRM VD: ¿CÓMO SE HACE RETORNO DE CARRO EN LOS COMENTARIOS?

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#145]
![image](https://user-images.githubusercontent.com/22589031/27231722-d72662a6-52b3-11e7-8ad4-00cd29097dae.png)
Si se utiliza la tecla RETURN, se graba el comentario, no se cambia de línea.
@CristianBinpar @minigoBinpar

**Comment by franciscorrr** [comment]
Pendiente de despliegue en los entornos.

Hemos incluido un botón para guardar (como en la creación de un comentario) y otro para cancelar la edición. De esta forma ya se puede utilizar el botón "intro" para crear una nueva línea.

![image](https://user-images.githubusercontent.com/30254281/28459473-e8d3d144-6e0d-11e7-8881-e689f5867a02.png)

**Comment by MACEMP** [comment]
¡Magnífico!
@franciscorrr
