### ISSUE TITLE
PRM VD: NO APARECE NINGUNA SUBESPECIALIDAD CUANDO SE CUMPLIMENTA EL PEDIDO EN EL CRM

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#146]
![image](https://user-images.githubusercontent.com/22589031/27231894-713d98c8-52b4-11e7-9e75-e7288a210f08.png)

No aparece ninguna SUBESPECIALIDAD en el campo SUBESPECIALIDAD ni aparece el signo + para añadir una nueva.

¿Puede el administrador del CRM añadir SUBESPECIALIDADES?
@CristianBinpar @minigoBinpar @Al3xBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 

El campo en cuestión hace referencia a la subespecialidad de la profesión. Según la elección de profesión, variarán las subespecialdiades.

Los admin no pueden crearlas. Sólo notros desde base de datos.

**Comment by MACEMP** [comment]
¿No sería más conveniente que el Administrador pudiese crear subespecialidades?
Agilizaría la gestión.
@minigoBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 
Me dicen que no. Hace un año se creó intencionadamente cerrado para controlar el dato.

**Comment by MACEMP** [comment]
OK!
@minigoBinpar
