### ISSUE TITLE
PRM VD & CRM: GESTIÓN PEDIDO EN CRM ¿TIENE SENTIDO QUE APAREZCA CUOTAS 0?

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#147]
![image](https://user-images.githubusercontent.com/22589031/27232416-474af748-52b6-11e7-9652-6ee73b28d63f.png)

En el campo CUOTAS aparece 0. No sé en qué puede afectar que aparezca, pero tal vez sería mejor empezar la serie en 1.

Por otra parte, la denominación del CRM y PRM del material sigue siendo distinta.
@CristianBinpar @minigoBinpar @Al3xBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 

Me dicen que seleccionamos 0 por defecto y que debe ser el vendedor el que ajuste el valor. 

No obstante, si consideras mejor otro valor lo establecemos en el momento.

**Comment by MACEMP** [comment]
Creo que nunca habrá una venta con 0 cuotas. Entiendo que 1 debiera ser la cantidad por defecto.
1 cuota = total importe factura
¿qué opinas?
@minigoBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 
Sin problema. Asigno la tarea a @Al3xBinpar
