### ISSUE TITLE
PRM VD: INFORME VENTA DIRECTA - ICONO FASE

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#148]
![image](https://user-images.githubusercontent.com/22589031/27232755-7ef9f51c-52b7-11e7-9b29-68fd35d2dd65.png)
¿Podría añadirse el icono de la fase, además del Fase 1, Fase 2....?
Sería más atractivo visualmente.
@CristianBinpar @minigoBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 
Listo:
![image](https://user-images.githubusercontent.com/20515815/27283742-04cd3362-54f6-11e7-87fb-9708a2c40160.png)


[Informe_VDs_1497872576143 (1).zip](https://github.com/BinPar/PRM/files/1084771/Informe_VDs_1497872576143.1.zip)

**Comment by MACEMP** [comment]
¡Queda mucho más visual! Gracias
@minigoBinpar
