### ISSUE TITLE
PRM VD: INFORME VENTA DIRECTA NO FUNCIONAN LOS FILTROS

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#149]
**FILTRO CÓDIGO POSTAL**

![image](https://user-images.githubusercontent.com/22589031/27232912-0063d1b8-52b8-11e7-8a9b-449f8b3d9c3b.png)
¿Podría funcionar con comodines?
P.e. si el contacto está en Madrid, pero no sé el código, indicar 28*** o 28???

**FILTRO FECHA**
![image](https://user-images.githubusercontent.com/22589031/27233002-4f94eba0-52b8-11e7-9f0d-a92ea61cf886.png)

¿Cuál es la fecha que filtra? ¿La de creación del contacto? ¿la de creación de la oportunidad? ¿la del último estado de oportunidad?

**FILTRO MATERIAL**

![image](https://user-images.githubusercontent.com/22589031/27233121-bce1c3ae-52b8-11e7-8704-6cf9a6ab6adf.png)
Indica 1 de 2 adopciones, pero no muestra el resultado
Por cierto indica ADOPCIONES. Hay que modificarlo por OPORTUNIDADES

**FILTRO ESTADO**

![image](https://user-images.githubusercontent.com/22589031/27233215-0d9cc9c4-52b9-11e7-85e2-e4dfd3215d8a.png)

No funciona. Indica 1 de 2 adopciones cuando son 2 de 2 las OPORTUNIDADES GANADAS

@CristianBinpar @minigoBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 
Corregidos
