### ISSUE TITLE
EBOOK MOORE NO APARECE ICONO MATERIAL COMPLEMENTARIO

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#15]
Alex Nieto reporta el mismo error en el MOORE que en el JAUREGI, ambos en la versión ebook
__Los  materiales complementarios los tiene activados en el PRM, pero realmente no se activan.
Al trabajar con el eBook de Moore no aparece el icono de Materiales en el PRM, esto ya sabíamos que fallaba. 
El problema es que, al trabajar con Moore en papel, sí que aparece el botón de materiales, pero al activarlo no funciona. (el mensaje del PRM confirma que se han activado correctamente, y no es así)
Espero que lo puedan solucionar_
@CristianBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 

Ángeles, ¿puedes decirme sobre que docente y promoción se da este caso?

No consigo replicar la incidencia

**Comment by MACEMP** [comment]
Se da en todos los docentes que tienen entregado el **ebook** del Moore.  En la versión papel aparece el icono.
@minigoBinpar @CristianBinpar

**Comment by minigoBinpar** [comment]
Cierro esta issue porque la tenemos duplicada con la #9
