### ISSUE TITLE
PRM VD: INFORME VENTA DIRECTA NO APARECE EL IMPORTE 

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#150]
![image](https://user-images.githubusercontent.com/22589031/27233401-9c0ab900-52b9-11e7-99ba-349c562f6d01.png)
Tiene que aparecer el importe de cada  Línea -OPORTUNIDAD
@CristianBinpar @minigoBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 
![image](https://user-images.githubusercontent.com/20515815/27287804-2391bc00-5505-11e7-848c-5ef20adec513.png)

**Comment by MACEMP** [comment]
¡Magnífico!
Si aparece en pantalla, aparece en el Excel ¿verdad?
@minigoBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 
Correcto. En cuanto suba versión, lo tendrás todo :)
