### ISSUE TITLE
PRM VD: SUSTITUIR DOCENTE POR CONTACTO

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#151]
![image](https://user-images.githubusercontent.com/22589031/27237181-64ab14f0-52c8-11e7-981f-26496b2e5924.png)

Donde dice "Último docente visitado" debe decir "Último contacto visitado"
@CristianBinpar @minigoBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 
Asumo que es un cambio para los VD

**Comment by MACEMP** [comment]
Si, en el título del mensaje se indica PRM VD ;-)
@minigoBinpar

**Comment by minigoBinpar** [comment]
@MACEMP
mal por mi parte trabajar sin un primer café

**Comment by MACEMP** [comment]
JAJAJAJA
![image](https://user-images.githubusercontent.com/22589031/27273179-246a9aca-54ce-11e7-9a13-016eeea2247b.png)

@minigoBinpar

**Comment by MACEMP** [comment]
![image](https://user-images.githubusercontent.com/22589031/27343413-0bdd1148-55e3-11e7-9c6b-2464eee74f07.png)
Sigue apareciendo DOCENTE en el lateral izquierdo del menú del USUARIO ADMINSITRADOR
@minigoBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 

Controlado:

![image](https://user-images.githubusercontent.com/20515815/27420620-fd5b85c4-5726-11e7-8c89-4b33b7dfd8fc.png)

Subo en breves.
