### ISSUE TITLE
PRM VD: Informe VD incluir filtro ESPECIALIDAD

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#152]
Solicitamos incluir el filtro ESPECIALIDAD y la columna ESPECIALIDAD en INFORME EN PANTALLA y en INFORME EXCEL DESCARGADO
@minigoBinpar @CristianBinpar

**Comment by minigoBinpar** [comment]
@MACEMP

Incluyo la especialidad principal de la entidad en el listado de resultados:
![image](https://user-images.githubusercontent.com/20515815/27280645-f391e14a-54e8-11e7-96ae-b9105001573b.png)

Y también en los filtros:
![image](https://user-images.githubusercontent.com/20515815/27281985-76769952-54ee-11e7-92f0-427df7db4b27.png)

**Comment by MACEMP** [comment]
Perfecto!
En el Excel también ¿verdad?
@minigoBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 
Si sale en pantalla, en el excel igual :)

**Comment by MACEMP** [comment]
¡Fenomenal!
@minigoBinpar
