### ISSUE TITLE
AdminVD: capacidad para editar el VD de cada contacto

### ISSUE THREAD

**Issue by minigoBinpar** [BinPar/PRM#153]
La duda es si establecer la edición aquí:

![image](https://user-images.githubusercontent.com/20515815/27293588-2d1e786e-5517-11e7-861c-37a51c0da736.png)

En crear una nueva sección en administración que permita ver listado y administrar varios de forma simultánea

**Comment by minigoBinpar** [comment]
@MACEMP 
Tercera opción planteada: en el propio listado de contactos (desde la visata de un adminVD) dar la capacidad de seleccionar varios entities y asignar a un nuevo VD

**Comment by MACEMP** [comment]
Muy buena!!
Permite la edición en bloque de varios contactos.
@minigoBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 
Listo
![image](https://user-images.githubusercontent.com/20515815/27390512-bc10d39c-56a1-11e7-89ea-
4a7c40ffc9dc.png)

![image](https://user-images.githubusercontent.com/20515815/27390539-d06349c4-56a1-11e7-8963-f4d138d7a485.png)

**Comment by MACEMP** [comment]
Tiene buena pinta!
@minigoBinpar
