### ISSUE TITLE
PRM VD: AL GENERAR PEDIDO RESPONDE USUARIO Y/O CONTRASEÑA INCORRECTOS

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#154]
![image](https://user-images.githubusercontent.com/22589031/27342669-116b0838-55e1-11e7-931e-e99787a9d3c3.png)
Usuario PRM: mcastroventadirecta@binpar.com
Al clicar en GENERAR PEDIDO no se conecta con el CRM.
@CristianBinpar @minigoBinpar @Al3xBinpar

**Comment by Al3xBinpar** [comment]
Backup mal reestablecido

**Comment by MACEMP** [comment]
Funciona correctamente.
Acabo de generar un pedido desde PRM y me llevó a PRM sin problemas
@Al3xBinpar @minigoBinpar
