### ISSUE TITLE
PRM VD: INCORPORAR CAMPO ESPECIALIDAD A PANTALLA CONTACTOS Y EXCEL DESCARGABLE

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#155]
Se solicita incorporar el campo especialidad a CONTACTOS tanto pantalla como Excel
El campo Especialidad ya aparece en el INFORME VENTA DIRECTA.
@CristianBinpar @minigoBinpar

**Comment by minigoBinpar** [comment]
Listo
![image](https://user-images.githubusercontent.com/20515815/27422055-216aeb48-572d-11e7-8895-f42fdd7306bb.png)
