### ISSUE TITLE
PRM VD ADMINSTRADOR: ¿qué compara el boton COMPARAR?

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#156]
![image](https://user-images.githubusercontent.com/22589031/27343165-60b87302-55e2-11e7-8e2e-2e6c27a1dd47.png)
No responde, de ahí la pregunta.
@CristianBinpar @minigoBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 
Tenemos que redefinir que verá el adminVD.

**Comment by minigoBinpar** [comment]
@Al3xBinpar 

El Admin verá los mismos graficos y resultados, solo que sera el sumatorio de los contactos de sus vendedores

**Comment by MACEMP** [comment]
¿Será la misma comparativa que en Universidad?
@minigoBinpar
