### ISSUE TITLE
PRM VD: APARECE ASIGNACIÓN ZONA - ERROR MAIL NO REGISTRADO EN BBDD PANA

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#157]
![image](https://user-images.githubusercontent.com/22589031/27379921-762e4ce8-567d-11e7-825e-0725414506a7.png)
![image](https://user-images.githubusercontent.com/22589031/27379945-8c446058-567d-11e7-9378-4afdcb2c29f7.png)
El error de creación de usuario está relacionado con el no registro del mail en la bbdd de PANA.
No se puede confirmar que envíe correctamente el mail de invitación al usuario.
@CristianBinpar @minigoBinpar @Al3xBinpar

**Comment by Al3xBinpar** [comment]
@minigoBinpar revisando las conectionString de los métodos importCRM e importLead quedaría arreglada esta incidencia

**Comment by minigoBinpar** [comment]
@MACEMP 

Esto es debido a que primero hay que dar de alta los usuarios en el CRM. 

Te pasamos una lista de los mismos en breves

**Comment by MACEMP** [comment]
Perfecto!
Gracias. Seguiré con las pruebas cuando me la enviéis.
@minigoBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 
Hemos tenido un problema con la base de datos y tenidoque borrar y volver a crear los VD y el AdminVD.

Aquí te paso el admin VD:
administradorventadirecta@binpar.com
12341234

Puedes hacer pruebas creando nuevos VD con este email:
macastroVD@binpar.com

**Comment by MACEMP** [comment]
Creado nuevo usuario macastroVD@binpar.com desde el usuario Administrador SIN PROBLEMAS
Utilizaré estos 2 usuarios para realizar los test
@minigoBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 
Great :)
