### ISSUE TITLE
PRM UNI: ERROR AL CREAR ADOPCION COMPARTIDA 

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#159]
![image](https://user-images.githubusercontent.com/22589031/27423586-7763562a-5732-11e7-96aa-7b9e58a87c72.png)

Tanto Noemí como Alex al  intentar crear adopciones compartidas, obtienen un mensaje de ERROR AL ENVIAR CORREO
Esto no sucede cuando la ADOPCIÓN no es compartida.
@CristianBinpar @minigoBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 

Creo que ya funciona. Dime si os responde bien:
![image](https://user-images.githubusercontent.com/20515815/27583696-7ef81860-5b35-11e7-8998-950797861781.png)
