### ISSUE TITLE
INFORME ADOPCIONES: NO APARECE AÑO ACADEMICO 2017-2018 EN FILTRO

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#16]
![image](https://cloud.githubusercontent.com/assets/22589031/20638322/2ea48dc8-b3a4-11e6-909e-7936b2cdce7a.png)
No aparece el año académico 2017-2018. Pronto empezarán a incluir adopciones para el próximo curso y no se puede seleccionar. 
@CristianBinpar

**Comment by minigoBinpar** [comment]
Listo. Ahora subo versión
![image](https://cloud.githubusercontent.com/assets/20515815/20749042/f8a223ac-b6f0-11e6-8275-87e9967b9808.png)
