### ISSUE TITLE
PRM UNI: NO APARECE LA OPCIÓN COMPARTIDA EN CONFIRMAR ADOPCIÓN

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#160]
![image](https://user-images.githubusercontent.com/22589031/27424693-3c80c02a-5736-11e7-95fb-965b7a7dc5e2.png)

La opción COMPARTIDA no aparece cuando un promotor quiere confirmar una adopción. Esto les obliga a crear una nueva adopción desde 0 e indicar COMPARTIDA.
@CristianBinpar @minigoBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 

Ciertamente, se trataría de una nueva funcionalidad.

**Comment by MACEMP** [comment]
¿¿¿¿¿Nueva funcionalidad????Las adopciones sean nuevas o confirmadas pueden ser compartidas. Si no se marca compartida, los datos se multiplican x n profesores, desvirtuando totalmente los números.
@minigoBinpar

**Comment by franciscorrr** [comment]
Pendiente de que se despliegue en los entornos.

Al parecer el selector siempre ha estado ahí, pero debido a que la ventana era demasiado pequeña se quedaba (en según que circunstancias) oculto y no se mostraba. Hemos ampliado la altura de esa ventana "popup" para que siempre aparezca.

![image](https://user-images.githubusercontent.com/30254281/28456858-1ad520ee-6e04-11e7-9068-290a252fdd1a.png)

**Comment by MACEMP** [comment]
Gracias Fran.
¡Qué curioso!
@franciscorrr

**Comment by franciscorrr** [comment]
Repasando he visto que además de que no se estaba mostrando correctamente (estaba oculto dentro de la ventana) el checkbox no funcionaba bien, no guardaba el estado al pulsar guardar.

Esto pasaba tanto al realizar un "Reconfirmar" como al editar este checkbox en "Ver adopción". Ahora si que debería de funcionar OK en ambos casos.

**Comment by MACEMP** [comment]
https://prm.medicapanamericana.com/Contacts/ShowContact@F9208DB0-9D8B-4998-8949-5B7470313BD3 
Aparece el checkbox COMPARTIDA y aparece como NUEVA Y COMPARTIDA, pero en el mensaje no aparece COMPARTIDA
![image](https://user-images.githubusercontent.com/22589031/28518521-72fd39c6-7068-11e7-8d74-44eb262dfa39.png)
@franciscorrr @minigoBinpar

**Comment by franciscorrr** [comment]
Hemos añadido campo ADOPCIONCOMPARTIDA al correo que se envía cuando se reconfirma una adopción, pendiente de despliegue
