### ISSUE TITLE
PRM UNI: AL RECONFIRMAR UNA ADOPCION BORRA EL CURSO

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#161]
![image](https://user-images.githubusercontent.com/22589031/27441489-025a8060-576e-11e7-9f4c-9708a09af0a6.png)

Hemos detectado que hay bastantes adopciones sin número de Curso.
Los 2 promotores confirman que introducen el dato, pero luego no queda reflejado en el PRM.

Gracias por revisarlo
@CristianBinpar @minigoBinpar

**Comment by franciscorrr** [comment]
No he conseguido reproducir este problema tal cual se describe, lo que sí que pasaba es que no dejaba reconfirmar cuando el curso era distinto de 1, daba un error y no dejaba guardar.

Eso ya está solucionado (a falta de desplegar en los entornos) pero habría que comprobar si se sigue reproduciendo el problema que se describe.
