### ISSUE TITLE
PRM UNI: NO GRABA LAS VENTAS AL RECONFIRMAR ADOPCIONES

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#162]
Mensaje de Alex Nieto

_está claro es que el PRM no guarda las ventas cuando reconfirmas adopciones.
Ayer perdí bastante tiempo metiéndolas y en el Excel no aparecen._

Una de las tareas de los promotores es meter las ventas para cotejar con la previsión que ellos han realizado. Si no quedan grabadas de nada sirve el tiempo empleado.
@CristianBinpar @minigoBinpar

**Comment by franciscorrr** [comment]
Había un fallo que impedía guardar el número de ventas reales, ahora ya los debe de guardar. 

Cuando esté desplegado en los entornos os avisamos.

**Comment by MACEMP** [comment]
¡Gracias!
¿Está ya en Producción?
@franciscorrr
