### ISSUE TITLE
PRM VD: Vuelta al PRM tras confirmación

### ISSUE THREAD

**Issue by Al3xBinpar** [BinPar/PRM#163]

**Comment by Al3xBinpar** [comment]
Hecho

**Comment by minigoBinpar** [comment]
@Al3xBinpar 
![image](https://user-images.githubusercontent.com/20515815/27541399-160e50a0-5a84-11e7-9966-35ac5b1a53d6.png)

**Comment by Al3xBinpar** [comment]
Done!
