### ISSUE TITLE
PRM VD: LOS DATOS DE PANTALLA INICIO NO CORRESPONDEN CON EL HISTÓRICO

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#167]
Usuario: macastrovd@binpar.com
Contacto: mariafercas@gmx.com
![image](https://user-images.githubusercontent.com/22589031/27482567-4d842514-5822-11e7-9844-58598f18f506.png)

Este contacto tiene 4 oportunidades y en la pantalla de inicio solo aparecen 3

![image](https://user-images.githubusercontent.com/22589031/27482626-787b0b16-5822-11e7-8ac3-ed963129a627.png)
@CristianBinpar @minigoBinpar @Al3xBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 
Se trataba de un error derivado del proceso de reasignación de contactos entre distintos VD por parte del AdminVD

Subo versión a beta y si pudieras hacer un par de testings, iríamos sobre seguro
