### ISSUE TITLE
PRM UNI: APARECE OPCION MATERIALES COMPLEMENTARIOS EN UN MATERIAL QUE NO DISPONE DE MC

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#168]
Aparece la opción de activar materiales web, y no dispone de ellos
MATERIAL : BEST-TAYLOR  ebook
 
![image](https://user-images.githubusercontent.com/22589031/27532725-79a40e7a-5a61-11e7-95b5-31049b5d357e.png)
@CristianBinpar @minigoBinpar

**Comment by franciscorrr** [comment]
Para el libro BEST-TAYLOR:Bas. Fisiológicas 14Ed.-e (EAN: 9789500604604) hay dos materiales complementarios en la tabla [Panamericana].[dbo].[ComplementaryMaterial]. 
![image](https://user-images.githubusercontent.com/30254281/28451879-34f95c9c-6df0-11e7-9e47-6f7cb8699b71.png)

**Comment by MACEMP** [comment]
Gracias Fran.
Los materiales complementarios que indicas NO SON lo que nosotros Denominamos materiales complementarios (vídeos, preguntas autoevaluación, presentaciones, imágenes...). 
En la web http://www.medicapanamericana.com/Libros/Libro/4094/Best-Taylor-Bases-Fisiologicas-de-la-Practica-Medica.html tambien aparece sin acceso a MatCom . Cuando un libro tiene MatComp hay un apartado en la ficha que lo indica.
![image](https://user-images.githubusercontent.com/22589031/28451999-de7190f0-6df0-11e7-9214-44808c73f484.png)
@franciscorrr

**Comment by franciscorrr** [comment]
@MACEMP En realidad sí que aparecen Materiales Complementarios en la página web
http://www.medicapanamericana.com/Libros/Libro/4509/eBook-Best-Taylor-Bases-Fisiologicas-de-la-Practica-Medica.html

La captura que se indica al principio de la incidencia hace referencia al libro electrónico (4509) que sí que tiene materiales complementarios (al menos así se ve en el link que hay adjunto).

![image](https://user-images.githubusercontent.com/30254281/28454013-e70f73e0-6df9-11e7-9ff5-8b83e1e17bbf.png)

**Comment by MACEMP** [comment]
Si, aparece materiales complementarios, pero realmente es un código para activar el ebook, no un material tipo figuras, imágenes, vídeos que es lo que nosotros llamamos "material complementario".
El problema ya está resuelto, hay un "material complementario" atípico por eso aparece como disponible en el PRM.
Se puede cerrar el issue.
@franciscorrr
