### ISSUE TITLE
ENVIAR EN PROMOCIÓN: SE HA PRODUCIDO UNA SITUACIÓN DE EXCEPCION

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#17]
![image](https://cloud.githubusercontent.com/assets/22589031/20802111/3fe0a2d4-b7eb-11e6-9c7f-e46652b9cf5d.png)

Contacto: Nicanor Morales
Material: Cael (papel)
Tanto Noemí como yo hemos intentado ENVIAR EN PROMOCIÓN y la respuesta es la misma.
POR ERROR ABRÍ EL ISSUE EN PPD  :-)
@CristianBinpar

**Comment by minigoBinpar** [comment]
Listo
![image](https://cloud.githubusercontent.com/assets/20515815/21140420/3ba70d42-c138-11e6-9ef5-7b7b3a61439a.png)

En breves subo versión
