### ISSUE TITLE
PRM VD: NO FUNCIONA BOTON CONFIRMAR VENTA

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#171]
![image](https://user-images.githubusercontent.com/22589031/27546131-2f209b62-5a92-11e7-98f0-0f77dd94327d.png)

Al clicar en CONFIRMAR VENTA aparece el círculo en movimiento indicando que está procesando, pero no responde que se ha generado el mail ni me lleva de vuelta al PRM VD
USUARIO; macastroVD
@CristianBinpar @minigoBinpar @Al3xBinpar

**Comment by Al3xBinpar** [comment]
SMTP parado
