### ISSUE TITLE
PRM VD: ERROR REFERENCIA A OBJETO NO ESTABLECIDA

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#172]
![image](https://user-images.githubusercontent.com/22589031/27546354-d3c7c780-5a92-11e7-9949-8a85e6df8950.png)
Al crear promociones con algunos materiales aparece ERROR CREANDO NUEVA PROMOCIÓN
@CristianBinpar @minigoBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 
¿Podrías decirme que materiales?

**Comment by MACEMP** [comment]
Como apenas si se ve nada la línea del material, no te puedo decir. 
Era un libro acreditado. Acababa en -AC 
@minigoBinpar
