### ISSUE TITLE
Configuración de la cuenta con José Rico

### ISSUE THREAD

**Issue by Al3xBinpar** [BinPar/PRM#174]

**Comment by CristianBinpar** [comment]
@MACEMP , ¿sabemos algo de la creación de esta cuenta?

Gracias!!

**Comment by MACEMP** [comment]
Hablé ayer Jose para que se pusiese en contacto con Alex y solucionar este problema- 
@CristianBinpar

**Comment by CristianBinpar** [comment]
En principio está cerrada, verificamos y cerramos el issue @minigoBinpar

**Comment by MACEMP** [comment]
He realizado pedidos y los recibo correctamente.
@CristianBinpar @minigoBinpar
