### ISSUE TITLE
Tabla de oportunidades

### ISSUE THREAD

**Issue by Al3xBinpar** [BinPar/PRM#175]
![image](https://user-images.githubusercontent.com/25204866/27624668-02e29e8c-5be2-11e7-80af-87fc8fa15695.png)
 Cuando se genera una nueva oportunidad y se recarga la página en realidad está ordenando siempre por fecha estado, en vez de coger la active

**Comment by minigoBinpar** [comment]
![image](https://user-images.githubusercontent.com/20515815/27626525-ae8c6ef6-5be8-11e7-80d2-00046a689a0e.png)
