### ISSUE TITLE
PRM VD : EUROS TOTALES EN JUEGO ¿A QUÉ SE REFIERE?

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#177]
![image](https://user-images.githubusercontent.com/22589031/27632388-d988d1ea-5bfb-11e7-876f-4cf46fdc0a04.png)

El importe en euros debiera tener este formato ##.###,## €
@CristianBinpar @minigoBinpar @Al3xBinpar

**Comment by Al3xBinpar** [comment]
@MACEMP se refiere a euros potenciales que se han ganado o se pueden llegar a ganar con todas las oportunidades que hay abiertas.

**Comment by MACEMP** [comment]
Gracias.
El importe de GANANCIAS POTENCIALES ¿es la suma de los importes de cada oportunidad en la fase en la que se encuentra o es la suma de los importes de cada oportunidad si llega a concretarse?
Al juzgar por el importe que aparece ahora, creo que se trata de la suma de importes totales no del importe de fase-oportunidad.
@minigoBinpar @Al3xBinpar

**Comment by MACEMP** [comment]
Por cierto, es mucho más acertada la etiqueta GANANCIAS POTENCIALES que EUROS EN JUEGO. GRACIAS.
@minigoBinpar @Al3xBinpar

**Comment by Al3xBinpar** [comment]
@MACEMP efectivamente es el total de lo que ganarías si la oportunida llegara a concretarse.

**Comment by MACEMP** [comment]
¡Entendido! Gracias.
@Al3xBinpar @minigoBinpar
