### ISSUE TITLE
PRM VD: MODIFICAR 2 COLORES GRÁFICO DASHBOARD

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#178]
![image](https://user-images.githubusercontent.com/22589031/27632582-5a8a0e76-5bfc-11e7-9f17-3a5e9aa0066d.png)
Para mantener la coherencia, modificar el color de OPORTUNIDAD PERDIDA en el gráfico de GRIS a ROJO.
Modificar el color de PRIMER CONTACTO de ROJO a GRIS.
En el indicador superior el ROJO indica OPORTUNIDAD PERDIDA.
@CristianBinpar @minigoBinpar @Al3xBinpar

**Comment by Al3xBinpar** [comment]
Hecho
