### ISSUE TITLE
PRM UNI: APLICAR CON CARACTER RETROACTIVO LA SOLUCIÓN A  DOCENTES CON 2 MAILS NO APARECEN COMO REGISTRADOS EN LA WEB

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#184]
Derivada de  #52
@CristianBinpar @minigoBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 
Listo. Ahora el sistema busca en la lista de emails (no en el principal) y si alguno de los mismos coincide con los registros de Pana, entendemos que el user está registrado en la web.

**Comment by MACEMP** [comment]
Gracias!
¿Cuando crees que podrás subir versión?
@minigoBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 
Si saber 100% seguro, diría que el lunes. Pero te confirmo por email

**Comment by MACEMP** [comment]
Gracias!
@minigoBinpar
