### ISSUE TITLE
PRM VD: TAMAÑO GRÁFICO EN DASHBOARD

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#188]
![image](https://user-images.githubusercontent.com/22589031/27681825-b9965ae0-5cc0-11e7-8380-8e8d788ac2f5.png)
El tamaño del gráfico circular es demasiado grande. Lo ideal sería que cupiesen en una pantalla tanto la parte de arriba con los 3 indicadores y el gráfico circular con los 6 marcadores.
Una posible solución es disminuir el tamaño del gráfico y pasar las leyendas a un lateral en vertical en lugar de horizontal (es una sugerencia)
@CristianBinpar @minigoBinpar @Al3xBinpar

**Comment by Al3xBinpar** [comment]
@MACEMP lo hemos cambiado, te convence más así?

**Comment by MACEMP** [comment]
Si, mejor. De un vistazo se ve todo. Gracias.
@Al3xBinpar @minigoBinpar
