### ISSUE TITLE
CONTACTOS: NO APARECEN EN EL FILTRO LAS UNIVERSIDADES CON DENOMINACIÓN UNIVERSITAT

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#19]
![image](https://cloud.githubusercontent.com/assets/22589031/21106543/c7a9505c-c08e-11e6-9cbc-06615351de8c.png)
En el listado del FILTRO la última universidad que aparece es Universidad Fernando de Pessoa, no aparecen ninguna de Cataluña ya que se escriben UNIVERSITAT.
@CristianBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 
Listo. Próxima subida
![image](https://cloud.githubusercontent.com/assets/20515815/21385777/2f17c4de-c770-11e6-852a-f3c31d457c83.png)
