### ISSUE TITLE
PRM UNI: ELIMINAR DE BBDD CONTACTOS BINPAR

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#194]
En la BBDD en producción aparecen bastantes líneas con acciones de contactos tipo @binpar.com o Miguel Castro Binpar Binpar.
Sería conveniente eliminarlos para que en los informes no aparezcan datos ficticios.
@CristianBinpar @minigoBinpar

**Comment by franciscorrr** [comment]
Se han eliminado las lineas de acciones, adopciones y promociones relacionadas con los contactos de prueba de Binpar. En principio ya no debería de quedar ninguno.
