### ISSUE TITLE
PRM VD: error en el servidor remoto al crear pedido

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#197]
![image](https://user-images.githubusercontent.com/22589031/27796891-e17a6efe-600b-11e7-8333-37e1082e3864.png)
Al tratar de generar un pedido obtengo esa respuesta.
@CristianBinpar  @minigoBinpar @Al3xBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 
debería funcionar ya

**Comment by MACEMP** [comment]
![image](https://user-images.githubusercontent.com/22589031/28065962-39d357d4-663b-11e7-8323-21b5975613b4.png)
Ya permite generar el pedido, pero se queda parado cuando indico CONFIRMAR VENTA.
Antes lo que ocurría es que, una vez confirmado, te llevaba nuevamente al PRM para seguir generando oportunidades.

![image](https://user-images.githubusercontent.com/22589031/28066001-733a2548-663b-11e7-941b-04f0a5e66434.png)
A pesar de clicar repetidas veces en CONFIRMAR no generó la venta.
Comprobado en el PRM que la venta no aparece realizada.
![image](https://user-images.githubusercontent.com/22589031/28066044-9cbd4e18-663b-11e7-98f5-74734ef140fa.png)

Por otra parte en la imagen superior, recuadro en rojo los campos que siguen sin pasar al pedido, a pesar de estar en el PRM.
También indico que en el campo UNIVERSIDAD es texto libre. Lo lógico sería que apareciesen las UNIS del PRM, de otro modo será imposible realizar cualquier filtro porque habrá múltiples denominaciones para Universidad.

Siento reabrir el caso :-(
@minigoBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 
Ya debería dar resultado :)

**Comment by MACEMP** [comment]
EUREKA!!! FUNCIONA!!!
He tramitado el pedido sin problema, llevándome del PRM al CRM y del CRM al PRM con rapidez.
También he recibido el pedido por mail ¡¡¡bien!!!
Solo veo un problemilla: no aparece "Tipo de pago" (marcado en amarillo). Indiqué PROFORMA, tal y como me indicaste.
![image](https://user-images.githubusercontent.com/22589031/28136925-a14998fe-674b-11e7-9ffc-6f49f086ac51.png)

¡¡Gracias!!!
@minigoBinpar
