### ISSUE TITLE
PRM VD: NO APARECE PAIS EN INFORME EXCEL CONTACTOS

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#198]
![image](https://user-images.githubusercontent.com/22589031/27817114-ba7e00de-608f-11e7-951a-6f4420747882.png)
@CristianBinpar @minigoBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 

Listo

[Informe_Contactos_1499682298187.zip](https://github.com/BinPar/PRM/files/1135162/Informe_Contactos_1499682298187.zip)

**Comment by MACEMP** [comment]
¡Perfecto! gracias.
@minigoBinpar
