### ISSUE TITLE
PRM VD: MODIFICAR FILTROS INFORME CONTACTOS

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#199]
![image](https://user-images.githubusercontent.com/22589031/27817162-f7bc0f2c-608f-11e7-8d34-6e9d7008adaa.png)
Modificar UNIVERSIDAD por HOSPITAL / CENTRO
Modificar ASIGNATURA por ESPECIALIDAD
@CristianBinpar @minigoBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 
![image](https://user-images.githubusercontent.com/20515815/28012573-7c7d4e12-6566-11e7-9b4f-f1968257eb79.png)

![image](https://user-images.githubusercontent.com/20515815/28012600-97fe1cde-6566-11e7-9404-e93e12cea211.png)
