### ISSUE TITLE
SOLICITUD MEXICO: INCLUIR COMO DESTINATARIO DEL MAIL CONCESIÓN ACCESO EBOOK AL USUARIO

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#20]
Desde México solicitan que el usuario que concede el acceso al ebook a un docente, sea también destinatario de ese correo.
¿Resultaría muy costoso?
@CristianBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 

Sería conveniente probarlo en algún caso real, pero en principio se envía un segundo email con la misma información al promotor
