### ISSUE TITLE
PRM VD: MODIFICAR TABLA OPORTUNIDADES CONCRETADAS 

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#200]
![image](https://user-images.githubusercontent.com/22589031/27817358-f0aa4d60-6090-11e7-94aa-7216e0b40fc5.png)
Solo han de aparecer los campos:
MATERIAL
FECHA INICIO OPORTUNIDAD
FECHA FIN OPORTUNIDAD
IMPORTE €€€
COMERCIAL VD

Aparecen los datos de las adopciones de universidad.
@minigoBinpar @CristianBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 
![image](https://user-images.githubusercontent.com/20515815/28012330-b67d53f6-6565-11e7-88fe-cd98a97d0dce.png)


Listo :) subo en breves

**Comment by MACEMP** [comment]
Falta el comercial VD ;-) 
Cuando se trata del Administrador es interesante que al acceder a un contacto sepa qué VD cerró la oportunidad o si hubo cambio de VD.
También falta la fecha de inicio de la oportunidad.
@minigoBinpar
