### ISSUE TITLE
PRM UNI COLOMBIA: ERROR EN ENVÍO MAIL DE ACCESO EBOOK

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#202]
Desde Colombia reportan este error:
 al conceder el acceso a un ebook al contacto namega@hotmail.com , recibe un mensaje de NOTIFICACIÓN NO RECEPCIÓN DE MENSAJE.
Lo curioso es que indica que **el remitente está en una lista de bloqueo**.

**Unfortunately, messages from 193.70.45.164 weren't sent. Please contact your Internet service provider since part of their network is on our block list. You can also refer your provider to http://mail.live.com/mail/tr**

MENSAJE RECIBIDO POR COLOMBIA
De: postmaster@ns3062780 [mailto:postmaster@ns3062780] Enviado el: miércoles, 05 de julio de 2017 2:21 p. m.
Asunto: Notificación de estado de entrega (Error)
Algunos de los destinatarios no recibieron su mensaje.
      Asunto:	No se puede localizar a los destinatarios siguientes:
      namega@hotmail.com en 05/07/2017 2:20 p. m.
            ns3062780: 550 SC-001 (COL004-MC1F22) 
Unfortunately, messages from 193.70.45.164 weren't sent. Please contact your Internet service provider since part of their network **is on our block list**. You can also refer your provider to http://mail.live.com/mail/tr

Al igual que con España  ayer, el envío de mails confirmando el acceso a ebooks es prioritario.

Muchas gracias.
@CristianBinpar @minigoBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 
Creo que queda solucionado con todo el tema de envío de mensajes

**Comment by MACEMP** [comment]
Duda ¿tienen que volver a generar la promoción?
@minigoBinpar
