### ISSUE TITLE
PRM UNI COLOMBIA: Solicitan incluir en profesión QUÍMICO/A y VETERINARIO/A

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#203]
Desde Colombia solicitan la inclusión de 2 nuevas profesiones:
- Químico/a
- Veterinario/a
la petición es lógica ya que promocionamos libros de estas dos especialidades y que no aparecen en el desplegable de Profesiones. 
Actualmente se utiliza OTRAS, que aporta poca/ninguna información.
@CristianBinpar @minigoBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 
Listo :)

**Comment by MACEMP** [comment]
Gracias! Ahora solo falta lo de la provincia ;-) (qué cansina soy)
¡feliz semana!
@minigoBinpar
