### ISSUE TITLE
PRM BETA: No crea acciones en el histórico

### ISSUE THREAD

**Issue by minigoBinpar** [BinPar/PRM#206]

**Comment by MACEMP** [comment]
http://betaprm.medicapanamericana.test/Contacts/ShowContact@f78da26d-1b38-4955-93c9-bf83d7c21347 
he realizado acciones con este usuario y no queda reflejado en el histórico
@minigoBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 
Listo :)
![image](https://user-images.githubusercontent.com/20515815/28117396-9012ff78-670d-11e7-81f3-f4277b290fc3.png)

**Comment by MACEMP** [comment]
perfecto! A mi también me funciona.
Gracias :-)
@minigoBinpar
