### ISSUE TITLE
PRM UNI MEXICO: INCLUIR 2 NUEVAS PROVINCIAS

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#207]
Desde México solicitan 
- modificación del nombre de una provincia
- inclusión de una nueva provincia. Creo que no se puede utilizar el nombre de la ciudad LEON de Nicaragua como provincia de MÉXICO ¿es así?

![image](https://user-images.githubusercontent.com/22589031/28151047-98982890-6798-11e7-9d9d-f663d8e1bdd5.png)

Sería conveniente repensar la posibilidad de que el administrador pudiese controlar este tipo de situaciones creando un editor de localidades/provincias/país/zona

@CristianBinpar @minigoBinpar

**Comment by MACEMP** [comment]
Desde Mexico puntualizan:
_Se me pasó comentarte, que León aplica para los dos países.
Existe tanto en México como en Nicaragua._
En resumen:
Modificar denominación provincia México por Ciudad de México
Crear Provincia León en México 
@minigoBinpar

**Comment by franciscorrr** [comment]
@MACEMP Ya se han aplicado los cambios

**Comment by MACEMP** [comment]
Gracias!
@franciscorrr
