### ISSUE TITLE
PRM VD: EL TAMAÑO DEL GRÁFICO CIRCULAR ES EXCESIVO E IMPIDE VER BIEN LA COMPARATIVA

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#209]
![image](https://user-images.githubusercontent.com/22589031/28271918-455c3a2a-6b0a-11e7-8f31-c4738a57b412.png)

Sugiero que la comparativa se muestre justo debajo de los KPI para saber a qué se refiere la comparativa y el gráfico tarta se reduzca de tamaño.
@CristianBinpar @minigoBinpar

**Comment by CristianBinpar** [comment]
Estoy de acuerdo

**Comment by minigoBinpar** [comment]
@MACEMP 
He reducido el tamaño del gráfico (dejo en tu mano si consideras que se reduzca aún más):
![image](https://user-images.githubusercontent.com/20515815/28303359-0d292fd0-6b93-11e7-80fc-147240ff9225.png)

También he modificado la situación del gráfico de comparativas para que se perciba la respeusta del sistema por parte del usuario al hacer click en "comparar".

![image](https://user-images.githubusercontent.com/20515815/28303668-90ee7be4-6b94-11e7-90e8-8703bc930f18.png)

**Comment by MACEMP** [comment]
Lo haría un poco más pequeño . Gracias
@minigoBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 
Anotado
