### ISSUE TITLE
EXCEL CONTACTOS: NO DESGARGA EL ARCHIVO

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#21]
![image](https://cloud.githubusercontent.com/assets/22589031/21253161/9fb8460e-c35c-11e6-968b-455608d3041a.png)
Al clicar en  el botón EXPORTAR A EXCEL aparece el círculo de actividad, pero no descarga ningún archivo .
@CristianBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 
![image](https://cloud.githubusercontent.com/assets/20515815/21386897/6400d122-c775-11e6-9a3a-7efba9aa9de5.png)

¿Pudiera tratarse de algún error puntual? Subo versión y comprobamos en beta y producción, pero desde aquí todo parece correcto

**Comment by MACEMP** [comment]
Funciona correctamente
@minigoBinpar
