### ISSUE TITLE
PRM VD: GENERAR MENSAJE AL NUEVO USUARIO CUANDO EL ADMINISTRADOR CREA UN NUEVO USUARIO VENDEDOR

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#210]
@CristianBinpar @minigoBinpar

**Comment by minigoBinpar** [comment]
Listo
![image](https://user-images.githubusercontent.com/20515815/28304594-9494157a-6b98-11e7-96cb-a3d5b1bc6b8c.png)

**Comment by MACEMP** [comment]
¡Perfecto!
Solo hay que separar "superfil" = su perfil
![image](https://user-images.githubusercontent.com/22589031/28305783-4eb408d0-6b9d-11e7-8b4a-f981069fc09c.png)
@minigoBinpar
