### ISSUE TITLE
PRM VD BETA: REVISIÓN PEDIDO GENERADO CON DATOS DEL CONTACTO - ERROR EN IMPORTE - FALTA DE CAMPOS EN PEDIDO

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#212]
![image](https://user-images.githubusercontent.com/22589031/28304254-0b7d8902-6b97-11e7-9dbe-5f65616cffe5.png)
Al comparar los datos que proporciona el mail recibido tras la generación del pedido se detecta.
1. el importe que aparece en OPORTUNIDADES CONCRETADAS no coincide ni con el importe del pedido ni con el importe del PIPELINE en  OPORTUNIDADES del contacto
Pipeline: 1149,00
Pedido: 1149.00
OPORTUNIDADES CONCRETADAS: 114900.00
Por otra parte, en unos casos se utiliza "," y en otros "." para indicar los decimales
2. en el mail que genera el pedido aparece la línea "Hombre" sin indicar a qué campo pertenece
3. Sigue sin aparecer FORMA DE PAGO. Dato básico para poder generar el pedido en SAP
4. Siguen apareciendo campos como  ASIGNATURA... en OPORTUNIDADES CONCRETADAS. Hay un issue sobre este mismo asunto 
@CristianBinpar @minigoBinpar

**Comment by franciscorrr** [comment]
Solucionado a falta de desplegar.
![image](https://user-images.githubusercontent.com/30254281/28768208-1070ab70-75d7-11e7-938a-fbf8a8250e95.png)
![image](https://user-images.githubusercontent.com/30254281/28768273-45194dc8-75d7-11e7-936c-58ef24035470.png)
