### ISSUE TITLE
PRM VD BETA: CAMPOS IMPRESCINDIBLES QUE FALTAN EN EL MAIL DEL PEDIDO GENERADO

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#216]
![image](https://user-images.githubusercontent.com/22589031/28313759-5a07e182-6bb8-11e7-9760-28c48c064253.png)

Es esencial que aparezcan todos los campos, ya que con esos datos se genera el pedido en SAP

Hay un campo "TITULAR" correspondiente al apartado FORMA DE PAGO que no existe como campo y debiera de existir, ya que, con relativa frecuencia el TITULAR de los datos de pago, no es el mismo que el cliente que adquiere el curso.
@CristianBinpar @minigoBinpar @PabloBinpar

**Comment by PabloBinpar** [comment]
Hola Maria Angeles,

Los siguientes campos que menciono, no existen en el formulario. Necesito que me indiques de donde saldrían estos datos, si hay que incluirlos nuevos o no:
- Email Facturacion -> "FALTA PROVINCIA DE LA EMPRESA"
- Datos del pedido -> "INDICAR EN CUALQUIER FORMA DE PAGO EL TITULAR"
- CAMPOS QUE FALTAN -> Observaciones, numero de cuotas, importe cuotas

**Comment by MACEMP** [comment]
Hola Pablo,
PROVINCIA EMPRESA: no existe este campo, por lo que habría que crearlo. Si se trata de una dirección de facturación el dato PROVINCIA es obligatorio.
TITULAR: no existe este campo. Al solicitar los datos de pago, sea Tarjeta de crédito - Domiciliación bancaria - Transferencia , SE NECESITA el nombre del Titular

CAMPOS QUE FALTAN: estos campos ya existen en el pedido, pero no aparecen en el mail:
- Observaciones
- Número de cuotas 
- Importe cuotas = Precio final / nº cuotas (es me parece que no existe)

También hay que incluir los campos de DATOS DE VENTA:
CONVOCATORIA: (fecha)
INCLUYE LIBRO: SI/NO

@PabloBinpar

**Comment by MACEMP** [comment]
Muchas gracias por ir incorporando los campos. Estoy recibiendo nuevos pedidos y los voy revisando.
Ahora veo que solo falta:
- OBSERVACIONES Texto libre
- FORMA DE PAGO con los campos que trae cada FORMA DE PAGO. P.e. si es Tranferencia el titular y el número de cuenta. Si es tarjeta, titular,  nº tarjeta y caducidad, etc.
@PabloBinpar

**Comment by PabloBinpar** [comment]
Subido CRM con estos cambios a producción

**Comment by MACEMP** [comment]
Este es el comentario de la persona que gestiona los pedidos en SAP y recibirá el mail

"Lo veo completo, pero faltaría el campo de la forma de pago para meter la cuenta bancaria o bien la tarjeta y fecha de caducidad.
Es imprescindible un campo de observaciones para meter texto libre."

@PabloBinpar

**Comment by MACEMP** [comment]
Acabo de hacer un pedido.
No aparece el campo PROVINCIA (la he indicado)
![image](https://user-images.githubusercontent.com/22589031/28365828-5c20d1ae-6c8a-11e7-8908-f715371380c5.png)
NO aparece el texto que he incluido en  el campo OBSERVACIONES 
![image](https://user-images.githubusercontent.com/22589031/28365863-85eec2de-6c8a-11e7-85cd-cc4812cffe21.png)
NO aparece TIPO DE PAGO (más correcta sería la FORMA DE PAGO, pero es una corrección menor)
![image](https://user-images.githubusercontent.com/22589031/28365900-b639f044-6c8a-11e7-951b-c91b556f2e81.png)
@PabloBinpar @minigoBinpar

**Comment by MACEMP** [comment]
Nuevo pedido:
Aparece PROVINCIA, pero no aparecen OBSERVACIONES
![image](https://user-images.githubusercontent.com/22589031/28366237-22b34d1e-6c8c-11e7-8f66-b50fcc376df9.png)
Aparece FORMA DE PAGO, pero no los datos para poder cerrar el pago del pedido.  Comentario que ha realizado Marce Diaz, responsable de la carga de pedidos en SAP: "Lo veo completo, pero faltaría el campo de la forma de pago para meter la cuenta bancaria o bien la tarjeta y fecha de caducidad" 
"

![image](https://user-images.githubusercontent.com/22589031/28366273-488b3024-6c8c-11e7-9d6b-c20c758dfb89.png)
@PabloBinpar @minigoBinpar

**Comment by PabloBinpar** [comment]
Se han subido y corregido todos los cambios. Observaciones no lo cogía en ocasiones, por un parámetro que permitia recoger a veces el valor. Se ha resuelto este problema y se ha incluido los campos de cuenta y de tarjeta.

**Comment by MACEMP** [comment]
CASI PERFECTO
Solo falta el número de tarjeta.
![image](https://user-images.githubusercontent.com/22589031/28367174-1e314724-6c90-11e7-8088-c95f8b6c41cb.png)
Ahora haré uno con domiciliación para ver si trae el número de cuenta
@PabloBinpar @minigoBinpar

**Comment by MACEMP** [comment]
¡PERFECTO!
El número de cuenta ya lo pasa. Cuando me digáis vuelvo a probar con número de tarjeta
![image](https://user-images.githubusercontent.com/22589031/28367361-e45637b6-6c90-11e7-84cc-bf7f90dddc48.png)

El campo SUBESPECIALIDAD sigue sin mostrar desplegable :-(, por más crtl+shft+R que hago.
@PabloBinpar @minigoBinpar

**Comment by PabloBinpar** [comment]
El campo de tarjeta debe escribirse siempre con sólo números. A mi vuelta, si vería conveniente limitar estos campos la entrada a solo numeros. Los cambios están subidos justo antes de la ultima vez que probaste. No me dio tiempo a escribir.

**Comment by PabloBinpar** [comment]
Subespecialidad lo revisaré pero creo que no me va a dar tiempo hoy a revisarlo. Marcos lo podría revisar si no me da tiempo

**Comment by MACEMP** [comment]
![image](https://user-images.githubusercontent.com/22589031/28367584-c351464a-6c91-11e7-8498-1c7e45c22bf5.png)
Sigue sin aparecer la tarjeta.
Solo número ¿a qué te refieres? Solo utilizo números
@PabloBinpar @minigoBinpar

**Comment by MACEMP** [comment]
Es más importante dejar solucionado el campo TIPO DE PAGO que SUBESPECIALIDAD
@minigoBinpar @PabloBinpar

**Comment by PabloBinpar** [comment]
Revisa que no haya ningún espacio, que solo haya números. Solo hay una
razon para que no te coja ese campo ahora mismo y es que convierte el texto
a número y si contiene algo que no sea números lo introduce a 0.

*Pablo Leyton Lozano*

*Desarrollador*
*E* - pablo@binpar.com

[image: BinPar]

http://www.binpar.com
*T -  *91 391 06 02
*C - *Génova 10, 4º
28004 Madrid

*---- ADVERTENCIA ---- La información contenida en este correo electrónico,
y en su caso, cualquier fichero anexo al mismo, son de carácter privado y
confidencial siendo para uso exclusivo de su destinatario. Si usted no es
el destinatario correcto, el empleado o agente responsable de entregar el
mensaje al destinatario, o ha recibido esta comunicación por error, le
informamos que está totalmente prohibida cualquier divulgación,
distribución o reproducción de esta comunicación según la legislación
vigente y le rogamos que nos lo notifique inmediatamente, procediendo a su
destrucción sin continuar su lectura.*

*Le informamos que su dirección de correo electrónico, así como el resto de
los datos de carácter personal de la tarjeta de visita que nos facilite,
podrían ser objeto de tratamiento automatizado en nuestros ficheros, con la
finalidad de gestionar la agenda de contactos de BINPAR TEAM, S.L.*

*Vd. podrá en cualquier momento ejercer sus derechos de acceso,
rectificación, cancelación y oposición en los términos establecidos en la
Ley Orgánica 15/1999 mediante notificación escrita, aportando copia del
DNI, a la siguiente dirección: lopd@binpar.com <lopd@binpar.com>.*

2017-07-19 14:53 GMT+02:00 MACEMP <notifications@github.com>:

**Comment by MACEMP** [comment]
Pablo,
he introducido únicamente números, y en el campo sigue apareciendo 0.
No sé a qué se puede deber.

![image](https://user-images.githubusercontent.com/22589031/28367953-0dac95a4-6c93-11e7-8608-1bf11ce68c05.png)
@PabloBinpar @minigoBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 
Me lo das por bueno?

**Comment by MACEMP** [comment]
Al hacer un pedido, no está tomando el PRECIO
![image](https://user-images.githubusercontent.com/22589031/28407860-f6bf3830-6d35-11e7-8773-ef7d583ae3e7.png)
@minigoBinpar

**Comment by MACEMP** [comment]
![image](https://user-images.githubusercontent.com/22589031/28408291-4843d200-6d37-11e7-864f-11fae29b141c.png)
He marcado género MUJER e indica HOMBRE.
Salvo por ese error, el resto  toma bien los datos, incluso el número de la tarjeta :-)
Persisten 2 errores:
- No aparece el listado de Universidades que debiera de ser el mismo que en el PRM (hay un issue ya abierto)
- El desplegable SUBESPECIALIDAD no despliega nada (hay un issue ya abierto)
@minigoBinpar @CristianBinpar

**Comment by MACEMP** [comment]
Como hemos comentado ¡adelante con la subida!
![image](https://user-images.githubusercontent.com/22589031/28410649-9613621e-6d3e-11e7-8886-f4308c3200af.png)

@minigoBinpar @CristianBinpar
