### ISSUE TITLE
PRM VD BETA: ¿A DONDE SE ENVÍA EL XML QUE GENERA EL PEDIDO?

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#217]
El xml lo utilizan en Atención al cliente Formación para cargar los pedidos en SAP

@CristianBinpar @PabloBinpar @minigoBinpar

**Comment by PabloBinpar** [comment]
Hola Maria Angeles,

Los pedidos se alojan en la 24, en la carpeta "PedidosVentaDirecta\es" pero me comenta @CristianBinpar  que Jose Rico mueve los archivos a otro lado que personalmente desconozco. Espero que Jose Rico te pueda ayudar en esto también.

Un saludo.

**Comment by MACEMP** [comment]
Gracias Pablo.
Preguntaré a Jose Rico
@PabloBinpar

**Comment by MACEMP** [comment]
Jose Rico confirma que:
"Todo lo que se deja en los directorios que ya se definieron, se sincronizan mediante una aplicación que está continuamente corriendo ( algo parecido a Dropbox ) con los equipos de la gente de atención al cliente ( o de quien corresponda )
Lo único que hay que hacer es indicar qué carpetas son las que hay que sincronizar en cada uno de los equipos de los usuarios"
@CristianBinpar @PabloBinpar @minigoBinpar
