### ISSUE TITLE
SUSTITUIR DENOMINACIÓN CLINICA UNIVERSITARIA DE NAVARRA por CLINICA UNIVERSIDAD DE NAVARRA

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#22]
Se solicita  sustituir en BBDD la denominación de Clínica Universitaria de Navarra por Clínica Universidad de Navarra.
No puedo saber el número de contactos afectados por este cambio porque el Excel de Contactos no se descarga y resulta inviable consultar uno a uno todos los contactos de la Universidad de Navarra y comprobar si están adscritos a la Clínica o no.
¿Es posible? ¿Supone muchas horas?
@CristianBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 

Listo. No debería de haber colaterales

**Comment by MACEMP** [comment]
Perfecto! Gracias
@minigoBinpar
