### ISSUE TITLE
PRM VD BETA: AL MODIFICAR LOS DATOS DE UN CONTACTO DA ERROR

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#220]
![image](https://user-images.githubusercontent.com/22589031/28407664-3e463574-6d35-11e7-8303-c5446ee79375.png)

Error al sobreescribir los datos de un contacto y tratar de ir a la ficha del contacto para generar oportunidades
@CristianBinpar @minigoBinpar

**Comment by minigoBinpar** [comment]
Error producido durante subida proyecto
