### ISSUE TITLE
PRM UNI PRO: NO TENGO CREDENCIALES PARA ACCEDER A ROSA.BINPAR.COM\PRM

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#222]
Para poder realizar consultas a la bbdd del PRM necesito credenciales para el acceso a rosa.binpar.com
![image](https://user-images.githubusercontent.com/22589031/28450590-708bb65e-6de8-11e7-9046-d8efcd63bd7e.png)

@CristianBinpar @minigoBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 
Usuario actualizado (puedes emplear las credenciales que tenías de antes).

¿Necesitas usuario en PPD?

**Comment by MACEMP** [comment]
agh! las borré ;-( ¿Me las puedes enviar de nuevo?

Del PPD ya tengo nuevas credenciales, tanto para mi como para el usuario readonly

Gracias
@minigoBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 

Te envío un nuevo juego por email :)
