### ISSUE TITLE
PRM UNI PRO: NO SE DESPLIEGAN LOS MATERIALES AL REALIZAR UNA PROMOCION

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#223]
![image](https://user-images.githubusercontent.com/22589031/28463371-57daf312-6e20-11e7-9e1a-6111a041c45c.png)
@CristianBinpar @minigoBinpar @franciscorrr

**Comment by minigoBinpar** [comment]
@MACEMP 
Correcto. Los materiales es una de las partes que

**Comment by MACEMP** [comment]
Si es así, no se puede trabajar con el PRM, todavía.
@minigoBinpar

**Comment by MACEMP** [comment]
He intentado hacer una promoción y los materiales no se despliegan.
@minigoBinpar

**Comment by franciscorrr** [comment]
Ya se despliegan los materiales en la venta de nueva promoción, posiblemente se debiera a las cargas que se estuvieron realizando en PRO estos días.
![image](https://user-images.githubusercontent.com/30254281/28661327-9455fa36-72b6-11e7-8db1-54e360be352b.png)
