### ISSUE TITLE
PRM UNI PRO: NO SE VISUALIZA EL HISTORIAL

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#224]
![image](https://user-images.githubusercontent.com/22589031/28463469-d619328e-6e20-11e7-9d85-2deddc7645c9.png)
Al seleccionar cualquier Promoción ya creada, no se visualiza el historial
@CristianBinpar @minigoBinpar @franciscorrr

**Comment by franciscorrr** [comment]
@MACEMP Parece que fue un fallo temporal durante la subida de datos a PRO. Ahora funciona correctamente.
![image](https://user-images.githubusercontent.com/30254281/28661240-521f2322-72b6-11e7-9dff-7cbe548e848e.png)
