### ISSUE TITLE
PRM UNI PRO: ¿INFORME VENTA DIRECTA?

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#225]
![image](https://user-images.githubusercontent.com/22589031/28463920-303802fc-6e23-11e7-9a6e-5b88368384a2.png)
En la zona de INFORMES aparece un nuevo informe VENTA DIRECTA ¡qué raro!

Los informes responden correctamente.

@CristianBinpar @minigoBinpar @franciscorrr

**Comment by MACEMP** [comment]
Por cierto, la lupa solo se ha añadido a la pantalla de CONTACTO. El resto de INFORMES también merece tener la lupa en el lado izquierdo para facilitar el acceso a la ficha del contacto.
Gracias.
@minigoBinpar @franciscorrr

**Comment by franciscorrr** [comment]
Implementado. Pendiente de despliegue.

Se ha añadido la lupa al final de la pantalla en todos los informes, se ha mantenido también la lupa del final en aquellos informes que son más extensos horizontalmente.

El apartado de "Venta Directa" en "Informes" ya no aparece salvo que inicies sesión con un perfil de Venta Directa

![image](https://user-images.githubusercontent.com/30254281/28711504-1158ab4c-7388-11e7-87ef-bdb30e9918fe.png)
