### ISSUE TITLE
PRM UNI PRO: GESTION PERMISOS LLEVA AL DASHBOARD

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#226]
![image](https://user-images.githubusercontent.com/22589031/28464302-cf2512c8-6e24-11e7-9d05-bd265e5a6654.png)
Al clicar en el bloque ADMINISTRACIÓN - GESTION PERMISOS se abre el Dashboard, no el gestor de permisos.
@CristianBinpar @minigoBinpar @franciscorrr

**Comment by franciscorrr** [comment]
-- Todavía está pendiente de despliegue --

Hemos cambiado los permisos para que el usuario "macastro@medicapanamericana.es" pueda acceder a esta pantalla. También hemos cambiado pequeñas partes de la funcionalidad de esta pantalla para hacerla más intuitiva a la hora de trabajar con ella.

![image](https://user-images.githubusercontent.com/30254281/28515638-aa7efe3e-705e-11e7-82e7-60de3aa02fc5.png)

**Comment by MACEMP** [comment]
Muy buena aportación!
Gracias.
@franciscorrr
