### ISSUE TITLE
PRM UNI PRO: NO COINCIDEN DATOS KPI DASHBOARD_INFORME ADOPCIONES_INFORME ADOPCIONES VALORIZADAS

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#228]
![image](https://user-images.githubusercontent.com/22589031/28520005-25e1bec2-706e-11e7-9f45-915ec983aae7.png)

He comparado el número de adopciones que aparece en 3 lugares:
KPI DB = 1477
INF ADOPCIONES = 1404
INF ADOPCIONES VALORIZADAS = 1405 
El dato debiera de ser el mismo en los 3 casos.
Solo he utilizado el filtro FECHA : 5/9/2016 A 24/7/2017.
@CristianBinpar @minigoBinpar @franciscorrr

**Comment by MACEMP** [comment]
El número de adopciones ya coincide en los INFORMES, pero sigue sin coincidir en el DB

DB: 1484 (con la selección de fechas 5/9/2016 a 26/7/2017)
INFORMES: 1408
@minigoBinpar @franciscorrr

**Comment by franciscorrr** [comment]
Hemos hecho unos cambios (pendientes de despliegue) para ajustar los datos que se muestran en los informes y las exportaciones, ahora los datos de Adopciones - Adopciones valoradas son iguales, también en sus informes.

Falta la diferencia que hay con la pantalla del dashboard, que necesita unos cambios más profundos en el código y que afectan también a otras incidencias ( #234). 

Cierro esta tarea y lo que queda del dashboard lo continuamos en la #234

**Comment by MACEMP** [comment]
ok!
