### ISSUE TITLE
PRM UNI PRO: ELIMINAR DE BBDD LAS ACCIONES DE LOS CONTACTOS macastro@medicapanamericana.es consultor.macastro@medicapanamericana.es

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#229]
Para evitar falseamiento de datos convendría eliminar de la bbdd las acciones realizadas por los contactos 
macastro@medicapanamericana.es
consultor.macastro@medicapanamericana.es
@CristianBinpar @minigoBinpar @franciscorrr

**Comment by franciscorrr** [comment]
Cambios aplicados al entorno de PRO, se han eliminado todas las acciones realizadas por los usuarios macastro@medicapanamericana.es y consultor.macastro@medicapanamericana.es.
