### ISSUE TITLE
NUEVA PROMOCIÓN: NO PERMITE SELECCIONAR FECHAS 

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#23]
NO funciona el selector de fechas. Unicamente toma la fecha actual. Mensaje enviado por Noemí
Es importante solucionar esta incidencia ya que no refleja fielmente cuando se realizan las promociones.

Pruebas realizadas:

Le he dado al aspa y he escrito la fecha 13/12/2016 le dí a enter y no hace nada así que le doy a Crear. Haciéndolo así, la fecha que finalmente aparece en la promoción es la de hoy 16/12/2016

Le he dado a las flechitas pequeñas de arriba y abajo hasta colocar la fecha 13/12/2016 le dí al enter y no hace nada. Le doy a Crear y de nuevo en la ficha de la profesora la fecha que aparece para esta promoción es la de hoy 16/12/2016

Por último, pincho en la flecha grande hacia abajo para desplegar el calendario y selecciono el 13/12/2016 doy a enter y no pasa nada. Le doy a Crear y nuevamente sale la fecha de hoy.

Me temo que no me funciona con ninguna de la formas probadas.

No sé si hay alguna otra manera que se me haya pasado.
![image](https://cloud.githubusercontent.com/assets/22589031/21264753/365aa9ee-c39e-11e6-8d69-777e678fc09f.png)
@CristianBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 

Listo.
![image](https://cloud.githubusercontent.com/assets/20515815/21389941/8fb3a3ee-c784-11e6-9788-abfe42de0eef.png)

Podemos definir la fecha que queramos como fecha de inicial, pero la fecha de estado sigue cogiendo la hora actual de nuestra zona horaria
