### ISSUE TITLE
PRM UNI PRO: PROBLEMAS A LA HORA DE ESCRIBIR COMENTARIOS

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#232]
Noemí reporta errores a la hora de escribir un comentario:
_"Ahora cuando intento escribir un comentario en algún título dentro de la ficha del profesor, el comentario no se guarda al darle a enter. Se me queda con el cursor dentro del comentario y para poder salir de la casilla de comentarios tengo que darle al + como para crear un nuevo comentario."_

¿Está relacionado con la posibilidad de usar RETURN para crear una nueva línea dentro del comentario?
@CristianBinpar @minigoBinpar @franciscorrr

**Comment by franciscorrr** [comment]
@MACEMP Esta funcionalidad sigue siendo la misma. A la hora de crear un comentario existe la posibilidad de añadir nuevas líneas pulsando intro. De echo, en la incidencia #145 se pedía que al modificar los comentarios tuviesemos ese mismo comportamiento que se produce al crear una incidencia.
