### ISSUE TITLE
PRM UNI PRO: PANEL DATOS ACADEMICOS DESAPARECIDO

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#233]
Ha desaparecido el bloque DATOS ACADÉMICOS
![missing panel datos academicos](https://user-images.githubusercontent.com/22589031/28563660-e7419804-7126-11e7-86a4-a324e3495c0a.jpg)
@CristianBinpar @minigoBinpar @franciscorrr

**Comment by franciscorrr** [comment]
Cambios aplicados, pendiente de desplegar.
![image](https://user-images.githubusercontent.com/30254281/28709189-8e63c242-737f-11e7-8f98-8aa3eecf4115.png)
