### ISSUE TITLE
PRM UNI PRO: DASHBOARD PROMOTORES no funciona correctamente

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#234]
Los datos que aparecen en los DB de los promotores no reflejan los datos con fidelidad.
En el de Noemí, no aparece ningún dato.

En el mío, si que aparecen datos.

![db noemi](https://user-images.githubusercontent.com/22589031/28563901-bb948c4c-7127-11e7-8ce8-bd03b28dab7c.jpg)

@CristianBinpar @minigoBinpar @franciscorrr

**Comment by MACEMP** [comment]
Este es el comentario de Noemí sobre el DB una vez subida la versión
_Mi Dashboard sigue igual de tostado pero lo que respecta a los títulos que no aparecían en el desplegable, ahora ya sí aparecen correctamente._
@minigoBinpar @franciscorrr

**Comment by franciscorrr** [comment]
![image](https://user-images.githubusercontent.com/30254281/28661527-3c3728ce-72b7-11e7-87b1-999f04773bab.png)

**Comment by MACEMP** [comment]
Gracias Fran!
Parece que sigue un poco "tostado" como dice Noemí.
El donut con % de NO ADOP/ADOPCIONES muestra un % erróneo y los de ventas indican 0% ¿?
@franciscorrr

**Comment by franciscorrr** [comment]
Sí, hay varios valores que no tienen sentido o son erróneos, vamos a darle un repaso al sistema de dashboard

**Comment by franciscorrr** [comment]
Ahora los porcentajes ya tienen algo de sentido (todavía falta desplegar en PRO)

![image](https://user-images.githubusercontent.com/30254281/28769822-544cd962-75dd-11e7-8dc9-9eba5dd764e6.png)
