### ISSUE TITLE
PRM UNI PRO: faltan datos en MAILS COMUNICACION ACCESO EBOOK Y MATERIAL COMPLEMENTARIO

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#235]
Errores detectados:

En el mensaje de acceso al ebook no aparece la url del ebook , en la que tiene que clicar para acceder
En el mensaje de los materiales complementarios la url te lleva a la web, no a los materiales complementarios si no estás logueado 

@CristianBinpar @minigoBinpar @franciscorrr

**Comment by franciscorrr** [comment]
@MACEMP ¿Podríamos saber con que usuario os ha dado ese problema?

**Comment by MACEMP** [comment]
La falta de datos en el mail ocurre con cualquier usuario que genere un acceso a un ebook.
Mi usuario macastro@medicapanamericana.es o el de alex, anieto@medicapanamericana.es
@franciscorrr

**Comment by franciscorrr** [comment]
Acabo de hacer una prueba y me han llegado dos correos, uno con el acceso y otro con la encuesta. ¿A vosotros no os llegan estos dos correos?
![image](https://user-images.githubusercontent.com/30254281/28669885-75ef2b92-72d6-11e7-9fab-a6631b8df92f.png)
![image](https://user-images.githubusercontent.com/30254281/28669890-7c7d063c-72d6-11e7-892f-89b215acb12a.png)

**Comment by MACEMP** [comment]
Enviaba un único mensaje  (el segundo que copias) no los dos mensajes.
Es importante que el mail de acceso al ebook lleve al usuario o bien al ebook, si ya está logueado, o bien a la zona de registro para que se loguee y acceda al ebook.

@franciscorrr

**Comment by franciscorrr** [comment]
El error se producía cuando se intentaba dar acceso a un usuario preexistente en la BBDD de Panamericana (si el acceso era por pin no había problema). Ya se ha corregido y en cuanto se despliegue se podrá probar. 

Se envía un correo en este formato (para contactos ya registrados en Panamericana)
![image](https://user-images.githubusercontent.com/30254281/28670530-74dd07ee-72d9-11e7-9825-097ab86c5ecd.png)

**Comment by MACEMP** [comment]
¡Perfecto!
Esta funcionalidad la habíamos perdido hace un tiempo.

Gracias.
@franciscorrr
