### ISSUE TITLE
PRM UNI PRO: MODIFICAR ASUNTO MAIL ACCESO EBOOK

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#236]
![image](https://user-images.githubusercontent.com/22589031/28565054-4aa6ea76-712b-11e7-988c-5d6844ab680e.png)

Conviene modificar el ASUNTO del mail en el que se comunica al docente que:
1. se le ha concedido acceso al ebook
2. cumplimente el cuestionario de opinión

Actualmente solo aparece en el ASUNTO del mail Envío del cuestionario de opinión cuando realmente se le está comunicando el acceso al ebook y el cuestionario.

Nuevo asunto:
CONCESIÓN ACCESO A EBOOK  -si es posible indicar el nombre del ebook al que se le concede el acceso

Quedaría así:
CONCESION ACCESO A EBOOK : AAFP:Atlas Microscopia Clínica 4Ed.-e

@CristianBinpar @minigoBinpar @franciscorrr

**Comment by franciscorrr** [comment]
@MACEMP  Entiendo que realmente el correo que muestras sería el correo para el cuestionario de opinión, el correo para el acceso al Ebook es algo parecido a esto:
![image](https://user-images.githubusercontent.com/30254281/28608034-f93ac5cc-71de-11e7-94a7-0826f7669184.png)

¿Cambiamos de todas formas el asunto del correo del cuestionario de opinión a "CONCESION ACCESO A EBOOK: <título del libro>"?

**Comment by franciscorrr** [comment]
@MACEMP Vale, acabo de ver que en algunos casos no se está enviando ese correo que he puesto en la captura y se está enviando justo el que comentabas. Voy a cambiar el asunto y en cuanto esté desplegado os avisamos.

**Comment by MACEMP** [comment]
Perfecto! 
Efectivamente, cuando se concede el acceso al ebook, en el mismo correo se le notifica la concesión y el enlace al cuestionario de opinión
@franciscorrr

**Comment by franciscorrr** [comment]
Asunto del correo cambiado.
