### ISSUE TITLE
ERROR EN INCLUIR EN PENDIENTES: REFERENCIA A OBJETO NO ESTABLECIDA

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#24]
![image](https://cloud.githubusercontent.com/assets/22589031/21271329/dfa0a9f6-c3ba-11e6-8e98-bf287250813b.png)

Se produce este error con 
Contacto Jbuenestado.lleida.ics@gencat.cat 
Material SECO:Afec.Medicoquir. Fisiot. - SME-III
@CristianBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 

Solucionado. Completé el proceso con mi usuario. Si es en problema se puede cambiar:

![image](https://cloud.githubusercontent.com/assets/20515815/21387548/55fe216c-c778-11e6-9544-326b2c6e9232.png)

Noto que este error es recurrente y la causa siempre es la misma: a la hora de mandar el email, si el campo provincia está vacío genera error porque no sabe leerlo.

Propongo:
Revisar el programa para ver dónde más se solicita esta información y avisarle de que si está vacío  no falle

**Comment by MACEMP** [comment]
Perfecto!
