### ISSUE TITLE
PRM VD PRO: DB ADMINISTRADOR NO MUESTRA CORRECTAMENTE LOS ELEMENTOS EN LA PANTALLA

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#240]
![image](https://user-images.githubusercontent.com/22589031/28655113-b7b4c024-7299-11e7-8b84-844708dacedf.png)
@minigoBinpar @CristianBinpar

**Comment by franciscorrr** [comment]
El problema se producía porque no estábamos controlando bien el caso en el que todo fuera 0.

![image](https://user-images.githubusercontent.com/30254281/28657580-1666a002-72a8-11e7-9297-70dbfbe5cadd.png)
