### ISSUE TITLE
PRM VD PRO: AL CREAR UN USUARIO VD APARECEN LAS ZONAS A ASIGNAR COMO EN PRM UNI

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#242]
![image](https://user-images.githubusercontent.com/22589031/28655556-f907b83a-729c-11e7-8d19-4d7f9d1fb8e4.png)
Los VD no tienen la misma asignación de zonas que los UNI. 
¿Cómo se asignan los Códigos postales a los VD?

@CristianBinpar @minigoBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 
Correcto, pero al seleccionar el tipo de usuario VD el sistema entiende que este perfil no posee Zonas y las elimina.

La asignación de CP es en la edición deusuarios
