### ISSUE TITLE
PRM VD PRO: ERROR CREANDO LA NUEVA PROMOCION

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#243]
![image](https://user-images.githubusercontent.com/22589031/28656165-9eedb238-72a0-11e7-9c97-76d71f1dc0a5.png)

Creando una nueva promoción en PRO da este error:
https://prm.medicapanamericana.com/Contacts/ShowContact@44372ab9-e3a0-42bc-b70c-ee81ab44ecda

El material elegido FORMACION - CURSO PEDIATRIA AEP
@CristianBinpar @minigoBinpar

**Comment by franciscorrr** [comment]
@MACEMP  Ya lo tenéis resuelto, también en PRO, con lo que ya se puede probar.
