### ISSUE TITLE
PRM UNI PRO: EN MENSAJE ADOPCION APARECE ##PROMOTOR## EN LUGAR DEL NOMBRE DEL PROMOTOR

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#245]
![image](https://user-images.githubusercontent.com/22589031/28657911-5c49fc6c-72a9-11e7-9c14-26352f972e6a.png)

Debiera de aparecer el nombre del promotor/promotora y no el nombre del campo
@CristianBinpar @franciscorrr @minigoBinpar

**Comment by franciscorrr** [comment]
@MACEMP  Solucionado, faltaba una almohadilla al final y al principio para que lo reconociera (###PROMOTOR###). Está ya disponible en PRO y BETA.

**Comment by MACEMP** [comment]
Gracias!
@franciscorrr
