### ISSUE TITLE
PRM VD PRO:  ERROR AL GENERAR PEDIDO_NO SE PUEDE RESOLVER EL NOMBRE REMOTO

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#246]
![image](https://user-images.githubusercontent.com/22589031/28659070-5542f22a-72ae-11e7-8257-7ea8ef5af3c2.png)
@CristianBinpar @minigoBinpar @franciscorrr

**Comment by franciscorrr** [comment]
Cambios ya implementados a falta de desplegar.

@minigoBinpar Cuando subas esto a los entornos habrá que cambiar el setting "CRM" en el Web.config para que apunte a la ruta correcta del CRM.

![image](https://user-images.githubusercontent.com/30254281/28660051-cf89afb2-72b1-11e7-83bd-f3bc60079804.png)

**Comment by MACEMP** [comment]
¿Puedo realizar ya la prueba?
@franciscorrr @minigoBinpar

**Comment by franciscorrr** [comment]
Ya lo puedes probar

**Comment by MACEMP** [comment]
Este error ya no se produce, pero sigue sin poder completarse el pedido.
Al hacer CONFIRMAR PEDIDO se queda pensando y ni emite el mail ni lleva automáticamente al PRM.
Ahora si que lleva al PRM y no da error 404.
VAMOS AVANZANDO!
@franciscorrr @minigoBinpar
