### ISSUE TITLE
PRM VD PRO: AL GENERAR EL PEDIDO SE QUEDA COLGADO EN ¿ESTÁ SEGURO QUE QUIERE CONFIRMAR ESTA VENTA?

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#248]
![image](https://user-images.githubusercontent.com/22589031/28663376-7994fb28-72bd-11e7-9294-fbbc8cb18fc8.png)
Se queda colgado y no responde.
No envía el mail de comunicación a lblecua & macastro & atencionalclienteformacion
@CristianBinpar @minigoBinpar

**Comment by franciscorrr** [comment]
Hemos hecho pruebas y ahora mismo sí que se están enviando los emails y el sistema responde, aunque si que es verdad que tarda unos 15 segundos.

**Comment by MACEMP** [comment]
Acabo de realizar una prueba, y sigue sin responder y sin enviar el mensaje.
Al volver al PRM (ahora vuelve perfectamente) no aparece la venta como realizada.
Por otra parte, si habéis hecho pruebas de pedido, tanto lblecua como macastro tendríamos que haber recibido el mail de notificación y no ha sido así.
Creo que convendría revisar este issue.
@franciscorrr @minigoBinpar
