### ISSUE TITLE
PRM VD PRO: ERROR 404 AL PULSAR BOTON "VOLVER AL PRM" DESDE CRM

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#249]
![image](https://user-images.githubusercontent.com/22589031/28663529-ea1eca22-72bd-11e7-83c4-cb6ed77396e4.png)

Al pulsar el botón VOLVER AL PRM la respuesta es de error.

@CristianBinpar @minigoBinpar

**Comment by franciscorrr** [comment]
@minigoBinpar He cambiado en el **CRM** la dirección del PRM (apuntaba a http en vez de https). Cuando puedas subirlo a PRO lo probamos.
Gracias!

**Comment by franciscorrr** [comment]
Ya funciona OK
