### ISSUE TITLE
INFORME ADOPCIONES VALORIZADAS: NO APARECE AÑO ACADEMICO 2017-2018

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#25]
![image](https://cloud.githubusercontent.com/assets/22589031/21361163/1dbfaf54-c6e3-11e6-8cfd-4cdf9545941c.png)
En el filtro de AÑO ACADEMICO no aparece 2017-2018.

En todos los informes que hay posibilidad de seleccionar AÑO ACADEMICO debieran aparecer, siempre que se crea un registro con información de ese AÑO ACADEMICO, ese AÑO ACADÉMICO. 

@CristianBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 

Listo:
![image](https://cloud.githubusercontent.com/assets/20515815/21387297/4ccc042a-c777-11e6-9853-3b523ccd0600.png)

He añadido en todos los informes con filtro año académico la capacidad de mostrar 2017-2018

Subo versión en breves
