### ISSUE TITLE
PRM VD PRO: NO APARECE EL GRÁFICO - USUARIO VENTADIRECTA.BINPAR

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#250]
![image](https://user-images.githubusercontent.com/22589031/28665866-63f1fbe2-72c5-11e7-86a4-e3657008c4f7.png)
@CristianBinpar @minigoBinpar

**Comment by franciscorrr** [comment]
Parece que está relacionado con la tarea #234. Vamos a esperar a que subamos esa tarea porque muy posiblemente también se solucione esta.

**Comment by franciscorrr** [comment]
Corregido, cambios pendientes de despliegue.

![image](https://user-images.githubusercontent.com/30254281/28708683-76e44116-737d-11e7-8c38-da91e2b0897c.png)
