### ISSUE TITLE
PRM VD PRO: NO TOMA BIEN LOS PRECIOS DEL MATERIAL

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#251]
![image](https://user-images.githubusercontent.com/22589031/28666686-c154f25a-72c8-11e7-969f-c42923521777.png)

Ver precio de la fase PRIMER CONTACTO y ver precio en PIPELINE
@CristianBinpar @minigoBinpar

**Comment by franciscorrr** [comment]
Corregido y pendiente de despliegue. Se estaba cogiendo el precio de un branch incorrecto.
