### ISSUE TITLE
PRM VD PRO: NO TOMA EL PRECIO CORRECTAMENTE

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#252]
No toma el precio correctamente.
El precio son 1.200€ y toma 0.
http://www.medicapanamericana.com/Libros/Libro/6063/Programa-de-Especializacion-en-Diagnostico-Diferencial-mediante-Ultrasonidos-de-los-Tumores-de-Ovario.html?TipoContenido=&buscador=9788491101758
![image](https://user-images.githubusercontent.com/22589031/28709807-f746bde4-7381-11e7-9e5e-3b3431cc6b7d.png)

https://crm.medicapanamericana.com/Login/VentaDirectaLogin?email=wqdSUiVPQ3k9J1NmGdd6Lglws2MZCY63xVE83mbJSAjz8nv1M56%2fRgQd%2f6A9FwUZQREYBHHBO47%2fiyZy3r%2fr6hQmYIQ441zJY7vdqqU6LyRNYHjMqf6oSQ%3d%3d&isbn=0A36ahGXO7u4waECjwfTqIsQSLy2y4aFTRvwqXTMgIBMxhFHQQwFSGxLGL59Q%2fuaH3mI%2fGoLY25q2kIlT5q9rvIplxNYZmsr&remember=true&redirect=&leadEmail=j17g8hs7T9PoT7vVqanlgUoR5SyRjLoPS7oIw9s1hBjfWqFIlnZr9Tm%2b%2fmrqo%2f87ZXtsqiIF5V%2fLkpnBiIe23Gghx5mUDQaLASVhZXVGNoA%3d&leadPhone=MVnqbPmcQexaIZEz8I0Ns%2bwwqqOgOgAXvYoM70aZrOi893583uX%2f%2fekIabAOxJjkirVKrOAxmdsEzTxVN9WeDU3%2fXqkLDnln&entityID=aVwtq2rOqHWYg5CgMKK4FVFQkcWZhIsM3hd%2b%2bpl91XONog%2fjUeWUaUEIxEy9%2bWic%2fHxtsFfdm5fpLdqDaw9wEv1jbh2NtLTdkfFLP5oy0TmcRl%2bhaaPe9i%2fTZ%2fmfBPQu&timelineEntityID=06%2bpHMSF405LoXD%2bsY7EyalKbUw%2br27yg%2bqGRt8nE8X8y9%2bRao1OflNP%2f%2fDn9pAG81wyxTsRup3oyVtDRMJA%2fGwI1CigxSPTWSMdnfHYdEw16t1Eg%2bVKv16kiBR4SYU2&cryptoHospitalName=rxFRUKZ6FyoS1MQ2ApbS3IYaVOUcxsftR8C%2foVHbU2bEcwIBV0izpKdvWiFWpszGq%2bHgcI2yg8a%2bNFggtcW%2f%2bpHYe7Y%2bmwbasHse31IH%2b06KQ5G%2bU%2bLTj0siY5PQb3cr&cryptoLocalidad=QxmaxOxvCVdVuG%2b3ryEaRsFF45GnqinHJcgBf5Db2q6r7uGgFLPkHuHfq3RbcwSGAiXs4WmDWTqLzAxWbAo%2f5bDf22c%2bZmqsv8FhlDVtSAbYewHETi87sWi1xxsBNNcZ&cryptoProvincia=4sHeUaCYIxCwdg56jGDVpAeDoK0wn8V7Zw4ad1DnbF%2fPsKo1y%2b85Dl%2burp2s1VipbAKbBKarp7vTI1tQ4Ym9kXFFnV6MYSY7CEt6vIfaiwpJUarnNE1k0Tjf7ya2sJx3 

@CristianBinpar @minigoBinpar @franciscorrr

**Comment by franciscorrr** [comment]
Este producto no tiene ningún precio en la tabla ImportesProducto de la BBDD de CRM. ¿Es posible que no se haya hecho la importación de precios de este producto?

``` sql
SELECT TOP (1000) [ID]
      ,[ProductID]
      ,[Importe]
      ,[PI_BRN_ID]
      ,[PrecioLocal]
  FROM [CRM].[dbo].[ImportesProducto]
  WHERE ProductID = 'B67E5DCC-C17C-474B-94CD-2611C514513A'
```

**Comment by franciscorrr** [comment]
Cierre por duplicidad #247
