### ISSUE TITLE
PRM UNI PRO COLOMBIA: SOLICITA INCLUIR LA PROVINCIA RIOBAMBA

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#253]
Desde Colombia solicitan:
_Agradezco por favor la inclusión de la RIOBAMBA en provincia, Atento a indicaciones,_

Nueva provincia en PRM Colombia: Riobamba

@CristianBinpar @minigoBinpar @franciscorrr

**Comment by franciscorrr** [comment]
Ya lo tenéis disponible en Beta y PRO

**Comment by MACEMP** [comment]
Gracias, Fran!
Comunicado a Colombia
@franciscorrr
