### ISSUE TITLE
PRM VD PRO: NO CALCULA BIEN LOS PORCENTAJES DEL PIPELINE

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#255]
![image](https://user-images.githubusercontent.com/22589031/28908351-86d2e7a8-7823-11e7-9b17-515a7bbd83ee.png)

No está calculando bien el porcentaje que tiene que aparecer en el pipeline.
En el ejemplo, si el precio inicial es 33,88, el pipeline al 60% no puede ser 33,88.

@CristianBinpar @minigoBinpar @franciscorrr

**Comment by franciscorrr** [comment]
@minigoBinpar Implementado a falta de desplegar en los entornos.
