### ISSUE TITLE
NO APARECE EN EL INFORME ADOPCIONES LA ADOPCION SILVERTHORN DEL CONTACTO clara@um.es

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#27]
![image](https://cloud.githubusercontent.com/assets/22589031/21453023/85ef64a0-c90b-11e6-9dfe-cd6fe003bbb6.png)
No aparece en el INFORME ADOPCIONES la adopción de esta profesora, a pesar de que está bien creada
@CristianBinpar

**Comment by MACEMP** [comment]
Sucede lo mismo con ricardo.insausti@uclm.es con la adopción del GARCIA-PORRERO.
@minigoBinpar @CristianBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 
Dime si a ti también te aparece:
![image](https://cloud.githubusercontent.com/assets/20515815/23171907/4da6f00e-f854-11e6-8fcb-336297a7a0f6.png)

Creo que guarda relación con la tarea de las zonas de Noemí y Nieto

**Comment by MACEMP** [comment]
Si, aparece en el listado, pero en el Excel y en pantalla  aparece PROMOTOR JAIME DIAZ
![image](https://cloud.githubusercontent.com/assets/22589031/23172751/1bfef210-f857-11e6-94c2-79ae7d054433.png)
![image](https://cloud.githubusercontent.com/assets/22589031/23172794/42da4ee8-f857-11e6-90f3-ff9f47c77e91.png)
@minigoBinpar

**Comment by minigoBinpar** [comment]
@MACEMP es que fue Jaime quién la realizó, ¿no es correcto?

**Comment by MACEMP** [comment]
Si, fue Jaime quién hizo la adopción. 
@minigoBinpar

**Comment by minigoBinpar** [comment]
@MACEMP entonces... solucionado? el problema original era que no aparecía y ahora ya aparece
es correcto?

**Comment by MACEMP** [comment]
Correcto. Antes no aparecía. 
Vaya limpieza de issues!!
@minigoBinpar

**Comment by minigoBinpar** [comment]
jajaja hoy era el día PRM, ya avisé
