### ISSUE TITLE
ERROR GUARDADO DATOS: NO PERMITE CREAR NUEVOS MATERIALES

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#28]
![image](https://cloud.githubusercontent.com/assets/22589031/21981512/1cf82faa-dbe8-11e6-8742-2e97730e392f.png)
@CristianBinpar

**Comment by minigoBinpar** [comment]
Creo que es más bien un error en el mensaje que se muestra. Lo corrijo y subo en próxima versión:
![image](https://cloud.githubusercontent.com/assets/20515815/23172612/a1cac01e-f856-11e6-8cfe-2021b9c55f8b.png)
