### ISSUE TITLE
MEXICO: PROMOTOR TEODORO RODRIGUEZ NO PUEDE HABILITAR ACCESO EBOOK

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#29]
Adjunto documento con las imágenes en las que se comprueba que Teodoro Rodríguez no puede conceder acceso al ebook Silverthorn al docente Pier Angeli Kay To Py Montiel Boeringhuer.
[FALLA PRM E-BOOK Teodoro.pptx](https://github.com/BinPar/PRM/files/708646/FALLA.PRM.E-BOOK.Teodoro.pptx)
@CristianBinpar

**Comment by minigoBinpar** [comment]
El usuario no figura en la base de datos de pana como administrador. De ahí la imposibilidad de conceder accesos a ebook.

Si se le da de alta, el problema queda resuelto

**Comment by MACEMP** [comment]
Comunicado a MEXICO
@minigoBinpar @CristianBinpar
