### ISSUE TITLE
DISCREPANCIA DE DATOS EN DASHBOARD E INFORMES

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#31]
A la hora de hacer el Informe adopciones desde 1/1/2017 a 30/1/2017 aparecen solo 2 promotores -es lo correcto-, sin embargo en el dashboard aparecen los datos de Angel Perez y Jaime Díaz, cuando realmente solo debieran de aparecer datos de Alex y Noemí
![image](https://cloud.githubusercontent.com/assets/22589031/22415749/0ff16ac8-e6ca-11e6-98e1-b16297863edf.png)
![image](https://cloud.githubusercontent.com/assets/22589031/22415800/5ba00ef2-e6ca-11e6-9b75-7fdbfb44d3e0.png)
@CristianBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 
Diría que ya queda corregido:
![image](https://cloud.githubusercontent.com/assets/20515815/23172913/bdfc9158-f857-11e6-8bcf-1bc5087da8c0.png)

**Comment by MACEMP** [comment]
Lo he comprobado y parece que está OK.
@minigoBinpar
