### ISSUE TITLE
INFORME PROMOCION: NO TIENE EN CUENTA LAS NUEVAS ZONAS DE NOEMÍ Y ALEX

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#32]
A la hora de obtener el informe de promoción, solo refleja las promociones realizadas en las antiguas zonas.

No aparece ninguna acción realizada en provincias como Barcelona, Granada, Valencia, Málaga.

No he probado con el histórico, pero imagino que pasará lo mismo.

@CristianBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 

Puedes comprobar los datos ahora?

**Comment by MACEMP** [comment]
Comprobados datos en BETA. Están OK. Confirmado con los Noemí y Alex.
@minigoBinpar

**Comment by minigoBinpar** [comment]
Y en producción?

**Comment by MACEMP** [comment]
Vaya! lo probé en beta. Lo pruebo en producción.
@minigoBinpar

**Comment by MACEMP** [comment]
Comprobado. En Producción también aparecen las promociones de Alex y Noemí de las nuevas zonas.
¿Pueden trabajar ya con normalidad?
@minigoBinpar

**Comment by minigoBinpar** [comment]
Perfecto. Claro, que trabajen ya con normalidad con el PRM.

Cierro issue
