### ISSUE TITLE
ARGENTE VERSIÓN EBOOK : NO SE PUEDE DAR ACCESO A LOS MATERIALES COMPLEMENTARIOS 

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#33]
![image](https://cloud.githubusercontent.com/assets/22589031/22796784/03fef48a-eefc-11e6-929c-dc09cd3efc29.png)
Desde Colombia reportan este error.
No pueden conceder el acceso a los Materiales complementarios desde el PRM al ebook del Argente.
SI se puede hacer desde la versión en papel.
@CristianBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 
¿Que mensaje muestra por pantalla? Dime que usuario ha tratado de realizar esta acción

**Comment by MACEMP** [comment]
Tanto Gilberto Silva de Colombia como yo.
![entregamc](https://cloud.githubusercontent.com/assets/22589031/23158956/4086b78e-f821-11e6-8d9b-7fbe7e71d3f2.jpg)
@minigoBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 

Se trata de un error en la base de datos de Pana. Lo he arreglado para que pueda dar acceso pero si es algo recurrente, lo mismo mañana vuelve a dar error.

He creado la tarea al responsable de Pana y la solucionarán en cuanto puedan
