### ISSUE TITLE
CONCEDER ACCESO A MAC A LAS TABLAS DEL PRM

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#34]
Solicito el acceso a las tablas para poder elaborar consultas desde Excel
@CristianBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 

Añado a la tarea a Cris para que supervise y a Nicolás, que es nuestro responsable en este tipo de acciones. Te vamos comentando

**Comment by minigoBinpar** [comment]
@MACEMP 
Listo. Con el mismo usuario y claves de ppd puedes conectarte a la base de datos de PRM (sólo tienes que elegir el nombre de la base de datos al iniciar la conexión)

**Comment by MACEMP** [comment]
OK! Gracias. Ya he probado y funciona perfectamente.
@minigoBinpar
