### ISSUE TITLE
PRM MEX: REVISION USUARIO TEODORO RODRIGUEZ

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#35]
Envían a Verónica el siguiente mensaje:

_Buen día Vero, el mensaje sucede al momento de querer dar acceso desde el PRM a un ebook.
Por ejemplo se crea una promoción dentro de un contacto (en este caso ebook tortora) luego en el botón de sobre se proporciona acceso, al pulsar enviar es cuando sale el mensaje de que no se encuentra al promotor en la base de datos._
![error acceso ebook](https://cloud.githubusercontent.com/assets/22589031/22937823/0ef41230-f2da-11e6-8140-48273a926933.png)
![acceso ebook](https://cloud.githubusercontent.com/assets/22589031/22937859/2ce3fde6-f2da-11e6-8ad9-11aa675bf5c8.png)
_Datos de acceso PRM
teodoro.rodriguez@medicapanamericana.com.mx
EMP640108_

Aparentemente no hay ningún motivo por el que no pueda conceder acceso a los ebooks. En el PRM aparece como usuario registrado correctamente y realiza otras acciones sin problema.
¿Podrías revisarlo? Lleva ya  tiempo con este problema y no veo que sea del PRM.
@CristianBinpar

**Comment by MACEMP** [comment]
El usuario sigue teniendo el mismo problema
@minigoBinpar @CristianBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 
Lo he comprobado y tal y como dice el mensaje, el promotor no figura como usuario en la base de datos de Panamericana.

El PRM pregunta a Pana cuando se trata de dar accesos a ebooks, para todo lo demás se hacen consultas sólo a la base de datos de PRM en la que este user no presenta ningún problema.

**Comment by MACEMP** [comment]
¿Sabes a quién tiene que pedir el acceso?
@minigoBinpar

**Comment by minigoBinpar** [comment]
Iba a hacerte la misma pregunta jjj

Según parece es algo que tienen que hacer desde Pana, con el gestor

**Comment by MACEMP** [comment]
Gracias. Se lo comunicaré a los de la web para que gestionen ellos los permisos de este usuario.
@minigoBinpar

**Comment by minigoBinpar** [comment]
Perfecto. Cierro issue. Si vuelve a surgir algo, creamos nuevo issue

**Comment by MACEMP** [comment]
![image](https://cloud.githubusercontent.com/assets/22589031/23254734/51f13f3c-f9b9-11e6-8016-896547c0f716.png)
Esta es la ficha de Teodoro en el Gestor de la web y esta la url:
http://gestor.medicapanamericana.com/tables/user.aspx?id=4321

@CristianBinpar @minigoBinpar

**Comment by minigoBinpar** [comment]
las direcciones de correo son distintas
