### ISSUE TITLE
NO APLICA LOS FILTROS EN INFORME ADOPCIONES

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#36]
![image](https://cloud.githubusercontent.com/assets/22589031/23202728/9a93602e-f8df-11e6-9381-782a74864da6.png)
Los filtros de Facultad/Centro no funcionan
@CristianBinpar

**Comment by minigoBinpar** [comment]
Listo. Subo actualizaciones en breves

**Comment by MACEMP** [comment]
![image](https://cloud.githubusercontent.com/assets/22589031/23266093/06612914-f9e7-11e6-8eb4-15811ada39d1.png)
Ahora en el buscador no filtra ni por palabra ni por frase exacta. hay que marcar 1 a 1 los items.
Antes al escribir iba filtrando
@minigoBinpar

**Comment by minigoBinpar** [comment]
Ops, perdón @MACEMP 

Corregido. Te funciona ahora?

**Comment by MACEMP** [comment]
El filtro funciona, pero el buscador, no. Lo que hace realmente complicado y muy lento encontrar un centro o facultad.
@minigoBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 
Solucionado
