### ISSUE TITLE
PRM : NO BORRA MATERIALES A PESAR DE INDICAR CONFIRMAR Y BORRAR

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#37]
![image](https://cloud.githubusercontent.com/assets/22589031/23252197/3908aa9a-f9b0-11e6-946a-43116bbc7a70.png)
A pesar de indicar CONFIRMAR Y BORRAR el material sigue ACTIVO
![image](https://cloud.githubusercontent.com/assets/22589031/23252288/a410da56-f9b0-11e6-96c4-61d90cba8893.png)
@CristianBinpar

**Comment by minigoBinpar** [comment]
¿por qué material lo sustituyes?

**Comment by MACEMP** [comment]
Por ninguno. Fue un error.
@minigoBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 
Cuando elijes un producto a borrar y el que lo sustituirá en el combo, al pulsar confirmar y borrar, te da error?

**Comment by minigoBinpar** [comment]
Borro en bbdd
