### ISSUE TITLE
NO APLICA FILTRO FACULTAD/CENTRO EN INFORME PROMOCIONES

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#38]
![image](https://cloud.githubusercontent.com/assets/22589031/23266233/7b84f752-f9e7-11e6-86e6-d81a26d1933a.png)
Sucede lo mismo que con el INFORME ADOPCIONES.
Aquí si que funciona el buscador
@CristianBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 
Lo mismo de adopciones. Prueba ahora

**Comment by MACEMP** [comment]
Funciona el buscador y el filtro. OK!
@minigoBinpar
