### ISSUE TITLE
APARECEN UNIVERSIDADES Y PROMOCIONES DE ARGENTINA EN PRM ESPAÑA

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#39]
![image](https://cloud.githubusercontent.com/assets/22589031/23351409/3f27f28c-fcc1-11e6-8c65-315aba29024d.png)
Al buscar la Universidad Rovira i Virgil no aparece y, sin embargo, aparecen en el listado universidades de Argentina.
Por otra parte, el navegador da un error de SITIO NO SEGURO
@CristianBinpar

**Comment by MACEMP** [comment]
![image](https://cloud.githubusercontent.com/assets/22589031/23351519/02be664a-fcc2-11e6-87f7-5fa3188c8eaf.png)
No solo aparecen universidades de Argentina, tambien de Colombia y México
@minigoBinpar @CristianBinpar

**Comment by minigoBinpar** [comment]
Controlado. Te llamo y te explico. En breves subo los cambios a pro y beta

**Comment by minigoBinpar** [comment]
Cierro issues. Asumo que será necesario repasar los contenidos del prm relativos a universidad ya que la funcionalidad parece correcta.
![Uploading image.png…]()
