### ISSUE TITLE
UNIVERSITAT ROVIRA I VIRGILI NO APARECE EN LOS INFORMES

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#40]
![image](https://cloud.githubusercontent.com/assets/22589031/23351768/59e107a6-fcc3-11e6-9861-458b3b63c364.png)
La URV no aparece ni en el buscador ni cuando se descargan los informes en Excel.
Tendría que aparecer como Universitat Rovira i Virgili. 
Las direcciones de mail son xxxxx@urv.cat
@CristianBinpar

**Comment by minigoBinpar** [comment]
Esta universidad no aparece en los resultados de búsqueda  porque esta borrada:
![image](https://cloud.githubusercontent.com/assets/20515815/23354124/00a1a788-fcd0-11e6-87a3-8325b594ff72.png)

Se peude gestionar el estado en administración

**Comment by MACEMP** [comment]
Gracias. Ya la he reactivado
@minigoBinpar
