### ISSUE TITLE
NO APARECEN DATOS EN PRM

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#41]
![image](https://cloud.githubusercontent.com/assets/22589031/23352292/a4c10a84-fcc6-11e6-88b2-b54c0e7dae87.png)

Noemí me pasa un mensaje con errores que está detectando en el PRM.
Algo extraño está sucediendo.

@CristianBinpar

**Comment by minigoBinpar** [comment]
Arnedo en papel 2016:
![image](https://cloud.githubusercontent.com/assets/20515815/23355817/ca6b6e44-fcd7-11e6-9dcb-a08fa3394c89.png)

Alberca ebook 2016:
![image](https://cloud.githubusercontent.com/assets/20515815/23355848/e5a15390-fcd7-11e6-97a9-1091d2e73d2d.png)

Arnedo ebook 2016
![image](https://cloud.githubusercontent.com/assets/20515815/23355882/03263c28-fcd8-11e6-95a9-314278483ca4.png)


Creo que está todo.

**Comment by MACEMP** [comment]
Gracias!
¿Cual era el motivo por el que no aparecían? Solo por curiosidad
@minigoBinpar

**Comment by minigoBinpar** [comment]
Uno de los archivos del proyecto no se actualizó correctamente en la última subida de la semana pasada. A veces ocurren estas cosas. No tiene repercusión ninguna, simplemente hay que resubir el fichero y listo :)

**Comment by MACEMP** [comment]
Un pequeño rasguño que ni necesita betadine :-)
@minigoBinpar
