### ISSUE TITLE
NOEMÍ MARTIN REPORTA: el PRM me echa cada dos por tres.

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#42]
Este es el comentario de Noemí sobre el PRM hoy:
el PRM vuelve a estar raro hoy. Me echa cada dos por tres.

Ayer comunicaron tanto ella como Alex que los echaba constantemente.
¿Cual puede ser el motivo?

@CristianBinpar

**Comment by MACEMP** [comment]
Alex informa de que, también a el,  el PRM se cierra constantemente.
¿Podrías revisarlo? Se hace muy complicado trabajar así.
@CristianBinpar @minigoBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 
Estoy tratando de replicar el error. ¿Hacían alguna acción en concreto?

**Comment by MACEMP** [comment]
Ninguna en particular. Tanto Noemí como Alex trabajan mucho con la creación de promociones y contactos. Mientras que yo trabajo más con la parte de Informes.
Parece que los problemas comenzaron cuando hubo el cambio de servidor la semana pasada.
No sé si tiene algo que ver.
@minigoBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 
Estoy tratando de replicar el error. ¿Hacían alguna acción en concreto?

Pd. Creo que si usas la opción de recordar contraseña el programa no te saca:
![image](https://cloud.githubusercontent.com/assets/20515815/23695891/9cb5be9e-03e1-11e7-9f2a-134263346cbd.png)

Solución temporal mientras busco que ocurre

**Comment by MACEMP** [comment]
Gracias. Lo comunico a los promotores.
Nos vemos en 5 minutos.
@minigoBinpar

**Comment by MACEMP** [comment]
Al tratar de acceder al PRM filial MEX el PRM se sacó del programa. Al inciar sesión nuevamente, me situó en MEX.
@minigoBinpar

**Comment by CristianBinpar** [comment]
Se ha eliminado por el momento el balanceo de carga con lo que el problema parece solucionado.

SI se vuelve a reproducir abriremos incidencia.

**Comment by MACEMP** [comment]
Ayer México no reportó ninguna incidencia
¡Qué alegría haberlo resuelto!
@CristianBinpar
