### ISSUE TITLE
NO SE PUEDE CREAR MATERIAL

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#43]
Al intentar crear este material
![image](https://cloud.githubusercontent.com/assets/22589031/23702165/6d2faf04-03fa-11e7-8be1-74936ff75439.png)
se obtiene la respuesta 

![image](https://cloud.githubusercontent.com/assets/22589031/23702137/517706c2-03fa-11e7-900d-77e8ba40d909.png)

No existe ningún material ni con ese EAN ni con esa DENOMINACIÓN. Solo existe la versión ebook
![image](https://cloud.githubusercontent.com/assets/22589031/23702249/bb50b214-03fa-11e7-9017-48815c7918dc.png)

@CristianBinpar

**Comment by minigoBinpar** [comment]
Se puede crear el material en beta con las correcciones que te comenté al teléfono:
![image](https://cloud.githubusercontent.com/assets/20515815/24343130/291b6590-12c5-11e7-832f-67f612b9fac9.png)
