### ISSUE TITLE
INFORME CUESTIONARIOS DE OPINIÓN: ERROR EN EL SERVIDOR

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#44]
![image](https://cloud.githubusercontent.com/assets/22589031/23737555/23d45662-0494-11e7-8a57-888daf835c59.png)
Al solicitar el INFORME CUESTIONARIOS DE OPINIÓN, se obtiene un mensaje de error en el archivo descargado
@CristianBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 
Puedes mandarme url ?

**Comment by MACEMP** [comment]
https://prm.medicapanamericana.com/Informes/CuestionariosOpinion 
En pantalla se visualiza correctamente, pero no aparecen todos los campos que aparecen en el excel.
![image](https://cloud.githubusercontent.com/assets/22589031/23754605/ddfd07e8-04dd-11e7-8d05-a29deb813794.png)
@minigoBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 
Bien, creo que lo tengo controlado. Faltaría subir versión.

He tenido que implementar un cambio para corregirlo que, creo, no modifica los datos. En cualquier caso si pudieras repasar el zip adjunto para asegurar que todo es correcto, tanto mejor (así me lo ha parecido a mi).

[Informe_Cuestionarios_1489074163473.zip](https://github.com/BinPar/PRM/files/831508/Informe_Cuestionarios_1489074163473.zip)

**Comment by MACEMP** [comment]
El excel está OK
@minigoBinpar
