### ISSUE TITLE
PRM MEXICO: VARIOS ERRORES REPORTADOS POR USUARIO ALMA MANZO

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#45]
La usuaria Alma Manzo reporta  la responsable de PRM MEX (Belem Peña) os siguientes errores al trabajar con el PRM:
•	_Al tratar de registrar al contacto no lo permite
•	Y cuando logro registrar al contacto no permite hacer la promoción
•	Y en algunas ocasiones si logro hacer el registro y la promoción
•	En la pantalla que te envío se pone así cuando trato de hacer la promoción
•	Y ya te había enviado otra pantalla en la que se pone una ventana al tratar de registrar o hacer la promoción._
Alma no aporta más datos que la relación de  errores. He indicado a Belem que lo primero es CRTL+MAY+R y que para replicar los errores necesitamos más datos.

De todos modos, ¿Podrías revisar su usuario alma.manzo@medicapanamericana.com.mx?
@CristianBinpar

**Comment by minigoBinpar** [comment]
_Al tratar de registrar al contacto no lo permite_: Asumo que se refiere a dar de alta un usuario, ¿verdad? 
_Y cuando logro registrar al contacto no permite hacer la promoción_: Esto es un poco contradictorio con el punto anterior, no? 
_Y en algunas ocasiones si logro hacer el registro y la promoción_: Necesitaría más datos...
_En la pantalla que te envío se pone así cuando trato de hacer la promoción_: tienes esto por ahí?
_Y ya te había enviado otra pantalla en la que se pone una ventana al tratar de registrar o hacer la promoción_: idem
![image](https://cloud.githubusercontent.com/assets/20515815/24343354/48f489f4-12c6-11e7-9970-10f18d9d98b1.png)

**Comment by MACEMP** [comment]
CIERTO: Registrar = Dar de alta contacto
Comentario Alma: Y cuando logro registrar al contacto no permite hacer la promoción: 
Respuesta minigo: Esto es un poco contradictorio con el punto anterior, no?
Respuesta MAC: no es contradictorio. Una vez dado de alta un usuario, el promotor CREA PROMOCIONES, lo que Alma llama "hacer promociones"
¿Es posible que todos estos errores estuviesen relacionados con los problemas del servidor?
@minigoBinpar

**Comment by minigoBinpar** [comment]
@MACEMP me refería a que es contradictorio no poder crear un contacto y en el punto siguiente decir que he creado un contacto pero tengo problemas otros porblemas X

no sabría decir, decía que le mandabaal login? seguiré revisando su user

**Comment by MACEMP** [comment]
Podría parecerlo, pero entiendo que Alma intentaba una y otra vez crear el usuario, hasta que en algún momento lograba hacerlo . Una vez creado intentaba crear la promo y le sucedía lo mismo, por eso me pregunto si estará relacionado con los problemas de acceso al servidor. A veces funcionaba y a veces no.
He escrito a México preguntando si ya se solucionaron los problemas  de esta promotora.
Desde que se solucionó lo del balanceo no he vuelto a tener ningún reporte de error del PRM.
@minigoBinpar

**Comment by minigoBinpar** [comment]
@MACEMP Creo que, como bien dices, necesitamos algo más de información para ver que ocurre. Acciones concretas y capturas de pantalla de los errores

**Comment by MACEMP** [comment]
Sugiero cerrar el issue y si reportan nuevos errores, abrir uno nuevo con más detalles.
Estoy convencida de que todo se debía al problema de acceso al servidor.
@minigoBinpar
