### ISSUE TITLE
"ENVIAR EN PROMOCIÓN" EMITE MENSAJE DE ERROR - NO PERMITE AÑADIR LOCALIDAD

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#5]
Se producen dos errores con este contacto:
- No permite incorporar la localidad, a pesar de que aparece como localidad Villacarrillo
- Aparece un mensaje de error cuando se indica ENVIAR EN PROMOCIÓN el material SERAM:MANUAL...
  Adjunto imagen
  ![image](https://cloud.githubusercontent.com/assets/22589031/19357072/46b9e058-9170-11e6-99d5-772b438852df.png)
  @CristianBinpar

**Comment by minigoBinpar** [comment]
Solucionado. Subo en breves versión
![image](https://cloud.githubusercontent.com/assets/20515815/20749458/bda7af22-b6f2-11e6-9627-ea84d2c02b0e.png)
