### ISSUE TITLE
MENSAJE CONCESIÓN ACCESO EBOOK

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#50]
Comentan los promotores que se ha modificado el mensaje que reciben los profesores cuando se les concede el acceso a un ebook.
Antes recibían este:
![prm esp comunicacion acceso ebooks](https://cloud.githubusercontent.com/assets/22589031/24089803/c544c546-0d3a-11e7-83e1-94d11752c582.jpg)

y ahora reciben este:
![prm esp 17_03_2017 comunicacion acceso ebooks](https://cloud.githubusercontent.com/assets/22589031/24089822/f063bb1a-0d3a-11e7-903b-b654fb48ddf8.jpg)

A los receptores del mensaje no les aparece ni las instrucciones de acceso, ni el enlace a http://www.medicapanamericana.com/eBooks.aspx

El mensaje que ha de enviar es el que tiene unas instrucciones más detalladas de acceso.
@CristianBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 
Pero es que ese no es el mensaje de acceso al ebook, sino el mensaje de Cuestionario de Opinión para Ebook.

Ambos mensajes siguen activos y vigentes. ¿Es posible que se trate de una confusión?

**Comment by MACEMP** [comment]
Cuando se concede acceso a un ebook, el docente tendría que recibir 2 mensajes o bien 1 que incluyese la información:
1. concesión acceso al ebook
2. notificación url para cumplimentar el cuestionario de opinión
Hasta hace un tiempo era así, pero ahora solo reciben un mensaje en el que se le comunica que se le ha concedido el acceso al ebook, pero sin las instrucciones de cómo acceder al mismo.
Hemos detectado que ha bajado la tasa de apertura de ebooks, y este puede ser uno de los motivos, al no detallar cómo tienen que acceder, posiblemente desistan.
@minigoBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 
Añado el cuestionario de opinión parejo al acceso a ebook
