### ISSUE TITLE
DOCENTES CON 2 MAILS NO APARECEN COMO REGISTRADOS EN LA WEB

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#52]
Alex y Noemí reportan el siguiente error:
_Al sacar un listado en histórico de promociones nos facilita la opción Alta WEB SI/NO.
En ocasiones el docente está registrado, pero al exportar el EXCEL aparece como NO registrado.
Esto sucede en docentes que tienen asignadas varias direcciones de correo en su perfil:
 Aunque marquemos el mail con el que está registrado, al sacar el histórico de promociones en ocasiones asigna otro correo (no registrado) y aquí está el problema.
Contactamos con docentes que supuestamente no están registrados, y sí lo están._
![prm contactos con varios mails aparecen como no resgistrados en la web](https://cloud.githubusercontent.com/assets/22589031/24295615/e5e797c4-109b-11e7-8f89-e5d2cd3ed137.png)
Uno de los baremos para medir la actividad de los promotores es el número de docentes que aparecen como registrados en el WEB. Si, a pesar de estar registrados , aparecen como no registrados por tener dos direcciones de mail, los datos no son reales.
@CristianBinpar

**Comment by MACEMP** [comment]
Los promotores "se quejan" de que este problema sigue sin solución.
Sería conveniente resolverlo porque les resta bastante tiempo averiguar con qué email está registrado el docente.
@CristianBinpar @minigoBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 
La cosa es que técnicamente este usuario (su email, que es como registramos a los users) no figura en la bbdd de Pana:

![image](https://user-images.githubusercontent.com/20515815/27596329-9de02568-5b5f-11e7-87c1-d8d11f508c0c.png)

Se puede plantear que si alguno de los emails asociados figura en Pana marque como **SI**, pero no sé si el día de mañana presentará algún problema (ya que, como dije al principio, no es técnicamente exacto que esa persona figure en Pana)

**Comment by MACEMP** [comment]
¿No sería posible que, si un contacto tiene 2/3 direcciones de mail asociados, asignase al mail dado de alta las acciones?
Las restantes direcciones de mail quedarían como información adicional al contacto.
@minigoBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 

![image](https://user-images.githubusercontent.com/20515815/27643970-c9ba4fc4-5c22-11e7-8587-21820d4e8587.png)

![image](https://user-images.githubusercontent.com/20515815/27643988-d2117e22-5c22-11e7-9020-0bee562dabfc.png)

**Comment by minigoBinpar** [comment]
![image](https://user-images.githubusercontent.com/20515815/27644949-23a7fbd8-5c25-11e7-8412-fc7d5477d25d.png)

**Comment by MACEMP** [comment]
¿Qué pasa con los ya creados? 
@minigoBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 
Buena pregunta. No tiene carácter retroactivo esta medida. Si quieres podemos plantear una nueva issue con ello

**Comment by MACEMP** [comment]
Si, por favor 
@minigoBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 
¿Podrías plantearla? GRacias!

**Comment by MACEMP** [comment]
Hecho!
