### ISSUE TITLE
DUDA : el buscador de la sección INFORMES ¿no busca por mail del contacto?

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#53]
Responde perfectamente cuando se pone el nombre del contacto o nombre+apellidos, pero cuando se indica el mail no responde.
@CristianBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 
te refieres a algún informe en particular?

**Comment by MACEMP** [comment]
INFORME HISTORICO - ADOPCIONES - NO ADOPCIONES
Esto lo vi al investigar lo que pasaba con Jose Luis Dueñas

@minigoBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 
Acabo de mirar y el buscador sólo filtra por Nombre de la Entidad, Material o Promotor. Nada de Emails.

¿Consideras necesario añadir el email ala búsqueda?

**Comment by MACEMP** [comment]
No, no. Me extrañó por eso pregunté. Con saberlo es suficiente. GRACIAS
@minigoBinpar
