### ISSUE TITLE
POLTERGEIST contacto jlduenas@us.es

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#54]
Cuando se accede a este contacto desde HISTORICO DE PROMOCIONES aparecen unas promociones (1) que no aparecen cuando se accede desde la ficha del contacto (2)
(1) https://prm.medicapanamericana.com/Contacts/ShowContact@EA082BD9-F4FF-446B-B13F-19F9C3D83246
(2) https://prm.medicapanamericana.com/Contacts/ShowContact@6280785a-61a1-4248-857a-7e4469b0ee93
(1)
![image](https://cloud.githubusercontent.com/assets/22589031/24505997/4c345b24-155c-11e7-9a63-cc6fb0f94128.png)

(2)
![image](https://cloud.githubusercontent.com/assets/22589031/24505987/43594ca8-155c-11e7-8f2f-c861f3f20f71.png)

Verdaderamente misterioso!
@CristianBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 
¿Pudiera ser porque tenemos 2  JOSÉ LUIS DUEÑAS DÍEZ?
http://localhost:53385/Contacts/ShowContact@6280785a-61a1-4248-857a-7e4469b0ee93
http://localhost:53385/Contacts/ShowContact@EA082BD9-F4FF-446B-B13F-19F9C3D83246

Creo que el verdadero misterio es cómo se han creado 2 usuarios iguales

**Comment by MACEMP** [comment]
¿Permite crear 2 usuarios con el mismo mail?!!!!!!???????
@minigoBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 
Por la vía normal, no. A menos que alguien haya encontrado un loop o algo en el sistema.

Me pongo a investigar el caso.

¿Consideras necesario aunar ambos usuarios y sus promociones?

**Comment by MACEMP** [comment]
SI se trata del mismo usuario-concide dirección mail, universidad, departamento, asignaturas que imparte,... si, ya que sin duda se trataría del mismo usuario.
es raro, raro!
@minigoBinpar

**Comment by MACEMP** [comment]
El contacto jlduenas@us.es AHORA no aparece en INFORME PROMOCIONES ni en INFORME HISTORICO PROMOCIONES

![image](https://user-images.githubusercontent.com/22589031/27635868-24be2dec-5c09-11e7-9178-e5f18e9fcf83.png)
![image](https://user-images.githubusercontent.com/22589031/27635891-416bfe2e-5c09-11e7-9cd5-96f039618968.png)


Aparece en CONTACTOS

![image](https://user-images.githubusercontent.com/22589031/27636002-b378f166-5c09-11e7-9ad5-481a921c5b0a.png)

@minigoBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 
Creo que es un tema de filtros: en promociones e histórico de promociones no buscamos por email:

![image](https://user-images.githubusercontent.com/20515815/27639035-64cc9142-5c15-11e7-9245-1fbd279220f5.png)

![image](https://user-images.githubusercontent.com/20515815/27639046-6da240dc-5c15-11e7-974c-2104c39ab029.png)

Contactos sí que filtra por email:

![image](https://user-images.githubusercontent.com/20515815/27639075-7c205608-5c15-11e7-9148-ea331b4913ef.png)

**Comment by MACEMP** [comment]
Si, parece que es un tema de filtros y de reconocimiento de las tildes.
![image](https://user-images.githubusercontent.com/22589031/27639202-cd307276-5c15-11e7-93f9-a929a62757a9.png)

Si se utiliza "José" en lugar de "Jose", aparece el contacto
![image](https://user-images.githubusercontent.com/22589031/27639222-dc228986-5c15-11e7-8d82-e1988dda6a2c.png)

No debiera de tener en cuenta ni MAYUSCULAS ni TILDES.
Lo mismo nos ocurre en el PPD cuando se realiza la búsqueda por PRODUCTO / OBRA.
Tenemos que utilizar las tildes para que lo reconozca.

¿No podría realizar la búsqueda sin tener en cuenta TILDES/MAYUSCULAS?

Por otra parte, no tiene mucha lógica que un buscador funcione con la dirección de mail y otro no ¿verdad?
@minigoBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 
#180
