### ISSUE TITLE
PRM COLOMBIA: exportación a excel contacto GILBERTO SILVA

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#55]
El responsable de promoción en Colombia, Gilberto Silva, reporta el mismo error que su compañero Rolando Padilla:

_Aprovecho para informarle que realice el mismo ejercicio de exportación de los datos de mi PRM, y encuentro diferencias (teniendo en cuenta la aplicación de los filtros). En el PRM tengo registrados 932 datos, y en el Excel 251 datos,_
@CristianBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 

Es lo mismo del la última incidencia reportada: originalmente se preparó para exportar datos de usuarios con una sola zona asociada. 
Ya lo tengo controlado, pero me gustaría subir versión el lunes por la mañana por lo que pudiera ocurrir. 

Puedes comunicar Gilberto que el lunes a primera hora lo tendrá disponible.
Un saludo!

[Informe_Contactos_1490939156566.zip](https://github.com/BinPar/PRM/files/884630/Informe_Contactos_1490939156566.zip)

**Comment by MACEMP** [comment]
¡Comunicado!
Gracias :-)
@minigoBinpar

**Comment by MACEMP** [comment]
Hola!
¿está ya subida la versión que resuelve el problema de descarga de contactos a excel de Gilberto?
@minigoBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 
Ángeles,

Estamos teniendo algún problemilla con las conexiones a la base de datos de Pana. Están Jose y el de sistemas en ello. En cuanto quede solucionado, subo versión y te aviso :)

**Comment by MACEMP** [comment]
OK! Gracias Marcos.
@minigoBinpar
