### ISSUE TITLE
PETICIÓN MÉXICO: INCORPORACIÓN PROVINCIAS REPUBLICA DOMINICANA y ZONA CUBA

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#56]
Desde México solicitan:
_Me podrías auxiliar a crear las siguientes provincias que pertenecen a República Dominicana:

•	Arroyo Hondo
•	Distrito Nacional
•	La Romana
•	Peravia
•	San Pedro de Macorís
•	Santiago de los Caballeros
•	Santo Domingo

Así como la siguiente zona y su provincia:

CA - Cuba	La Habana_
@CristianBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 

¿A que usuario asociamos la nueva zona de cuba?

**Comment by MACEMP** [comment]
No me lo han indicado ¿No se puede reasignar posteriormente?
@minigoBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 

Si, pero uno por defecto debe de tener. ¿Ponemos a macastro?

**Comment by MACEMP** [comment]
Pon a Belem Peña. Es la coordinadora de promoción de Mexico. GRACIAS
@minigoBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 
Listo
![image](https://cloud.githubusercontent.com/assets/20515815/25263369/9d37c998-265f-11e7-9abd-30e69ae477fe.png)

**Comment by MACEMP** [comment]
Gracias . Les puedo comunicar que ya está?
@minigoBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 

Por supuesto :)

Si necesitan algún ajuste en esta línea, le daré prioridad hasta que estandaricemos el proceso con alguna nueva tarea

**Comment by MACEMP** [comment]
GRACIAS!
@minigoBinpar
