### ISSUE TITLE
Añadir Perfil Venta Directa

### ISSUE THREAD

**Issue by CristianBinpar** [BinPar/PRM#57]
Nuevo perfil Venta Directa.
El tipo de usuarios se tratará de forma específica.

**Comment by CristianBinpar** [comment]
Cambiamos facultad por hospital en los datos de alta

**Comment by CristianBinpar** [comment]
Facultad y Universidad desaparecen

**Comment by minigoBinpar** [comment]
@MACEMP 
![image](https://cloud.githubusercontent.com/assets/20515815/25380429/7c41c384-29b0-11e7-813c-d5c1aaf1d414.png)

**Comment by CristianBinpar** [comment]
@MACEMP con qué tipos de usuario trabajarán los perfiles Venta directa?

**Comment by MACEMP** [comment]
Confirmado con Luis serán:
Profesional 
Estudiante 
@CristianBinpar

**Comment by minigoBinpar** [comment]
Listo este punto
