### ISSUE TITLE
Gestión de contactos para perfil Venta Directa por Código Postal

### ISSUE THREAD

**Issue by CristianBinpar** [BinPar/PRM#58]
En la ficha de los usuarios VD, aparecerá una nueva sección: Códigos Postales Asignados.
Podrían definir uno o varios códigos postales e incluso rangos.

**Comment by CristianBinpar** [comment]
Cuando me asignan uno o varios códigos postales se me notificará vía email

**Comment by minigoBinpar** [comment]
![image](https://cloud.githubusercontent.com/assets/20515815/26816540/5893d76c-4a92-11e7-8e6f-fed96eb847fd.png)


![image](https://cloud.githubusercontent.com/assets/20515815/26815833/e4f9541a-4a8e-11e7-8386-405941260660.png)

![image](https://cloud.githubusercontent.com/assets/20515815/26816533/4edaa99e-4a92-11e7-9f89-804d13a6ed6a.png)
