### ISSUE TITLE
Añadir campo Origen solo para tipo "Oportunidad Venta Directa"

### ISSUE THREAD

**Issue by CristianBinpar** [BinPar/PRM#59]
A la espera de los posibles valores.

**Comment by MACEMP** [comment]
Origen:
- Congreso
- Visita hospitalaria
- Base de datos propia
@CristianBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 
Este campo iría en el alta de la entidad o en la creación de la VD?

**Comment by MACEMP** [comment]
Cierto! Resuelto en #61 
@minigoBinpar
