### ISSUE TITLE
JDIAZ_ENVIAR EN PROMOCIÓN: SE HA PRODUCIDO UNA SITUACION DE EXCEPCIÓN...

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#6]
![error enviar en promocion](https://cloud.githubusercontent.com/assets/22589031/19546774/b808c66c-9692-11e6-8d88-35883be9aff4.jpg)
JDIAZ comenta: "al querer enviar un libro a través de la Tablet (con otros libros a otros profesores no he tenido problema), el mensaje que me ha salido es el que ves a continuación (ver imagen)
Material: Nielsen
Contacto: NICANOR MORALES DELGADO 
Mail: nmd@um.es
Es la segunda vez que a este promotor le ocurre. En otra ocasion fue con un libro de la SERAM y otro contacto.
@CristianBinpar

**Comment by minigoBinpar** [comment]
Es algo puntual o hay capacidad de replicar el error?

Es poca información

**Comment by MACEMP** [comment]
El usuario Jaime Díaz ya no está en el PRM (ni el departamento de promoción). Ahora sus contactos los gestiona Noemí Martín y por el momento no ha reportado ningún error.
@minigoBinpar @CristianBinpar
