### ISSUE TITLE
Cambios en la ficha de contacto

### ISSUE THREAD

**Issue by CristianBinpar** [BinPar/PRM#61]
Solo para contactos de tipo "Oportunidad Venta Directa":

- [x] Promociones e historial pasa a nombrarse: Oportunidades y Pipeline.
- [x]  En el histórico, además del nuevo estado, nueva columna con el %.
- [x]  Acceso a cualquier material, con filtro por tipo. Principalmente utilizarán productos de formación.
- [x]  Al generar la oportunidad en la primera ficha se debe mostrar el precio web del producto.
- [x]  Datos Académicos desaparece.
- [x]  Adopciones -> Oportunidades concretadas (consultar columnas a mostrar con MAC)

**Comment by CristianBinpar** [comment]
Sería bastante similar a:
![image](https://cloud.githubusercontent.com/assets/17255550/25216883/ed915776-25a4-11e7-9f8d-8cc4ab301ba5.png)

**Comment by CristianBinpar** [comment]
Contemplar también la fecha de cierre, estimada por el perfil VD

**Comment by MACEMP** [comment]
Incorporar campo FUENTE a CONTACTO:
Desplegable con 3 items: Visita hospitalaria - Congresos - Cartera propia
@CristianBinpar @minigoBinpar

**Comment by CristianBinpar** [comment]
Enviado por correo el último listado.
Cargaremos los datos en CRM y la BBDD del PRM se sincronizará diariamente con ella.
