### ISSUE TITLE
Venta Directa: Fases del proceso de venta

### ISSUE THREAD

**Issue by CristianBinpar** [BinPar/PRM#62]
INICIO
 
Fase 1: Primer contacto con el alumno y trasmisión de la información de curso concreto (Probabilidad 10%)
Fase 2: Contacto de Seguimiento realizado y concreción del programa (Probabilidad 30%)
Fase 3: Concreción de condiciones económicas y financiación (Probabilidad 60%)
Fase 4 Gestión de Hoja de pedido 80%
Fase 5 Tramitación del pedido 100%
Fase 6: Oportunidad Perdida
 
VENTA

**Comment by CristianBinpar** [comment]
Necesitaremos iconos de diseño

**Comment by minigoBinpar** [comment]
@MACEMP 
Hola Ángeles,

Una duda rápida: en la fase 1 dónde dice alumno, entiendo que habría que modificarlo ya que el contacto puede producirse con varios tipo de perfil. Es correcto?

Deberíamos dejar la opción de retroceder en fases (pasar de una 4 a una 3, etc?)

**Comment by MACEMP** [comment]
Hola Marcos!!
Confirmado: mantenemos denominación ALUMNO
Confirmado: no se puede retroceder en las fases
@minigoBinpar
