### ISSUE TITLE
PETICION COLOMBIA: NUEVAS PROVINCIAS

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#64]
Desde Colombia solicitan:

_Por solicitud del promotor SR. ROLANDO PADILLA favor incluir en PROVINCIA: Tunja

Y de acuerdo a mis responsabilidades agradezco incluir: AMBATO_ (SR. GILBERTO SILVA)

Tenemos otra petición de México de inclusión de provincias pendiente de solucionar.
Sería conveniente pensar en dar permiso al administrador de cada filial para que cree provincias y las asigne a ZONAS. 

Los promotores no pueden volcar sus visitas en el PRM al no poder crear el contacto con los datos correctos.
@CristianBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 

¿Tunja a qué país pertenece? Me salen varios por suramerica

Y AMBATO como provincia o zona? 

Con respecto a inclusión de provincias voy a crear una tarea específica a parte, si te parece bien, para tratar el nuevo desarrollo

**Comment by MACEMP** [comment]
Estás en todo :-)
TUNJA: Colombia
AMBATO. Ecuador
Ciertamente se necesita la opción de que el administrador de la filial cree PROVINCIAS
@minigoBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 
Listo

**Comment by MACEMP** [comment]
GRACIAS!
@minigoBinpar

**Comment by MACEMP** [comment]
He accedido al PRM COLOMBIA.
AMBATO aparece en País Colombia Provincia Quito ¿?
Tunja no aparece en el listado de localidades 
![image](https://cloud.githubusercontent.com/assets/22589031/25265751/ced6265c-266e-11e7-9305-612e61457bb9.png)
@minigoBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 

Ambato estaba como localidad asociado a Colombia (¿?), lo cambio a ecuador
![image](https://cloud.githubusercontent.com/assets/20515815/25266386/443e7582-2671-11e7-9407-cf8103711a61.png)

TANJUA a que provincia está asociado?

**Comment by MACEMP** [comment]
Tunja es un municipio colombiano, capital del departamento de Boyacá. 
Hasta geografía aprendemos con el PRM :-)
@minigoBinpar

**Comment by MACEMP** [comment]
El nombre es TUNJA no Tanjua
@minigoBinpar

**Comment by minigoBinpar** [comment]
Listo

**Comment by MACEMP** [comment]
En el listado de LOCALIDADES del PRM COLOMBIA no aparecen ¿misterio?
@minigoBinpar

**Comment by MACEMP** [comment]
PERDON!!!
Tal es la costumbre de verificar primero en BETA que no lo verifiqué en PRODUCCION. Está OK.
Disculpas
@minigoBinpar
