### ISSUE TITLE
Alta contacto

### ISSUE THREAD

**Issue by minigoBinpar** [BinPar/PRM#68]
Creo que sería conveniente hacer el campo zona obligatorio y que el combo mostrara las zonas ligadas al user que está creando el alta.

En el caso de Venta Directa es indispensable.

@MACEMP que opinas de ello?

**Comment by minigoBinpar** [comment]
Hablado con Cristian.

Zona no se mostrará en VD y CP será obligatorio

**Comment by MACEMP** [comment]
De acuerdo!
@minigoBinpar
