### ISSUE TITLE
TIEMPO DE DESCARGA HISTORICO PROMOCION EXCESIVO

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#7]
La descarga del Excel puede durar más de 20 minutos,  acotando por fechas
@CristianBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 

Ciertamente. El problema es que básicamente se trata de montar un excel con TODA la información habida en PRM. investigo a ver si se puede hacer de otra forma pero son una gran cantidad de datos igualmente...

¿Quizás acortando los resultados con algún filtro predefinido?

**Comment by minigoBinpar** [comment]
@MACEMP 
Hemos bajado los tiempos. En breves subo versión y me dices :)

**Comment by MACEMP** [comment]
He realizado la siguiente prueba:
HISTORICO PROMOCIONES ALEX NIETO: 6''36
HISTORICO PROMOCIONES NOEMÍ MARTIN: 6''30
HISTORICO PROMOCIONES ALEX & NOEMÍ: 13''57
Como no tengo registros de antes, no puedo comparar, pero la sensación es que va  más rápido
La exportación a Excel 1'51''. Más rápido que antes o esa es la impresión.
@minigoBinpar

**Comment by minigoBinpar** [comment]
6 minutos!?
Estamos hablando de beta, verdad?
Acabo de hacer pruebas con Noemí y el histórico de promociones me ha tardado 50 segundos.

¿Puedes volver a probar?

**Comment by MACEMP** [comment]
Si, las pruebas las hice en beta el viernes.
Acabo de hacer más:
Filtro PROMOTOR ALEX: 10''
Filtro LIBRO ALCAZAR: 4''
Filtro ALBACETE: sin resultados porque se quedó el filtro ALCAZAR fijado, pero no lo marcaba con el icono de filtro aplicado
Filtro ALBACETE: 5''63 - DESCARGA EXCEL 6'' 
Sin duda la velocidad ha mejorado **MUCHIIIISIMO**. Falta solucionar el problemilla de que no aparece el simbolo FILTRO , a pesar de que está activado.
![image](https://cloud.githubusercontent.com/assets/22589031/24343854/eb67c848-12c8-11e7-910b-63d46d27d662.png)
@minigoBinpar
