### ISSUE TITLE
MENSAJE : ENVIO EN PROMOCIÓN 

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#70]
Me comentan los promotores que cuando se elige la opción ENVIAR EN PROMOCIÓN, los docentes no están recibiendo el mail que les anuncia que van a recibir el ejemplar.
Alex ha realizado una prueba, no en beta, en pro, y no ha recibido ningún mensaje.
Me comentan también que sería conveniente incluir el NOMBRE Y TELEFONO del promotor de la zona.
@CristianBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 
perdona ángeles, que acción es ENVIAR EN PROMOCIÓN?

**Comment by minigoBinpar** [comment]
@MACEMP 

Recuperado secciones:

![image](https://user-images.githubusercontent.com/20515815/27690919-dff105c4-5ce2-11e7-8c1a-5c86a19345b5.png)

Lo del mensaje es raro. En la versión actual de beta responde bien:

![image](https://user-images.githubusercontent.com/20515815/27691064-474f8efc-5ce3-11e7-9a25-a9ee58cbc4b2.png)

Debería quedar solucionado tras la subida a producción

**Comment by MACEMP** [comment]
Ahora en beta todavía no se ven los iconos asociados a producto papel. Imagino que cuando subas versión lo veré ;-)
@minigoBinpar
