### ISSUE TITLE
KPI VENTA DIRECTA

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#71]
Estos son los KPI que Luis Blecua quiere que aparezcan en la página de inicio del usuario venta direccta

_-	Sobre histórico de operaciones dadas de alta:
      o	Numero total, separado en ganadas, perdidas y en curso: en nº y € como suma de la oferta presentada
-	En detalle las operaciones en curso siempre en nº y € oferta
     o	De meses pasados
     o	Del mes presente
     o	De meses futuros
-	En detalle de las operaciones en curso:
     o	Fases de venta
-	En detalle del mes:
     o	Ganadas
     o	Perdidas
Adicionalmente la posibilidad para cada uno en función de sus autorizaciones de sacar un listado a Excel de todo filtrado por las diferentes características._
¿Cómo lo véis? ¿se podría implementar?
@CristianBinpar

**Comment by MACEMP** [comment]
Confirmado con Luis Blecua. Se elimina el apartado En los meses futuros porque no tiene sentido.
@minigoBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 
El informe para VD y AdministradoresVD constará de los siguientes filtros:
- Fecha
- Material
- Código Postal
- Vendedores VD (sólo AdministradoresVD)
- Estado

**Comment by MACEMP** [comment]
¿Podría incluirse Fase de la oportunidad?
¿Cómo puedo acceder como administrador al PRM - VD?
@minigoBinpar

**Comment by MACEMP** [comment]
Me he dado cuenta de que ESTADO = Fase de la oportunidad. 
Luis solicita se incluya Cliente como filtro ¿es posible?
@minigoBinpar
