### ISSUE TITLE
INFORME ASIGNATURAS: campo curso contiene datos CURSO y AÑO ACADÉMICO

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#72]
![image](https://cloud.githubusercontent.com/assets/22589031/25695086/06847214-30b2-11e7-98dc-9dbed1a4bbc1.png)
Al descargar el INFORME ASIGNATURAS, el campo CURSO contiene tanto datos del curso (1,2,3,4,5,6) como datos del AÑO ACADEMICO (2016-2017, 2017-2018). Realmente solo debiera de aportar datos del curso, no del año académico.
¿De dónde toma el dato? En los registros que indican 2016-2017 o 2017-2018 se introdujeron directamente en el PRM y no fueron importados desde los Excel.
Por otra parte, habría que sustituir en la bbdd 1º/2º.... por 1-2-3 en todos los registros. 
En el PRM el curso se indica 1-2-3-4-5-6, no con ordinales.
 
@CristianBinpar @minigoBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 
Al crear una adopción (o reconfirmar) es cuando se crean las EntityAcademics (asignaturas), no obstante, no está bien definido si curso hace referencia a año académico o a curso actual.

Entiendo que se trataría de este último, permitiendo sólo un valor cardinal. Voy a ajustar la introducción de datos para que no permita más de un valor.

![image](https://user-images.githubusercontent.com/20515815/27591676-b0272a94-5b52-11e7-8095-e6dc8d7f389c.png)

También he corregido la vista del informe porque no estaba muy fina.
