### ISSUE TITLE
ADOPCIONES NO APARECE EL AÑO ACADÉMICO 2017-2018

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#8]
No se reflejan en el Informe ADOPCIONES las adopciones del curso 2017-2018 y tampoco aparecen en los filtros.
El último año académico que aparece es 2016-2017.
Los datos de la adopción están correctamente creados (ver imagen)

![image](https://cloud.githubusercontent.com/assets/22589031/19654742/ee5d3dbc-9a19-11e6-81be-be12f872f911.png)

DATOS DEL CONTACTO
https://prm.medicapanamericana.com/Contacts/ShowContact@0da7ec60-d11b-4551-bced-05565db94ec4 

![image](https://cloud.githubusercontent.com/assets/22589031/19654862/3d04e87a-9a1a-11e6-90ab-3a7997043275.png)
@CristianBinpar

**Comment by minigoBinpar** [comment]
![image](https://cloud.githubusercontent.com/assets/20515815/20318615/3556dafe-ab6b-11e6-9110-28802aa1172e.png)
![Uploading image.png…]()
