### ISSUE TITLE
Cargar lista de hospitales para alta de usuarios

### ISSUE THREAD

**Issue by CristianBinpar** [BinPar/PRM#80]
@Al3xBinpar dispone de la lista, 
verificar con @MACEMP si la lista está actualizada

**Comment by MACEMP** [comment]
Rosa informa que Luis Blecua ya está al tanto y está preparando el listado
@CristianBinpar @minigoBinpar

**Comment by CristianBinpar** [comment]
Enviado por correo el último listado.
Cargaremos los datos en CRM y la BBDD del PRM se sincronizará diariamente con ella.

**Comment by Al3xBinpar** [comment]
For you @minigoBinpar 
[CNH2016 (1).xlsx](https://github.com/BinPar/PRM/files/1080603/CNH2016.1.xlsx)
[CNH2016.pdf](https://github.com/BinPar/PRM/files/1080605/CNH2016.pdf)

**Comment by MACEMP** [comment]
Thanks!
@Al3xBinpar @minigoBinpar
