### ISSUE TITLE
Crear acceso a Luis Blecua a beta PRM

### ISSUE THREAD

**Issue by CristianBinpar** [BinPar/PRM#81]
En cuanto esté montada en la nueva máquina

**Comment by minigoBinpar** [comment]
@MACEMP 
Ángeles,

Puedes ir adelantándonos un email de contacto? Entiendo que tendrá perfil venta directa, es correcto?

**Comment by MACEMP** [comment]
Luis Blecua: lblecua@medicapanamericana.es 
Si, su perfil será de Venta Directa
¿Cómo accedo yo a Venta Directa?
@minigoBinpar

**Comment by CristianBinpar** [comment]
Creado y enviado
