### ISSUE TITLE
Interesa la opción de restringir la creación de promociones/oportunidades por material seleccionado?

### ISSUE THREAD

**Issue by Al3xBinpar** [BinPar/PRM#82]
Me refiero a no abrir nuevas promociones con el mismo material si tienes pendiente de concluir el ciclo de una con ese mismo material... 
Idem para las oportunidades de venta directa...
@CristianBinpar

**Comment by Al3xBinpar** [comment]
qué opinais? @minigoBinpar @MACEMP ?

**Comment by MACEMP** [comment]
Con un mismo contacto/entidad no tiene sentido tener dos promociones/oportunidades abiertas de un mismo material.
Veo interesante restringir la creación de un material si ya tienes una abierta con el mismo contacto/entidad.
@minigoBinpar @CristianBinpar @Al3xBinpar

**Comment by franciscorrr** [comment]
Cambios aplicados en el código, pendientes de desplegar (ya os avisamos cuando esté desplegado).

Se consideran abiertos las **Promociones** que no están en "Adopción" o en "No adoptada" en el último timeline. 

Se consideran abiertos las **Oportunidades** que no están en "Fase 5" u "Oportunidad Perdida".

Si hay abierta una promoción/oportunidad a un contacto/entidad con un material, no permitirá crear ni una promoción ni una oportunidad.
