### ISSUE TITLE
REPORTAN DESDE COLOMBIA: NO SE PUEDE CREAR MATERIAL RIVAS:Manual de Urgencias 4a Ed -e

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#84]
![image](https://cloud.githubusercontent.com/assets/22589031/26188493/c7ed2160-3b9f-11e7-9b90-364594ac3e6f.png)

No se puede crear el material ebook
RIVAS:Manual de Urgencias 4a Ed -e
EAN: 9788491100379

Motivo: el EAN se utilizó con otro material que ya está borrado.
![image](https://cloud.githubusercontent.com/assets/22589031/26188483/ba983b58-3b9f-11e7-882d-6dbdde8a5c3b.png)

Sería conveniente que, cuando un MATERIAL/EAN esté borrado,  permite su reutilización. 
La reutilización de códigos EAN no es muy frecuente, pero se produce de vez en cuando.
@CristianBinpar @minigoBinpar

**Comment by minigoBinpar** [comment]
Listo Ángeles. Se puede reutilizar el ean.

Dejo anotado el tema de reutilización de EANs.

**Comment by MACEMP** [comment]
¡GRACIAS!
¡Qué rápido!
@minigoBinpar
