### ISSUE TITLE
Consultar con Ángeles los materiales que se quieran conservar en producción

### ISSUE THREAD

**Issue by minigoBinpar** [BinPar/PRM#86]
Habría que asignarle un MaterialType y MaterialBranch

**Comment by Al3xBinpar** [comment]
@MACEMP para realizar la subida de versión en BETA borramos todos los materiales que había en laBBDDs e importamos desde la web los que había, teniendo relación con un listado que nos mandaste con el nombre SAP.
Tenemos que empezar a pensar cuál es el procedimiento que quieres que sigamos cuando llegue el momento.

**Comment by MACEMP** [comment]
Dudas: 
Actualmente los materiales del PRM se crean directamente en el PRM, no se importan de ningún sitio.
Si van a ser compartidos tanto por VD como por UNI  ¿se importarán de la WEB?
Si se importan de la WEB ¿se podría mantener la denominación SAP en el PRM mediante una relación como está ahora? ¿Cómo se  podría actualizar la denominación SAP?
Si no se produce la actualización automática podría darse el caso de un nuevo material en la WEB que pasa al CRM y no al PRM. El proceso de actualización de materiales tendrá que ser automático. ¿Es posible?
@Al3xBinpar

**Comment by MACEMP** [comment]
Consultado este punto con Rosa, se ha decidido que los materiales tengan la denominación que aparece en la WEB y no la DENOMINACIÓN SAP. Por lo tanto tomará los datos de la WEB.

@CristianBinpar @minigoBinpar
