### ISSUE TITLE
DPTO EDITORIAL SOLICITA INCORPORAR "SEPARATA" COMO TIPO DE PRODUCTO

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#89]
![image](https://cloud.githubusercontent.com/assets/22589031/26391022/4889418a-4061-11e7-8931-0f18d44c414b.png)
El item SEPARATA se incorpora en ese campo
@CristianBinpar @minigoBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 
¿Esto no es PPD?

**Comment by MACEMP** [comment]
![image](https://user-images.githubusercontent.com/22589031/27692533-3cca0e36-5ce7-11e7-87d4-8ac2153dd0d8.png)
@minigoBinpar
