### ISSUE TITLE
EBOOK JAUREGI : NO APARECE ICONO ACCESO A MATERIALES COMPLEMENTARIOS DOCENTES

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#9]
Los promotores no pueden facilitar el acceso a los materiales complementarios a los docentes de este material JAUREGI:100 TECNICAS EN OSTEOPATÍA porque no aparece el icono cuando se trata de EBOOK. El icono SI aparece cuando se trata de libro en papel
No puedo incorporar una imagen porque me da error constantemente la subida a GITHUB
@CristianBinpar

**Comment by MACEMP** [comment]
Ocurre lo mismo con otro ebook recien creado: MOORE: ANTES DE NACER. No aparece el icono para conceder el acceso a los materiales complementarios
![image](https://cloud.githubusercontent.com/assets/22589031/19696940/a3be7624-9ae9-11e6-9e53-92ad4487a874.png)
@CristianBinpar @minigoBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 

¿Puedes comprobar que ya es correcto? Creo que la solución se extiende a MOORE:
![image](https://cloud.githubusercontent.com/assets/20515815/20568711/a1d01366-b19d-11e6-9689-2f48f15e6da6.png)

**Comment by MACEMP** [comment]
Tanto el EBOOK del Moore como del Jauregi siguen sin mostrar el icono de MATERIAL COMPLEMENTARIO.
En el caso del Moore y Jauregi en papel SI que muestra el icono.
@minigoBinpar @CristianBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 

porque los ebook de MOORE y JAUREGI no tienen material complementario:

![image](https://cloud.githubusercontent.com/assets/20515815/20751179/b0f406ec-b6fa-11e6-81ca-9f43d5f5b9b4.png)

![image](https://cloud.githubusercontent.com/assets/20515815/20751186/ba25eee2-b6fa-11e6-8de4-47101ac3adad.png)

**Comment by MACEMP** [comment]
Si, si tienen material complementario:
http://www.medicapanamericana.com/materialesComplementarios/jauregi/jauregi.aspx 
http://www.medicapanamericana.com/materialesComplementarios/Moore/moore.aspx 
@minigoBinpar @CristianBinpar

**Comment by minigoBinpar** [comment]
Parece ser que el gestor no asocia los MC a ebook (tema interno de pana).

Voy a modificar PRM para que si un ebook no tiene MC pregunte si su homólogo en papel tiene

**Comment by minigoBinpar** [comment]
![image](https://cloud.githubusercontent.com/assets/20515815/20753013/8e602958-b704-11e6-97a0-608f6277bb45.png)

Ahora si. Subo versión en breves
