### ISSUE TITLE
¿Es posible modificar  en BBDD los mails de 87 profesores de la CEU CARDENAL HERRERA?

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#91]
La universidad CEU Cardenal Herrera ha modificado su dominio
actual en PRM @uch.ceu.es 
nueva  @uchceu.es

¿Sería posible sustituir la dirección en BBDD? De ese modo se evitaría que el promotor tuviese que hacerlo uno a uno?
@minigoBinpar  @CristianBinpar

**Comment by MACEMP** [comment]
¿Se podría realizar el cambio directamente en BBDD en lugar de modificar una a una las direcciones?
@minigoBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 
Listo :)

**Comment by MACEMP** [comment]
¿Están ya en la BBDD en producción?!??!??!!!?
@minigoBinpar

**Comment by minigoBinpar** [comment]
Correcto (es malo?)

**Comment by MACEMP** [comment]
NOOOOO, es magnífico!!!
Lo comunico a Alex Nieto que estará encantado.

Muchas gracias  :-)
@minigoBinpar
