### ISSUE TITLE
INFORME ADOPCIONES VALORIZADASVS ADOPCIONES: NO COINCIDEN LOS DATOS

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#92]
![image](https://cloud.githubusercontent.com/assets/22589031/26452236/854143f8-415f-11e7-956d-26d99c5f317a.png)
He descargado 2 informes de adopciones con y sin valorizar sin ningún filtro.

El número de adopciones  no es el mismo en los dos archivos ¿?
Si selecciono el año académico 2017-2018 en el informe sin valorizar aparecen adopciones de Jaime Diaz que no aparecen en el informe valorizado.
Las adopciones de Noemí y Alex coinciden.
¿Cuál es el correcto?

En un par de semanas tenemos que pasar a las librerías los listados con libros recomendados y para ello nos  basamos en las adopciones del PRM, de ahí la necesidad de saber cual está bien.
@CristianBinpar @minigoBinpar

**Comment by franciscorrr** [comment]
Hemos cambiado el mecanismo de filtrado en el informe de Adopciones Valorizadas para que coincida con el de Adopciones.

**Comment by MACEMP** [comment]
![image](https://user-images.githubusercontent.com/22589031/28317022-837cd7ea-6bc5-11e7-939d-259c74c426bf.png)
![image](https://user-images.githubusercontent.com/22589031/28317066-bcc99826-6bc5-11e7-9f52-7f4d55a9b313.png)
El número de adopciones no coincide en los dos informes
@franciscorrr @minigoBinpar

**Comment by franciscorrr** [comment]
Todavía no está desplegado en los entornos, os avisaremos cuando esté disponible

**Comment by franciscorrr** [comment]
Ya disponible en PRO

**Comment by MACEMP** [comment]
Perfecto!
Coinciden las adopciones en los dos informes.
@franciscorrr
