### ISSUE TITLE
MUSCOLINO_MATERIAL COMPLEMENTARIO EBOOK : NO APARECE EL ICONO PARA ACTIVARLO

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#93]
![image](https://cloud.githubusercontent.com/assets/22589031/26486391/379b1af6-41fb-11e7-830a-22d6f06a5332.png)
Contacto a.perez@ehu.es  
https://prm.medicapanamericana.com/Contacts/ShowContact@39c8cd9a-4461-4165-a8ab-a5f5a94c1743 

No se puede conceder acceso al material complementario asociado al ebook.
Tendría que crear una promoción en papel y conceder el acceso desde ese material, pero no es  la forma adecuada de hacerlo.
@CristianBinpar @minigoBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 
perdona, tengo algo oxidada esta parte del PRM.

Dices que al pulsar en enviar acceso a ebook no responde¿

**Comment by MACEMP** [comment]
No, no. 
Al pulsar en Material complementario no concede el acceso.
Sin embargo, si se hace la concesión de acceso desde la versión papel en lugar de la versión ebook si que lo concede.
@minigoBinpar

**Comment by minigoBinpar** [comment]
¿Y aún así esta persona no tiene acceso?:
![image](https://user-images.githubusercontent.com/20515815/27695926-8830546c-5cf0-11e7-873f-e9ee4bca3ec2.png)

**Comment by MACEMP** [comment]
Esta persona tiene acceso porque se lo dieron desde el gestor de la web, no desde el PRM.
@minigoBinpar

**Comment by franciscorrr** [comment]
Ya está solucionado (pendiente de despliegue).
![image](https://user-images.githubusercontent.com/30254281/28815408-97d32ac8-76a1-11e7-9529-61b1c12770d6.png)
Al parecer no estábamos filtrando correctamente a la hora de comprobar si el libro tenía o no materiales complementarios. Estábamos filtrando únicamente por EAN sin tener en cuenta el valor WOR_EST_ID (si el material está "activo" o no). Al no hacerlo nos estaba saliendo otro material con el mismo EAN pero que está desactivado.
![image](https://user-images.githubusercontent.com/30254281/28815501-e25912ba-76a1-11e7-996d-017eb84d2357.png)
