### ISSUE TITLE
ADOPCION FEDUCHI: APARECE ULTIMO ESTADO "incluir en pendientes" CUANDO ULTIMO ESTADO ES "adopción"

### ISSUE THREAD

**Issue by MACEMP** [BinPar/PRM#94]
![image](https://cloud.githubusercontent.com/assets/22589031/26547188/1349b14c-446e-11e7-9905-585e1437c8be.png)
La promoción del FEDUCHI en este contacto tiene como último estado la ADOPCION, sin embargo el icono indica INCLUIR EN PENDIENTES.
En los informes aparece correctamente como ADOPCIÓN.

Esta es una de las adopciones que aparece en el excel que yo descargo de PROMOCIONES VALORIZADAS como asignada a Jaime Díaz mientras que en el Excel que se descarga Noemí aparece como suya.
@CristianBinpar @minigoBinpar

**Comment by minigoBinpar** [comment]
@MACEMP 
Sospecho que el problema es que ambas acciones tienen una misma fecha (con horas a 00:00:00). El sistema ordena por este parámetro. Al tener valor idéntico, toma primero el "incluir en pendientes" siguiendo criterios internos.

Supongo que estos datos vienen dados de alguna importación (no se incluyó horas).

Ahora mismo si incluye horas en todas las acciones llevadas a cabo:
![image](https://user-images.githubusercontent.com/20515815/27633093-21bf6350-5bfe-11e7-8d44-67c15ac1e9c6.png)

He editado los parámetros de la adopción en la base de datos y ahora figura así:
![image](https://user-images.githubusercontent.com/20515815/27633156-62a42310-5bfe-11e7-85e6-86ed45fd48f7.png)

**Comment by MACEMP** [comment]
Gracias!
Tiene lógica la explicación
@minigoBinpar
